import {env} from 'cloudflare:workers';
import {database,failure,HttpError,identity,json,operator,sameOrigin} from '@/lib/market/server';

const allowed=new Set(['image/jpeg','image/png','application/pdf']);
const kinds=new Set(['invoice','purchase-proof','warehouse-photo','warehouse-report']);
function bucket(){if(!env.BUCKET)throw new HttpError(503,'Хранилище документов недоступно.');return env.BUCKET}
function validMagic(bytes:Uint8Array,type:string){return type==='image/jpeg'?bytes[0]===0xff&&bytes[1]===0xd8:type==='image/png'?bytes.slice(0,8).every((v,i)=>v===[137,80,78,71,13,10,26,10][i]):type==='application/pdf'?new TextDecoder().decode(bytes.slice(0,5))==='%PDF-':false}

export async function GET(request:Request){try{const user=await identity(),url=new URL(request.url),id=url.searchParams.get('id');if(id){const row=await database().prepare('SELECT customer_id,object_key,filename,content_type FROM market_order_documents WHERE id=?').bind(id).first<{customer_id:string;object_key:string;filename:string;content_type:string}>();if(!row||(!operator(user.email)&&row.customer_id!==user.userId))throw new HttpError(404,'Документ не найден.');const object=await bucket().get(row.object_key);if(!object)throw new HttpError(404,'Файл документа не найден.');return new Response(object.body,{headers:{'Content-Type':row.content_type,'Content-Disposition':`attachment; filename="${encodeURIComponent(row.filename)}"`,'Cache-Control':'private, no-store'}})}const accountId=operator(user.email)&&url.searchParams.get('accountId')?url.searchParams.get('accountId')!:user.userId;const rows=await database().prepare('SELECT id,order_id,kind,filename,content_type,size,created_at FROM market_order_documents WHERE customer_id=? ORDER BY created_at DESC LIMIT 100').bind(accountId).all();return json({documents:rows.results})}catch(error){return failure(error)}}

export async function POST(request:Request){try{sameOrigin(request);const user=await identity();if(!operator(user.email))throw new HttpError(403,'Доступно только администратору.');const form=await request.formData(),file=form.get('file'),orderId=String(form.get('orderId')??''),customerId=String(form.get('customerId')??''),kind=String(form.get('kind')??'');if(!(file instanceof File)||!orderId||!customerId||!kinds.has(kind))throw new HttpError(400,'Проверьте заказ, тип и файл.');if(file.size<20||file.size>8_000_000||!allowed.has(file.type))throw new HttpError(400,'Поддерживаются JPG, PNG и PDF до 8 МБ.');const owned=await database().prepare('SELECT id FROM market_order_records WHERE id=? AND customer_id=?').bind(orderId,customerId).first();if(!owned)throw new HttpError(404,'Заказ не найден в операционной базе. Сначала синхронизируйте данные.');const bytes=new Uint8Array(await file.arrayBuffer());if(!validMagic(bytes,file.type))throw new HttpError(400,'Содержимое файла не соответствует формату.');const id='ORDDOC-'+crypto.randomUUID(),key=`orders/${encodeURIComponent(customerId)}/${orderId}/${id}`,now=Date.now();await bucket().put(key,bytes,{httpMetadata:{contentType:file.type}});try{await database().prepare('INSERT INTO market_order_documents (id,order_id,customer_id,kind,object_key,filename,content_type,size,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,orderId,customerId,kind,key,file.name.slice(0,180),file.type,file.size,user.userId,now).run()}catch(error){await bucket().delete(key);throw error}return json({document:{id,order_id:orderId,kind,filename:file.name.slice(0,180),content_type:file.type,size:file.size,created_at:now}},201)}catch(error){return failure(error)}}
