import test from 'node:test';
import assert from 'node:assert/strict';
import {extractProduct,parseWeight,safeImage} from '../lib/importer/extract.ts';
import {allowedUrl,fetchProduct} from '../lib/importer/fetch.ts';
import {customsVersion,paddedWeight,toUsd} from '../lib/market/world.ts';
import {applyAction} from '../lib/market/actions.ts';
import {blank,products,quote,checkoutCart,addToCart,cartSignature} from '../lib/market/domain.ts';
test('JSON-LD extracts title, image, price/currency, shipping and packaged weight',()=>{
const html=`<script type="application/ld+json">{"@context":"https://schema.org","@type":"Product","name":"Zapatos &amp; cosas","image":["https://i.ebayimg.com/image.jpg"],"shippingWeight":{"value":1500,"unitCode":"GRM"},"offers":{"@type":"Offer","price":"99.95","priceCurrency":"EUR","shippingDetails":{"shippingRate":{"value":4.5,"currency":"EUR"},"shippingDestination":{"addressCountry":"ES"}}}}</script>`;
const p=extractProduct(html,'https://www.ebay.es/itm/123');assert.equal(p.title,'Zapatos & cosas');assert.equal(p.price,99.95);assert.equal(p.currency,'EUR');assert.equal(p.shipping,4.5);assert.equal(p.shippingDestination,'ES');assert.equal(p.boxedWeight,1.5);assert.equal(p.weightKind,'shipping');assert.equal(p.country,undefined);
});
test('missing shipping remains unknown and aggregate lower bounds are not exact prices',()=>{const p=extractProduct('<script type="application/ld+json">{"@type":"Product","name":"Item","offers":{"@type":"AggregateOffer","lowPrice":10,"highPrice":100,"priceCurrency":"USD"}}</script>','https://ebay.com/itm/x');assert.equal(p.shipping,undefined);assert.equal(p.price,undefined);assert(p.warnings.length>0)});
test('OG fallback and escaped names render as text, never executable markup',()=>{const p=extractProduct(`<meta property='og:title' content='Product &amp; Shoes'><meta property='og:image' content='/image.jpg'><meta property='product:price:amount' content='12.50'><meta property='product:price:currency' content='USD'>`,'https://nike.com/item');assert.equal(p.title,'Product & Shoes');assert.equal(p.price,12.5);assert.equal(p.image,'https://nike.com/image.jpg');assert.equal(safeImage('javascript:alert(1)','https://nike.com'),undefined)});
test('units and boxed weight margin are explicit and applied once',()=>{assert.equal(parseWeight({value:2,unitCode:'LBR'}),.908);assert.equal(parseWeight({value:2}),undefined);assert.equal(paddedWeight(1.2),1.7);assert.equal(paddedWeight(.1),.6);assert.throws(()=>paddedWeight(50));assert.equal(toUsd(100,'EUR'),110)});
test('source fetch rejects private URLs, deceptive domains and foreign redirects',async()=>{for(const u of ['http://ebay.com/x','https://127.0.0.1','https://ebay.com.evil.com','https://evil.ebay.com','https://user:pw@ebay.com/x','https://ebay.com:8080'])assert.throws(()=>allowedUrl(u));const original=globalThis.fetch;globalThis.fetch=async()=>new Response('',{status:302,headers:{Location:'http://169.254.169.254/latest'}});try{await assert.rejects(()=>fetchProduct('https://ebay.com/itm/1'))}finally{globalThis.fetch=original}});
test('fetch parses readable pages and rejects oversized responses',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response('<meta property="og:title" content="Demo listing">',{headers:{'Content-Type':'text/html'}});try{assert.equal((await fetchProduct('https://ebay.es/itm/1')).title,'Demo listing');globalThis.fetch=async()=>new Response('x'.repeat(2_000_001),{headers:{'Content-Type':'text/html'}});await assert.rejects(()=>fetchProduct('https://ebay.es/itm/1'))}finally{globalThis.fetch=original}});
test('server recomputes country currency, domestic shipping and padded weight',()=>{const p={...products[0],sourceUrl:'https://ebay.es/itm/12',sourcePrice:100,sourceCurrency:'EUR',sourceShipping:5,shippingKnown:true,boxedWeight:1.2,country:'Испания',weight:49,usd:1};const s=applyAction(blank(),{type:'cart-add',product:p,variant:p.variants[0]},false);assert.equal(s.cart[0].product.weight,1.7);assert.equal(s.cart[0].product.usd,110);assert.equal(s.cart[0].quote.sourceShipping,70400);assert.equal(s.cart[0].quote.weight,1.7);assert.equal(s.cart[0].quote.total,s.cart[0].quote.merchandise+s.cart[0].quote.service+s.cart[0].quote.shipping+s.cart[0].quote.reserve+70400)});
test('checkout needs recorded customs consent and warehouse actions require operator',()=>{let s=addToCart(blank(),products[0],products[0].variants[0]);assert.throws(()=>checkoutCart(s,'x',cartSignature(s.cart),false));s=checkoutCart(s,'x',cartSignature(s.cart),false,Date.now(),customsVersion);assert.equal(s.orders[0].customsConsent.version,customsVersion);assert.throws(()=>applyAction(s,{type:'advance',id:s.orders[0].id,expected:0},false));const n=applyAction(s,{type:'advance',id:s.orders[0].id,expected:0},true);assert.equal(n.orders[0].status,1)});
test('adding a photo keeps the original order quote unchanged',()=>{let s=addToCart(blank(),{...products[0],sourceUrl:'https://ebay.com/itm/1',shippingKnown:true},products[0].variants[0]);s=checkoutCart(s,'x',cartSignature(s.cart),false,Date.now(),customsVersion);const before=JSON.stringify(s.orders[0].quote);s=applyAction(s,{type:'order-image',id:s.orders[0].id,image:'https://i.ebayimg.com/image.jpg'},false);assert.equal(s.orders[0].product.image,'https://i.ebayimg.com/image.jpg');assert.equal(JSON.stringify(s.orders[0].quote),before)});
