export type Extracted={title?:string;image?:string;price?:number;currency?:string;shipping?:number;shippingCurrency?:string;shippingDestination?:string;boxedWeight?:number;weightKind?:'shipping'|'net';country?:string;warnings:string[];sourceUrl:string;method:string};
const clean=(s:unknown)=>typeof s==='string'?s.replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(Number(n),0x10ffff))).trim():'';
const number=(v:unknown)=>{if(typeof v==='number')return Number.isFinite(v)&&v>=0?v:undefined;if(typeof v!=='string')return undefined;const n=Number(v.replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)&&n>=0?n:undefined};
export function safeImage(value:unknown,base:string){const s=typeof value==='string'?value:typeof value==='object'&&value?String((value as Record<string,unknown>).url??(value as Record<string,unknown>).contentUrl??''):'';try{const u=new URL(s,base);if(!s||u.protocol!=='https:'||u.username||u.password||u.port||!u.hostname.includes('.')||/^[\d.:\[\]]+$/.test(u.hostname)||u.hostname.endsWith('.local')||u.hostname==='localhost')return undefined;return u.href}catch{return undefined}}
export function parseWeight(value:unknown){if(!value||typeof value!=='object')return undefined;const q=value as Record<string,unknown>,n=number(q.value);if(n===undefined||n<=0)return undefined;const unit=String(q.unitCode??q.unitText??'').toLowerCase();const factor=({kg:1,kilogram:1,kilograms:1,kgm:1,g:.001,gram:.001,grams:.001,grm:.001,lb:.45359237,lbs:.45359237,lbr:.45359237,oz:.0283495231,onz:.0283495231} as Record<string,number>)[unit];return factor?Math.ceil(n*factor*1000)/1000:undefined}
const regionNames:Record<string,string>={US:'США',ES:'Испания',DE:'Германия',GB:'Великобритания',FR:'Франция',IT:'Италия',CN:'Китай',TR:'Турция',JP:'Япония',KR:'Южная Корея',AE:'ОАЭ',CA:'Канада',AU:'Австралия'};
export function extractProduct(html:string,sourceUrl:string):Extracted {
 const meta:Record<string,string>={};for(const tag of html.match(/<meta\b[^>]*>/gi)??[]){const a:Record<string,string>={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))a[m[1].toLowerCase()]=clean(m[2]??m[3]);const key=a.property??a.name??a.itemprop;if(key&&a.content)meta[key.toLowerCase()]=a.content;}
 // JSON-LD has no fixed shape; traversal is bounded by depth and node count below.
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
 const nodes:Record<string,any>[]=[];
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
 const walk=(x:any,depth=0)=>{if(depth>15||nodes.length>4000||!x||typeof x!=='object')return;if(Array.isArray(x)){for(const y of x)walk(y,depth+1)}else{nodes.push(x);for(const y of Object.values(x))walk(y,depth+1)}};
 for(const match of html.matchAll(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{walk(JSON.parse(match[1]))}catch{}}
 const p=nodes.find(n=>[n['@type']].flat().some(t=>t==='Product'||t==='ProductGroup'));
 const offers=p?.offers;const offer=Array.isArray(offers)?offers[0]:offers;const details=offer?.shippingDetails;const ship=Array.isArray(details)?details[0]:details;
 const rate=ship?.shippingRate,shipping=number(rate?.value??rate?.price);const destination=ship?.shippingDestination?.addressCountry;
 const image=safeImage(Array.isArray(p?.image)?p.image[0]:p?.image??meta['og:image']??meta['twitter:image'],sourceUrl);
 // Aggregate/auction lowPrice is not a buy-now price. Never substitute it.
 const price=number(offer?.price??offer?.priceSpecification?.price??meta['product:price:amount']??meta['og:price:amount']);
 const currency=clean(offer?.priceCurrency??offer?.priceSpecification?.priceCurrency??meta['product:price:currency']??meta['og:price:currency']).toUpperCase()||undefined;
 const title=clean(p?.name??meta['og:title']??meta['twitter:title']??html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]).slice(0,140)||undefined;
 const gross=parseWeight(p?.shippingWeight),net=parseWeight(p?.weight);const loc=offer?.availableAtOrFrom?.address?.addressCountry??p?.offers?.shippingOrigin?.addressCountry;
 const warnings:string[]=[];if(!price)warnings.push('Цена не найдена: укажите её со страницы выбранного варианта.');if(shipping===undefined)warnings.push('Доставка магазина не найдена. Это не означает бесплатную доставку.');if(!gross&&!net)warnings.push('Вес не опубликован. Предложим приблизительный вес по категории.');if(net&&!gross)warnings.push('Магазин указал вес товара; вес коробки может не входить. Проверьте поле веса.');if(Array.isArray(offers)&&offers.length>1)warnings.push('Найдено несколько предложений: показано первое. Проверьте вариант и цену.');if(offer?.['@type']==='AggregateOffer')warnings.push('Указан диапазон цен. Нужна цена конкретного варианта.');
 return {title,image,price,currency,shipping,shippingCurrency:clean(rate?.currency)||currency,shippingDestination:typeof destination==='string'?destination:undefined,boxedWeight:gross??net,weightKind:gross?'shipping':net?'net':undefined,country:regionNames[String(loc).toUpperCase()],warnings,sourceUrl,method:p?'JSON-LD':'Open Graph'};
}
