import {extractProduct} from './extract.ts';
const roots=['ebay.com','ebay.es','ebay.de','ebay.co.uk','ebay.fr','ebay.it','ebay.ca','ebay.com.au','nike.com','zara.com','mango.com','massimodutti.com','amazon.com','amazon.es','amazon.de','amazon.co.uk','amazon.fr','amazon.it','amazon.co.jp','amazon.ca','amazon.com.au','amazon.ae','amazon.com.tr','zarahome.com','asos.com','hm.com','uniqlo.com','apple.com','bestbuy.com','fnac.es','elcorteingles.es','iherb.com','aliexpress.com'];
export function allowedUrl(value:string){const u=new URL(value);const host=u.hostname.toLowerCase();if(u.protocol!=='https:'||u.username||u.password||u.port||!roots.some(r=>host===r||host==='www.'+r||(['mango.com','hm.com','uniqlo.com'].includes(r)&&host==='shop.'+r)))throw Error('Автозагрузка этого магазина пока не подключена. Заполните товар вручную.');return u;}
export async function fetchProduct(value:string){let url=allowedUrl(value);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{
 let response:Response|undefined;for(let i=0;i<4;i++){response=await fetch(url,{redirect:'manual',signal:controller.signal,headers:{'Accept':'text/html,application/xhtml+xml','User-Agent':'AtlasProductPreview/1.0','Accept-Language':'en-US,en;q=0.8'}});if(response.status>=300&&response.status<400){const location=response.headers.get('location');await response.body?.cancel();if(!location||i===3)throw Error('Магазин перенаправляет запрос. Используйте прямую ссылку на товар.');url=allowedUrl(new URL(location,url).href);continue}break}
 if(!response?.ok)throw Error('Магазин не разрешил загрузить страницу. Заполните данные вручную.');
 if(!response.headers.get('content-type')?.includes('text/html')){await response.body?.cancel();throw Error('По ссылке нет HTML-страницы товара.')}
 const reader=response.body?.getReader();if(!reader)throw Error('Пустая страница');let size=0;let html='';const decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>2_000_000){await reader.cancel();throw Error('Страница слишком большая для автозагрузки. Заполните данные вручную.')}html+=decoder.decode(value,{stream:true})}html+=decoder.decode();
 if(/captcha|verify you are human|pardon our interruption|robot check/i.test(html.slice(0,60000)))throw Error('Магазин запросил проверку посетителя. Используйте ручной ввод.');
 return extractProduct(html,url.href);
 }finally{clearTimeout(timer)}}
