"use client";

import { useState } from "react";
import Link from "@/components/site-link";
import { ArrowUpRight, Check, Download, FileCheck2, FileText, LogOut, MessageCircle, Package, Plus, ScanLine, ShieldCheck, Upload, UserRound, Wallet } from "lucide-react";
import { useMarket } from "@/lib/market/store";
import { customsReferences as customsSources } from "@/lib/market/customs";
import { CustomsCalculator } from "./customs-estimate";
import { balanceOf, money, statuses } from "@/lib/market/domain";
import { toast } from "sonner";
import { Modal, PageHeading } from "./market-ui";

export function AccountView() {
  const { user, state, ready, act } = useMarket();
  const lang=state.communication.language;
  const labels={ru:{title:"Личный кабинет",intro:"Ваши покупки, получатели и документы.",settings:"Профиль и настройки",manage:"Управление Atlas",addresses:"Получатели и адреса",documents:"Документы",support:"Поддержка",limits:"Таможенный ориентир"},uz:{title:"Shaxsiy kabinet",intro:"Xaridlar, qabul qiluvchilar va hujjatlar.",settings:"Profil va sozlamalar",manage:"Atlas boshqaruvi",addresses:"Qabul qiluvchilar va manzillar",documents:"Hujjatlar",support:"Yordam",limits:"Bojxona bahosi"},en:{title:"Your account",intro:"Purchases, recipients and documents.",settings:"Profile & settings",manage:"Manage Atlas",addresses:"Recipients & addresses",documents:"Documents",support:"Support",limits:"Customs estimate"}}[lang];
  const [legacy, setLegacy] = useState<string | null>(null);
  const [addressOpen, setAddressOpen] = useState(false);
  const [ticket, setTicket] = useState({ subject: "", text: "" });
  const activeOrders=state.orders.filter(order=>!order.cancelled&&order.status<5);
  function exportProfile() {
    const payload = JSON.stringify({ exportedAt: new Date().toISOString(), profile: user, deliveryProfiles: state.deliveryProfiles, communication: state.communication, orders: state.orders, entries: state.entries, declarations: state.declarations, supportTickets: state.supportTickets }, null, 2);
    const url = URL.createObjectURL(new Blob([payload], { type: "application/json" }));
    const link = document.createElement("a");
    link.href = url; link.download = "atlas-profile-export.json"; link.click();
    URL.revokeObjectURL(url);
    toast.success("Экспорт профиля подготовлен");
  }
  return <>
    <PageHeading overline="ATLAS" title={labels.title} description={labels.intro}>{user?.operator&&<Link className="btn secondary" href="/admin">{labels.manage}<ArrowUpRight size={17}/></Link>}</PageHeading>
    {!user ? <section className="surface"><UserRound size={36} /><h2>Вход и создание аккаунта</h2><p>Войдите через ChatGPT — профиль Atlas создастся автоматически. Ваши находки, адреса и заказы будут доступны в одном кабинете.</p><a className="btn primary" href="/signin-with-chatgpt?return_to=%2Faccount" target="_top">Продолжить с ChatGPT <ArrowUpRight size={18} /></a></section> : <>
      <section className="surface account-status"><div className="section-heading"><div><span className="eyebrow">СЛЕДУЮЩЕЕ ДЕЙСТВИЕ</span><h2>Центр заказов</h2></div><Link className="text-link" href="/orders">Все заказы <ArrowUpRight size={16}/></Link></div>{activeOrders.length ? activeOrders.slice(0, 1).map(order => <article className="status-center-row" key={order.id}><Package size={20}/><div><b>{order.product.name}</b><span>{order.cancelled ? "Отменён" : statuses[order.status]}</span><small>{order.status === 0 ? "Откройте заказ, чтобы проверить оплату и выкуп." : order.status === 5 ? "Заказ завершён." : "Следите за изменениями в карточке заказа."}</small></div><Link className="text-link" href={"/orders#"+order.id}>Открыть</Link></article>) : <p>{state.orders.length ? "Все заказы завершены. История доступна в разделе «Мои заказы»." : "Пока нет заказов. Выберите товар в каталоге или добавьте ссылку."}</p>}</section>
      <div className="account-grid">
        <details className="surface account-settings"><summary>{labels.settings}</summary><div className="account-avatar"><UserRound size={30} /></div><h2>{user.name}</h2><p>{user.email}</p><p className="micro">Роль: {user.operator ? "администратор и покупатель" : "покупатель"} · профиль создан {new Date(user.createdAt).toLocaleDateString("ru-RU")}</p>
          {state.deliveryProfile ? <div className="saved-address"><b>Основной получатель</b><span>{state.deliveryProfile.recipient} · {state.deliveryProfile.phone}</span><small>{state.deliveryProfile.region}, {state.deliveryProfile.city}, {state.deliveryProfile.address}</small></div> : <div className="notice"><ShieldCheck size={20} /><span>Адрес сохранится после первого оформления заказа.</span></div>}
          <div className="profile-actions"><button className="btn secondary" onClick={exportProfile}><Download size={17} /> Скачать мои данные</button><a className="text-link" href="/signout-with-chatgpt?return_to=%2Faccount" target="_top"><LogOut size={16} /> Выйти</a></div>
        </details>
        <section className="surface account-links">
          <Link href="/identity"><ScanLine /><div>Паспорт<small>{state.identityProfile ? "Данные подтверждены" : "Нужно подтвердить"}</small></div><ArrowUpRight /></Link>
          <Link href="/declaration"><FileCheck2 /><div>Декларации<small>{state.declarations.length} подготовленных пакетов</small></div><ArrowUpRight /></Link>
          <Link href="/orders"><Package /><div>Мои заказы<small>{state.orders.length} заказов</small></div><ArrowUpRight /></Link>
          <Link href="/balance"><Wallet /><div>Баланс Atlas<small>{money(balanceOf(state))}</small></div><ArrowUpRight /></Link>
          <Link href="/notifications"><ShieldCheck /><div>Email и SMS<small>{state.communication.emailEnabled || state.communication.smsEnabled ? "Настроены" : "Выключены"}</small></div><ArrowUpRight /></Link>
          <Link href="/legal"><FileText /><div>Правила Atlas<small>Условия и конфиденциальность</small></div><ArrowUpRight /></Link>
          <Link href="/customs"><ShieldCheck /><div>Таможенные условия<small>Лимиты и согласие</small></div><ArrowUpRight /></Link>
        </section>
      </div>

      <div className="account-grid account-tools">
        <details className="surface ux-disclosure"><summary>{labels.addresses}</summary><div className="section-heading"><div><span className="eyebrow">ПОЛУЧАТЕЛИ</span><h2>Адреса доставки</h2></div><button className="icon-btn" aria-label="Добавить адрес" onClick={() => setAddressOpen(true)}><Plus size={18}/></button></div>{state.deliveryProfiles.length ? state.deliveryProfiles.map(profile => <div className="saved-address" key={profile.id}><b>{profile.label}{profile.primary ? " · основной" : ""}</b><span>{profile.recipient} · {profile.phone}</span><small>{profile.region}, {profile.city}, {profile.address}</small><button className="text-button" onClick={() => void act({ type: "delivery-profile-remove", id: profile.id })}>Удалить</button></div>) : <p>Сохраните несколько получателей — при оформлении сможете выбрать нужного.</p>}</details>
        <details className="surface ux-disclosure"><summary>{labels.limits}</summary><span className="eyebrow">ЛИМИТЫ МЕСЯЦА</span><h2>Профиль таможенного риска</h2><strong className="customs-limit">${Math.round(state.orders.filter(order => new Date(order.createdAt).getMonth() === new Date().getMonth() && new Date(order.createdAt).getFullYear() === new Date().getFullYear()).reduce((sum, order) => sum + order.quote.merchandise / (order.quote.fx ?? 12800), 0))}</strong><p>Сумма ваших тестовых заказов за текущий месяц. Это подсказка, а не официальный остаток лимита: Atlas не видит покупки в других сервисах.</p><Link className="text-link" href="/customs">Проверить условия <ArrowUpRight size={16}/></Link></details>
      </div>
      <div className="account-grid account-tools">
        <details className="surface ux-disclosure"><summary>{labels.documents}</summary><span className="eyebrow">ДОКУМЕНТЫ И ДАННЫЕ</span><h2>Центр документов</h2><p>Паспорт хранится отдельно; декларации создаются только после вашего подтверждения. Счета и фото склада появятся в конкретном заказе, когда оператор добавит их.</p><div className="profile-actions"><Link className="btn secondary" href="/identity"><ScanLine size={16}/> Паспорт</Link><Link className="btn secondary" href="/declaration"><FileCheck2 size={16}/> Декларации</Link><button className="btn secondary" onClick={exportProfile}><Download size={16}/> Экспорт</button></div></details>
        <details className="surface ux-disclosure" id="support"><summary>{labels.support}{state.supportTickets.some(t=>t.status==="answered")?" · ●":""}</summary><span className="eyebrow">ПОДДЕРЖКА</span><h2>Обращения</h2>{state.supportTickets.length ? <div className="ticket-list">{state.supportTickets.slice(0,3).map(item => <div key={item.id}><b>{item.subject}</b><small>{item.status === "open" ? "Ждём ответа" : item.status === "answered" ? "Есть ответ" : "Закрыто"} · {item.replies.length} сообщений</small><details><summary>Открыть историю</summary>{item.replies.map(reply => <p className="ticket-reply" key={reply.id}><b>{reply.author === "support" ? "Поддержка" : "Вы"}</b><br/>{reply.text}</p>)}{item.status !== "closed" && <form className="support-reply-form" onSubmit={async event => { event.preventDefault(); const form = event.currentTarget; const input = form.elements.namedItem("reply") as HTMLInputElement; if (await act({ type: "support-reply", id: item.id, text: input.value })) input.value = ""; }}><input name="reply" required minLength={3} placeholder="Ответить по обращению"/><button className="btn secondary">Ответить</button></form>}</details></div>)}</div> : <p>Напишите нам — история обращения останется в вашем профиле.</p>}<form className="support-form" onSubmit={async event => { event.preventDefault(); if (await act({ type: "support-create", subject: ticket.subject, text: ticket.text })) { setTicket({ subject: "", text: "" }); toast.success("Обращение отправлено в тестовую очередь."); } }}><input required minLength={3} placeholder="Тема обращения" value={ticket.subject} onChange={event => setTicket({ ...ticket, subject: event.target.value })}/><textarea required minLength={3} placeholder="Опишите вопрос" value={ticket.text} onChange={event => setTicket({ ...ticket, text: event.target.value })}/><button className="btn secondary" disabled={!ready}><MessageCircle size={16}/> Отправить обращение</button></form></details>
      </div>
      <details className="surface ux-disclosure legacy-import"><summary>Перенос прежних данных</summary><h2>Заказы из предыдущей версии</h2><p>Если в этом браузере уже есть данные Atlas, можно один раз перенести их в пустой профиль.</p><button className="btn secondary" disabled={!ready || !!(state.orders.length || state.cart.length || state.entries.length || state.favorites.length)} onClick={() => { try { const raw = localStorage.getItem("atlas-market-demo-v1"); if (!raw) { toast.message("В этом браузере старых данных нет."); return; } setLegacy(raw); } catch { toast.error("Нет доступа к данным браузера."); } }}><Upload size={16} /> Найти прежние заказы</button></details>
    </>}
    <Modal open={!!legacy} onClose={() => setLegacy(null)} title="Перенести данные?" description="Будут перенесены заказы, корзина, избранное и баланс Atlas из этого браузера. Подтвердите, что это ваши данные."><button className="btn primary" onClick={async () => { if (legacy && await act({ type: "import-legacy", data: legacy })) { setLegacy(null); toast.success("Данные перенесены в аккаунт."); } }}>Это мои данные — перенести <Check size={18} /></button></Modal>
    <Modal open={addressOpen} onClose={() => setAddressOpen(false)} title="Новый получатель" description="Адрес сохраняется в вашем профиле и используется при оформлении заказа."><AddressForm onSave={async value => { if (await act({ type: "delivery-profile-save", value: value.profile, label: value.label })) { setAddressOpen(false); toast.success("Получатель сохранён."); } }}/></Modal>
  </>;
}

function AddressForm({onSave}:{onSave:(value:{label:string;profile:{recipient:string;phone:string;region:string;city:string;address:string;postalCode:string;comment:string}})=>Promise<void>}) { const [value,setValue]=useState({label:"Новый адрес",recipient:"",phone:"",region:"",city:"",address:"",postalCode:"",comment:""}); return <form className="address-form" onSubmit={event=>{event.preventDefault();void onSave({label:value.label,profile:value})}}><input required placeholder="Название: дом, родители, офис" value={value.label} onChange={e=>setValue({...value,label:e.target.value})}/><input required placeholder="Получатель" value={value.recipient} onChange={e=>setValue({...value,recipient:e.target.value})}/><input required placeholder="Телефон" value={value.phone} onChange={e=>setValue({...value,phone:e.target.value})}/><input required placeholder="Область" value={value.region} onChange={e=>setValue({...value,region:e.target.value})}/><input required placeholder="Город" value={value.city} onChange={e=>setValue({...value,city:e.target.value})}/><input required minLength={5} placeholder="Улица, дом, квартира" value={value.address} onChange={e=>setValue({...value,address:e.target.value})}/><input placeholder="Индекс (необязательно)" value={value.postalCode} onChange={e=>setValue({...value,postalCode:e.target.value})}/><button className="btn primary">Сохранить адрес</button></form> }

export function CustomsView() {
  const { pricing, state } = useMarket();
  return <>
    <PageHeading overline="ДО ОФОРМЛЕНИЯ ЗАКАЗА" title="Таможня: что нужно учитывать." description="Памятка для личных некоммерческих покупок в Узбекистан. Проверена 11 сентября 2026 года." />
    <div className="customs-grid"><section className="surface"><h2>Курьерские отправления</h2><strong className="customs-limit">$200</strong><p>Лимит беспошлинного ввоза на имя физического лица за календарный месяц по нормам, введённым с 1 мая 2025 года. Учитывайте покупки у других продавцов и сервисов.</p></section><section className="surface"><h2>Почтовые отправления</h2><strong className="customs-limit">$100</strong><p>Для международных почтовых отправлений установлена отдельная норма. Нельзя автоматически применять к ним курьерский лимит.</p></section></div>
    <CustomsCalculator fx={pricing.fx} locale={state.communication.language}/><section className="surface customs-text"><details className="ux-disclosure"><summary>Если стоимость выше нормы</summary><p>Для личных некоммерческих товаров превышение установленных норм облагается единым таможенным платежом. Конкретный расчёт зависит от таможенной стоимости, количества, категории и способа ввоза. Возможны отдельные сборы.</p></details><details className="ux-disclosure"><summary>Какая ставка используется</summary><p>Для обычного личного курьерского ввоза: 30% превышения, минимум $3 за кг облагаемой части. С 1 января 2027 года пункт 8 УП-174 предусматривает 20%, минимум $2 за кг. НДС повторно не добавляется. Дата прибытия меняет ставку в калькуляторе.</p><details><summary>Почему не 3% или 5% из публикаций?</summary><p>ПП-136 устанавливает отдельный эксперимент для бондовых складов и зарегистрированных платформ: 3% плюс НДС для специального перечня либо единый платёж 5%. Это не общий режим зарубежных покупок; 5% не означает 5% плюс НДС, а курьерский лимит $200 к этой схеме не переносится.</p></details></details><details className="ux-disclosure"><summary>Что означает ваше согласие</summary><p>При оформлении вы подтверждаете, что ознакомлены с условиями и понимаете возможность дополнительных таможенных платежей. Это не разрешение на автоматическое списание произвольной суммы: доплата согласовывается отдельно.</p></details><details className="ux-disclosure"><summary>Что Atlas пока не знает</summary><p>Мы не получаем ваши покупки через другие сервисы и официальный остаток месячного лимита. Оценка таможни показана отдельно и не включена в сумму Atlas. Страна магазина сама по себе не определяет размер платежа; некоторые категории и коммерческие партии имеют другие требования.</p></details><details className="ux-disclosure"><summary>Официальные источники</summary><div className="source-list">{customsSources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.title}<ArrowUpRight size={16} /></a>)}</div><p className="micro">Перед реальными покупками проверьте действующую редакцию правил и расчёт перевозчика. Эта памятка не заменяет таможенное решение.</p></details></section>
  </>;
}
