"use client";

import { useState } from "react";
import Link from "@/components/site-link";
import { AlertCircle, ArrowRight, ArrowUpRight, Bell, Check, Download, FileCheck2, Heart, LogOut, MapPin, MessageCircle, Package, Plus, ScanLine, ShieldCheck, Upload, UserRound, Wallet } from "lucide-react";
import { useMarket } from "@/lib/market/store";
import { customsReferences as customsSources } from "@/lib/market/customs";
import { CustomsCalculator } from "./customs-estimate";
import { balanceOf, money } from "@/lib/market/domain";
import { toast } from "sonner";
import { Modal, PageHeading } from "./market-ui";

export function AccountView() {
  const { user, state, ready, act } = useMarket();
  const lang=state.communication.language;
  const labels={ru:{title:"Личный кабинет",intro:"Всё важное по покупкам — на одном экране.",settings:"Профиль и настройки",manage:"Управление Atlas",addresses:"Получатели и адреса",documents:"Документы",support:"Поддержка",limits:"Таможенный ориентир",next:"Сейчас важно",orders:"Заказы",active:"В работе",saved:"Избранное",messages:"Новые сообщения",services:"Сервисы Atlas",allOrders:"Все заказы",open:"Открыть",ready:"Всё в порядке",readyHint:"Сейчас от вас ничего не требуется.",shop:"Перейти в каталог"},uz:{title:"Shaxsiy kabinet",intro:"Xaridlar bo‘yicha barcha muhim ma’lumotlar bir joyda.",settings:"Profil va sozlamalar",manage:"Atlas boshqaruvi",addresses:"Qabul qiluvchilar va manzillar",documents:"Hujjatlar",support:"Yordam",limits:"Bojxona bahosi",next:"Hozir muhim",orders:"Buyurtmalar",active:"Jarayonda",saved:"Saqlangan",messages:"Yangi xabarlar",services:"Atlas xizmatlari",allOrders:"Barcha buyurtmalar",open:"Ochish",ready:"Hammasi joyida",readyHint:"Hozir sizdan hech narsa talab qilinmaydi.",shop:"Katalogga o‘tish"},en:{title:"Your account",intro:"Everything important about your purchases in one place.",settings:"Profile & settings",manage:"Manage Atlas",addresses:"Recipients & addresses",documents:"Documents",support:"Support",limits:"Customs estimate",next:"Needs your attention",orders:"Orders",active:"In progress",saved:"Saved",messages:"New messages",services:"Atlas services",allOrders:"All orders",open:"Open",ready:"You’re all set",readyHint:"Nothing needs your attention right now.",shop:"Browse catalog"}}[lang];
  const [legacy, setLegacy] = useState<string | null>(null);
  const [addressOpen, setAddressOpen] = useState(false);
  const [openSection,setOpenSection]=useState<string|null>(null);
  const [ticket, setTicket] = useState({ subject: "", text: "" });
  const activeOrders=state.orders.filter(order=>!order.cancelled&&order.status<5);
  const pendingApproval=activeOrders.find(order=>(order.changeRequests??[]).some(request=>request.status==="pending"));
  const pendingPayment=activeOrders.find(order=>order.payment?.status==="pending");
  const currentOrder=pendingApproval??pendingPayment??activeOrders[0];
  const unread=state.notifications.filter(item=>!item.read).length;
  const monthlyMerchandise=Math.round(state.orders.filter(order=>{const date=new Date(order.createdAt),now=new Date();return date.getMonth()===now.getMonth()&&date.getFullYear()===now.getFullYear()}).reduce((sum,order)=>sum+order.quote.merchandise/(order.quote.fx??12800),0));
  const nextAction=pendingApproval?{title:lang==='ru'?'Нужно ваше решение':lang==='uz'?'Qaroringiz kerak':'Your approval is needed',hint:pendingApproval.product.name,href:`/orders#${pendingApproval.id}`,icon:<AlertCircle/>}:pendingPayment?{title:lang==='ru'?'Завершите оплату':lang==='uz'?'To‘lovni yakunlang':'Complete payment',hint:pendingPayment.product.name,href:`/orders#${pendingPayment.id}`,icon:<Wallet/>}:!state.identityProfile?{title:lang==='ru'?'Подтвердите паспорт':lang==='uz'?'Pasportni tasdiqlang':'Confirm your passport',hint:lang==='ru'?'Это понадобится для декларации.':lang==='uz'?'Bu deklaratsiya uchun kerak.':'Required for the declaration.',href:'/identity',icon:<ScanLine/>}:!state.deliveryProfiles.length?{title:lang==='ru'?'Добавьте получателя':lang==='uz'?'Qabul qiluvchini qo‘shing':'Add a recipient',hint:lang==='ru'?'Адрес будет готов к оформлению.':lang==='uz'?'Manzil buyurtma uchun tayyor bo‘ladi.':'Your address will be ready at checkout.',action:true,icon:<MapPin/>}:currentOrder?{title:lang==='ru'?'Заказ в работе':lang==='uz'?'Buyurtma jarayonda':'Order in progress',hint:currentOrder.product.name,href:`/orders#${currentOrder.id}`,icon:<Package/>}:null;
  function exportProfile() {
    const payload = JSON.stringify({ exportedAt: new Date().toISOString(), profile: user, deliveryProfiles: state.deliveryProfiles, communication: state.communication, orders: state.orders, entries: state.entries, declarations: state.declarations, supportTickets: state.supportTickets }, null, 2);
    const url = URL.createObjectURL(new Blob([payload], { type: "application/json" }));
    const link = document.createElement("a");
    link.href = url; link.download = "atlas-profile-export.json"; link.click();
    URL.revokeObjectURL(url);
    toast.success("Экспорт профиля подготовлен");
  }
  return <>
    <PageHeading overline="ATLAS" title={labels.title} description={labels.intro}>{user?.operator&&<Link className="btn secondary" href="/admin">{labels.manage}<ArrowUpRight size={17}/></Link>}</PageHeading>
    {!user ? <section className="surface"><UserRound size={36} /><h2>Вход и создание аккаунта</h2><p>Войдите через ChatGPT — профиль Atlas создастся автоматически. Ваши находки, адреса и заказы будут доступны в одном кабинете.</p><a className="btn primary" href="/signin-with-chatgpt?return_to=%2Faccount" target="_top">Продолжить с ChatGPT <ArrowUpRight size={18} /></a></section> : <>
      <section className="account-overview">
        <div className="surface account-next-action"><span className="eyebrow">{labels.next}</span>{nextAction?<><div className="next-action-icon">{nextAction.icon}</div><div><h2>{nextAction.title}</h2><p>{nextAction.hint}</p></div>{nextAction.action?<button className="btn primary" onClick={()=>setAddressOpen(true)}>{labels.open}<ArrowRight size={17}/></button>:<Link className="btn primary" href={nextAction.href!}>{labels.open}<ArrowRight size={17}/></Link>}</>:<><div className="next-action-icon complete"><Check/></div><div><h2>{labels.ready}</h2><p>{labels.readyHint}</p></div><Link className="btn primary" href="/">{labels.shop}<ArrowRight size={17}/></Link></>}</div>
        <aside className="surface account-profile-compact"><div className="account-avatar"><UserRound size={26}/></div><div><b>{user.name}</b><span>{user.email}</span></div><details><summary>{labels.settings}</summary><p className="micro">{user.operator ? labels.manage : labels.title} · {new Date(user.createdAt).toLocaleDateString(lang==='ru'?'ru-RU':lang==='uz'?'uz-UZ':'en-US')}</p><div className="profile-actions"><button className="text-button" onClick={exportProfile}><Download size={16}/>{lang==='ru'?'Скачать данные':lang==='uz'?'Ma’lumotlarni yuklash':'Download data'}</button><a className="text-link" href="/signout-with-chatgpt?return_to=%2Faccount" target="_top"><LogOut size={16}/>{lang==='ru'?'Выйти':lang==='uz'?'Chiqish':'Sign out'}</a></div></details></aside>
      </section>
      <section className="account-stats" aria-label={labels.title}>
        <Link href="/orders"><Package/><span>{labels.orders}<b>{state.orders.length}</b></span></Link>
        <Link href="/orders"><ShieldCheck/><span>{labels.active}<b>{activeOrders.length}</b></span></Link>
        <Link href="/favorites"><Heart/><span>{labels.saved}<b>{state.favorites.length}</b></span></Link>
        <Link href="/notifications"><Bell/><span>{labels.messages}<b>{unread}</b></span></Link>
      </section>
      <section className="account-services"><div className="section-heading"><div><span className="eyebrow">ATLAS</span><h2>{labels.services}</h2></div><Link className="text-link" href="/orders">{labels.allOrders}<ArrowUpRight size={16}/></Link></div><div className="account-links account-service-grid">
        <Link href="/orders"><Package/><div>{labels.orders}<small>{activeOrders.length?`${activeOrders.length} ${labels.active.toLocaleLowerCase()}`:labels.ready}</small></div><ArrowUpRight/></Link>
        <Link href="/identity"><ScanLine/><div>{lang==='ru'?'Паспорт':lang==='uz'?'Pasport':'Passport'}<small>{state.identityProfile?(lang==='ru'?'Подтверждён':lang==='uz'?'Tasdiqlangan':'Confirmed'):(lang==='ru'?'Нужно подтвердить':lang==='uz'?'Tasdiqlash kerak':'Confirmation needed')}</small></div><ArrowUpRight/></Link>
        <Link href="/declaration"><FileCheck2/><div>{lang==='ru'?'Декларации':lang==='uz'?'Deklaratsiyalar':'Declarations'}<small>{state.declarations.length}</small></div><ArrowUpRight/></Link>
        <Link href="/balance"><Wallet/><div>{lang==='ru'?'Баланс Atlas':lang==='uz'?'Atlas balansi':'Atlas balance'}<small>{money(balanceOf(state))}</small></div><ArrowUpRight/></Link>
        <button type="button" onClick={()=>setAddressOpen(true)}><MapPin/><div>{labels.addresses}<small>{state.deliveryProfiles.length}</small></div><Plus/></button>
        <Link href="/notifications"><Bell/><div>{lang==='ru'?'Уведомления':lang==='uz'?'Bildirishnomalar':'Notifications'}<small>{unread?`${unread} ${labels.messages.toLocaleLowerCase()}`:labels.ready}</small></div><ArrowUpRight/></Link>
      </div></section>

      <div className="account-grid account-tools">
        <details className="surface ux-disclosure account-detail" open={openSection==='addresses'}><summary onClick={event=>{event.preventDefault();setOpenSection(openSection==='addresses'?null:'addresses')}}><span>{labels.addresses}</span><small>{state.deliveryProfiles.length}</small></summary><div className="account-detail-content"><div className="account-detail-head"><p>{lang==='ru'?'Сохранённые получатели для оформления заказа':lang==='uz'?'Buyurtma uchun saqlangan qabul qiluvchilar':'Saved checkout recipients'}</p><button className="text-button" onClick={() => setAddressOpen(true)}><Plus size={16}/>{lang==='ru'?'Добавить':lang==='uz'?'Qo‘shish':'Add'}</button></div>{state.deliveryProfiles.length ? state.deliveryProfiles.map(profile => <div className="saved-address" key={profile.id}><b>{profile.label}{profile.primary ? " · основной" : ""}</b><span>{profile.recipient} · {profile.phone}</span><small>{profile.region}, {profile.city}, {profile.address}</small><button className="text-button" onClick={() => void act({ type: "delivery-profile-remove", id: profile.id })}>Удалить</button></div>) : <p className="account-detail-empty">Получателей пока нет.</p>}</div></details>
        <details className="surface ux-disclosure account-detail" open={openSection==='limits'}><summary onClick={event=>{event.preventDefault();setOpenSection(openSection==='limits'?null:'limits')}}><span>{labels.limits}</span><small>${monthlyMerchandise}</small></summary><div className="account-detail-content"><strong className="customs-limit">${monthlyMerchandise}</strong><p>Покупки через Atlas в этом месяце. Покупки в других сервисах здесь не учитываются.</p><Link className="text-link" href="/customs">Условия и расчёт <ArrowUpRight size={16}/></Link></div></details>
      </div>
      <div className="account-grid account-tools">
        <details className="surface ux-disclosure account-detail" open={openSection==='documents'}><summary onClick={event=>{event.preventDefault();setOpenSection(openSection==='documents'?null:'documents')}}><span>{labels.documents}</span><small>{state.declarations.length}</small></summary><div className="account-detail-content"><p>Паспорт, декларации и экспорт данных. Счета и складские материалы находятся внутри заказов.</p><div className="profile-actions"><Link className="btn secondary" href="/identity"><ScanLine size={16}/> Паспорт</Link><Link className="btn secondary" href="/declaration"><FileCheck2 size={16}/> Декларации</Link><button className="btn secondary" onClick={exportProfile}><Download size={16}/> Экспорт</button></div></div></details>
        <details className="surface ux-disclosure account-detail" id="support" open={openSection==='support'}><summary onClick={event=>{event.preventDefault();setOpenSection(openSection==='support'?null:'support')}}><span>{labels.support}</span><small>{state.supportTickets.some(t=>t.status==="answered")?'Есть ответ':state.supportTickets.length}</small></summary><div className="account-detail-content">{state.supportTickets.length ? <div className="ticket-list">{state.supportTickets.slice(0,3).map(item => <div key={item.id}><b>{item.subject}</b><small>{item.status === "open" ? "Ждём ответа" : item.status === "answered" ? "Есть ответ" : "Закрыто"} · {item.replies.length} сообщений</small><details><summary>Открыть историю</summary>{item.replies.map(reply => <p className="ticket-reply" key={reply.id}><b>{reply.author === "support" ? "Поддержка" : "Вы"}</b><br/>{reply.text}</p>)}{item.status !== "closed" && <form className="support-reply-form" onSubmit={async event => { event.preventDefault(); const form = event.currentTarget; const input = form.elements.namedItem("reply") as HTMLInputElement; if (await act({ type: "support-reply", id: item.id, text: input.value })) input.value = ""; }}><input name="reply" required minLength={3} placeholder="Ответить по обращению"/><button className="btn secondary">Ответить</button></form>}</details></div>)}</div> : <p className="account-detail-empty">Нет открытых обращений.</p>}<form className="support-form" onSubmit={async event => { event.preventDefault(); if (await act({ type: "support-create", subject: ticket.subject, text: ticket.text })) { setTicket({ subject: "", text: "" }); toast.success("Обращение отправлено в тестовую очередь."); } }}><input required minLength={3} placeholder="Тема обращения" value={ticket.subject} onChange={event => setTicket({ ...ticket, subject: event.target.value })}/><textarea required minLength={3} placeholder="Опишите вопрос" value={ticket.text} onChange={event => setTicket({ ...ticket, text: event.target.value })}/><button className="btn secondary" disabled={!ready}><MessageCircle size={16}/> Отправить</button></form></div></details>
      </div>
      <details className="surface ux-disclosure legacy-import"><summary>Перенос прежних данных</summary><h2>Заказы из предыдущей версии</h2><p>Если в этом браузере уже есть данные Atlas, можно один раз перенести их в пустой профиль.</p><button className="btn secondary" disabled={!ready || !!(state.orders.length || state.cart.length || state.entries.length || state.favorites.length)} onClick={() => { try { const raw = localStorage.getItem("atlas-market-demo-v1"); if (!raw) { toast.message("В этом браузере старых данных нет."); return; } setLegacy(raw); } catch { toast.error("Нет доступа к данным браузера."); } }}><Upload size={16} /> Найти прежние заказы</button></details>
    </>}
    <Modal open={!!legacy} onClose={() => setLegacy(null)} title="Перенести данные?" description="Будут перенесены заказы, корзина, избранное и баланс Atlas из этого браузера. Подтвердите, что это ваши данные."><button className="btn primary" onClick={async () => { if (legacy && await act({ type: "import-legacy", data: legacy })) { setLegacy(null); toast.success("Данные перенесены в аккаунт."); } }}>Это мои данные — перенести <Check size={18} /></button></Modal>
    <Modal open={addressOpen} onClose={() => setAddressOpen(false)} title="Новый получатель" description="Адрес сохраняется в вашем профиле и используется при оформлении заказа."><AddressForm onSave={async value => { if (await act({ type: "delivery-profile-save", value: value.profile, label: value.label })) { setAddressOpen(false); toast.success("Получатель сохранён."); } }}/></Modal>
  </>;
}

function AddressForm({onSave}:{onSave:(value:{label:string;profile:{recipient:string;phone:string;region:string;city:string;address:string;postalCode:string;comment:string}})=>Promise<void>}) { const [value,setValue]=useState({label:"Новый адрес",recipient:"",phone:"",region:"",city:"",address:"",postalCode:"",comment:""}); return <form className="address-form" onSubmit={event=>{event.preventDefault();void onSave({label:value.label,profile:value})}}><input required placeholder="Название: дом, родители, офис" value={value.label} onChange={e=>setValue({...value,label:e.target.value})}/><input required placeholder="Получатель" value={value.recipient} onChange={e=>setValue({...value,recipient:e.target.value})}/><input required placeholder="Телефон" value={value.phone} onChange={e=>setValue({...value,phone:e.target.value})}/><input required placeholder="Область" value={value.region} onChange={e=>setValue({...value,region:e.target.value})}/><input required placeholder="Город" value={value.city} onChange={e=>setValue({...value,city:e.target.value})}/><input required minLength={5} placeholder="Улица, дом, квартира" value={value.address} onChange={e=>setValue({...value,address:e.target.value})}/><input placeholder="Индекс (необязательно)" value={value.postalCode} onChange={e=>setValue({...value,postalCode:e.target.value})}/><button className="btn primary">Сохранить адрес</button></form> }

export function CustomsView() {
  const { pricing, state } = useMarket();
  return <>
    <PageHeading overline="ДО ОФОРМЛЕНИЯ ЗАКАЗА" title="Таможня: что нужно учитывать." description="Памятка для личных некоммерческих покупок в Узбекистан. Проверена 11 сентября 2026 года." />
    <div className="customs-grid"><section className="surface"><h2>Курьерские отправления</h2><strong className="customs-limit">$200</strong><p>Лимит беспошлинного ввоза на имя физического лица за календарный месяц по нормам, введённым с 1 мая 2025 года. Учитывайте покупки у других продавцов и сервисов.</p></section><section className="surface"><h2>Почтовые отправления</h2><strong className="customs-limit">$100</strong><p>Для международных почтовых отправлений установлена отдельная норма. Нельзя автоматически применять к ним курьерский лимит.</p></section></div>
    <CustomsCalculator fx={pricing.fx} locale={state.communication.language}/><section className="surface customs-text"><details className="ux-disclosure"><summary>Если стоимость выше нормы</summary><p>Для личных некоммерческих товаров превышение установленных норм облагается единым таможенным платежом. Конкретный расчёт зависит от таможенной стоимости, количества, категории и способа ввоза. Возможны отдельные сборы.</p></details><details className="ux-disclosure"><summary>Какая ставка используется</summary><p>Для обычного личного курьерского ввоза: 30% превышения, минимум $3 за кг облагаемой части. С 1 января 2027 года пункт 8 УП-174 предусматривает 20%, минимум $2 за кг. НДС повторно не добавляется. Дата прибытия меняет ставку в калькуляторе.</p><details><summary>Почему не 3% или 5% из публикаций?</summary><p>ПП-136 устанавливает отдельный эксперимент для бондовых складов и зарегистрированных платформ: 3% плюс НДС для специального перечня либо единый платёж 5%. Это не общий режим зарубежных покупок; 5% не означает 5% плюс НДС, а курьерский лимит $200 к этой схеме не переносится.</p></details></details><details className="ux-disclosure"><summary>Что означает ваше согласие</summary><p>При оформлении вы подтверждаете, что ознакомлены с условиями и понимаете возможность дополнительных таможенных платежей. Это не разрешение на автоматическое списание произвольной суммы: доплата согласовывается отдельно.</p></details><details className="ux-disclosure"><summary>Что Atlas пока не знает</summary><p>Мы не получаем ваши покупки через другие сервисы и официальный остаток месячного лимита. Оценка таможни показана отдельно и не включена в сумму Atlas. Страна магазина сама по себе не определяет размер платежа; некоторые категории и коммерческие партии имеют другие требования.</p></details><details className="ux-disclosure"><summary>Официальные источники</summary><div className="source-list">{customsSources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.title}<ArrowUpRight size={16} /></a>)}</div><p className="micro">Перед реальными покупками проверьте действующую редакцию правил и расчёт перевозчика. Эта памятка не заменяет таможенное решение.</p></details></section>
  </>;
}
