'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Package,Wallet,UserRound,ShieldCheck,LogOut,Upload,Check} from 'lucide-react';
import {useMarket} from '@/lib/market/store';
import {customsSources} from '@/lib/market/world';
import {money,balanceOf} from '@/lib/market/domain';
import {toast} from 'sonner';
import {Modal,PageHeading} from './market-ui';
export function AccountView(){const {user,state,ready,act}=useMarket();const [legacy,setLegacy]=useState<string|null>(null);return <><PageHeading overline="ЛИЧНОЕ ПРОСТРАНСТВО" title="Ваш профиль Atlas." description="Заказы, фото товаров и баланс сохраняются в аккаунте и доступны после входа на другом устройстве."/>{!user?<section className="surface"><UserRound size={36}/><h2>Вход и создание аккаунта</h2><p>При первом входе через ChatGPT профиль Atlas создаётся автоматически. Регистрация по телефону и email пока не подключена.</p><a className="btn primary" href="/signin-with-chatgpt?return_to=%2Faccount" target="_top">Продолжить с ChatGPT<ArrowUpRight size={18}/></a></section>:<><div className="account-grid"><section className="surface"><div className="account-avatar"><UserRound size={30}/></div><h2>{user.name}</h2><p>{user.email}</p><p className="micro">Роль: {user.operator?'оператор и покупатель':'покупатель'} · Профиль создан {new Date(user.createdAt).toLocaleDateString('ru-RU')}</p><div className="notice"><ShieldCheck size={20}/><span>Заказы привязаны к вашему входу. У других пользователей отдельные профили.</span></div><a className="text-link" href="/signout-with-chatgpt?return_to=%2Faccount" target="_top"><LogOut size={16}/>Выйти</a></section><section className="surface account-links"><Link href="/orders"><Package/><div>Мои заказы<small>{state.orders.length} заказов</small></div><ArrowUpRight/></Link><Link href="/balance"><Wallet/><div>Демобаланс<small>{money(balanceOf(state))}</small></div><ArrowUpRight/></Link><Link href="/customs"><ShieldCheck/><div>Таможенные условия<small>Лимиты и согласие при оформлении</small></div><ArrowUpRight/></Link>{user.operator&&<Link href="/operations"><Package/><div>Кабинет оператора</div><ArrowUpRight/></Link>}</section></div><section className="surface legacy-import"><h2>Заказы из предыдущей версии</h2><p>Если вы тестировали Atlas в этом браузере, можно один раз перенести старые данные в пустой профиль.</p><button className="btn secondary" disabled={!ready||!!(state.orders.length||state.cart.length||state.entries.length||state.favorites.length)} onClick={()=>{try{const raw=localStorage.getItem('atlas-market-demo-v1');if(!raw){toast.message('В этом браузере старых данных нет.');return}setLegacy(raw)}catch{toast.error('Нет доступа к данным браузера.')}}}><Upload size={16}/>Найти прежние заказы</button></section></>}
 <Modal open={!!legacy} onClose={()=>setLegacy(null)} title="Перенести тестовые данные?" description="Будут перенесены заказы, корзина, избранное и демобаланс из этого браузера. Подтвердите, что это ваши данные."><button className="btn primary" onClick={async()=>{if(legacy&&await act({type:'import-legacy',data:legacy})){setLegacy(null);toast.success('Данные перенесены в аккаунт.')}}}>Это мои данные — перенести<Check size={18}/></button></Modal></>}
export function CustomsView(){return <><PageHeading overline="ДО ОФОРМЛЕНИЯ ЗАКАЗА" title="Таможня: что нужно учитывать." description="Памятка для личных некоммерческих покупок в Узбекистан. Проверена 9 сентября 2026 года."/><div className="customs-grid"><section className="surface"><h2>Курьерские отправления</h2><strong className="customs-limit">$200</strong><p>Лимит беспошлинного ввоза на имя физического лица за календарный месяц по нормам, введённым с 1 мая 2025 года. Учитывайте покупки у других продавцов и сервисов.</p></section><section className="surface"><h2>Почтовые отправления</h2><strong className="customs-limit">$100</strong><p>Для международных почтовых отправлений установлена отдельная норма. Нельзя автоматически применять к ним курьерский лимит.</p></section></div><section className="surface customs-text"><h2>Если стоимость выше нормы</h2><p>Для личных некоммерческих товаров превышение установленных норм облагается единым таможенным платежом. Конкретный расчёт зависит от таможенной стоимости, количества, категории и способа ввоза. Возможны отдельные сборы.</p><h2>Что означает ваше согласие</h2><p>При оформлении вы подтверждаете, что ознакомлены с условиями и понимаете возможность дополнительных таможенных платежей. Это не разрешение на автоматическое списание произвольной суммы: доплата согласовывается отдельно.</p><h2>Что Atlas пока не знает</h2><p>Мы не получаем ваши покупки через другие сервисы и официальный остаток месячного лимита. Показанный итог пока не включает расчёт таможни. Страна магазина сама по себе не определяет размер платежа; некоторые категории и коммерческие партии имеют другие требования.</p><h2>Официальные источники</h2><div className="source-list">{customsSources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<ArrowUpRight size={16}/></a>)}</div><p className="micro">Перед реальными покупками проверьте действующую редакцию правил и расчёт перевозчика. Эта памятка не заменяет таможенное решение.</p></section></>}
