"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "@/components/site-link";
import {BarChart3,ClipboardList,Database,History,Package,Settings2,ShieldCheck,UsersRound,WalletCards} from "lucide-react";
import {toast} from "sonner";
import {useMarket} from "@/lib/market/store";
import type {Policy} from "@/lib/market/policy";
import type {State} from "@/lib/market/domain";
import type {AuditEvent,StaffMember,StaffRole,StaffStatus} from "@/lib/market/server";
import {Empty,PageHeading} from "./market-ui";
import {CatalogAdmin} from "./catalog-admin";

type AdminData={accounts:Array<{id:string;name:string;state:State;revision:number;updatedAt:number}>;policy:Policy;staff:StaffMember[];audit:AuditEvent[];health:{customers:number;orders:number;feeLines:number;events:number;checkedAt:number};customerStatuses:Record<string,"active"|"review"|"blocked">;errors:Array<{id:string;area:string;message:string;createdAt:number;resolvedAt?:number}>};
type Tab="overview"|"catalog"|"customers"|"support"|"finance"|"staff"|"rules"|"system"|"audit";
const roleLabels:Record<StaffRole,string>={support:"Поддержка",procurement:"Закупки",warehouse:"Склад",finance:"Финансы",admin:"Администратор"};
const statusLabels:Record<StaffStatus,string>={invited:"Приглашён",active:"Активен",disabled:"Отключён"};

export function AdminView(){
 const {user,state}=useMarket(),[data,setData]=useState<AdminData|null>(null),[tab,setTab]=useState<Tab>("overview"),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState("");
 const c={ru:{tabs:['Обзор','Каталог','Клиенты','Поддержка','Финансы','Команда','Правила','Система','Журнал'],system:'Система и резервная копия',sync:'Синхронизировать всё',backup:'Скачать защищённый экспорт',errors:'Ошибки сервера',clear:'Ошибок не зарегистрировано'},uz:{tabs:['Umumiy','Katalog','Mijozlar','Yordam','Moliya','Jamoa','Qoidalar','Tizim','Jurnal'],system:'Tizim va zaxira nusxasi',sync:'Barchasini sinxronlash',backup:'Himoyalangan eksportni yuklash',errors:'Server xatolari',clear:'Xatolar qayd etilmagan'},en:{tabs:['Overview','Catalog','Customers','Support','Finance','Team','Rules','System','Audit'],system:'System and backup',sync:'Synchronize all',backup:'Download protected export',errors:'Server errors',clear:'No errors recorded'}}[state.communication.language];
 const [staffForm,setStaffForm]=useState<{email:string;displayName:string;role:StaffRole;status:StaffStatus}>({email:"",displayName:"",role:"support",status:"invited"});
 const load=useCallback(async()=>{if(!user?.operator)return;setLoadError("");try{const response=await fetch('/api/operations',{cache:'no-store'});const next=await response.json() as AdminData&{error?:string};if(!response.ok||!next.accounts||!next.policy||!next.staff||!next.audit)throw Error(next.error??'Не удалось загрузить админку.');setData(next)}catch(error){setLoadError((error as Error).message)}},[user?.operator]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 const metrics=useMemo(()=>{const accounts=data?.accounts??[],orders=accounts.flatMap(account=>account.state.orders),tickets=accounts.flatMap(account=>account.state.supportTickets);return{customers:accounts.length,orders:orders.length,activeOrders:orders.filter(order=>!order.cancelled&&order.status<5).length,attention:orders.filter(order=>!order.cancelled&&(order.payment?.status==='pending'||Boolean(order.settlement?.extra&&!order.extraApproved)||Boolean(order.storeShippingSettlement?.extra&&!order.storeShippingExtraApproved)||(order.changeRequests??[]).some(request=>request.status==='pending'))).length,openTickets:tickets.filter(ticket=>ticket.status==='open').length}},[data]);
 async function saveRules(){if(!data)return;setBusy(true);try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'policy',value:{maxCartLines:data.policy.maxCartLines,maxCartWeightKg:data.policy.maxCartWeightKg,maxMerchandiseUsd:data.policy.maxMerchandiseUsd,blockedCategories:data.policy.blockedCategories,restrictedTerms:data.policy.restrictedTerms}})});const next=await response.json() as {policy?:Policy;error?:string};if(!response.ok||!next.policy)throw Error(next.error??'Не удалось сохранить правила.');setData({...data,policy:next.policy});await load();toast.success('Ограничения обновлены и записаны в журнал.')}catch(error){toast.error((error as Error).message)}finally{setBusy(false)}}
 async function saveStaff(){setBusy(true);try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'staff',value:staffForm})});const next=await response.json() as {staff?:StaffMember[];audit?:AuditEvent[];error?:string};if(!response.ok||!next.staff||!next.audit)throw Error(next.error??'Не удалось сохранить сотрудника.');if(data)setData({...data,staff:next.staff,audit:next.audit});setStaffForm({email:"",displayName:"",role:"support",status:"invited"});toast.success('Карточка сотрудника сохранена.')}catch(error){toast.error((error as Error).message)}finally{setBusy(false)}}
 async function customerStatus(accountId:string,status:"active"|"review"|"blocked"){setBusy(true);try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'customer-status',accountId,status})});const next=await response.json() as {audit?:AuditEvent[];error?:string};if(!response.ok)throw Error(next.error??'Не удалось изменить статус.');if(data)setData({...data,customerStatuses:{...data.customerStatuses,[accountId]:status},audit:next.audit??data.audit});toast.success('Доступ клиента обновлён.')}catch(error){toast.error((error as Error).message)}finally{setBusy(false)}}
 async function rebuild(){setBusy(true);try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'projection-rebuild'})});const next=await response.json() as {health?:AdminData['health'];audit?:AuditEvent[];error?:string};if(!response.ok||!next.health)throw Error(next.error??'Не удалось синхронизировать базу.');if(data)setData({...data,health:next.health,audit:next.audit??data.audit});toast.success('Операционная база синхронизирована.')}catch(error){toast.error((error as Error).message)}finally{setBusy(false)}}
 async function reply(account:{id:string;revision:number},ticketId:string){const text=window.prompt('Ответ клиенту');if(!text?.trim())return;setBusy(true);try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'action',accountId:account.id,revision:account.revision,action:{type:'support-reply',id:ticketId,text:text.trim()}})});const next=await response.json() as {error?:string};if(!response.ok)throw Error(next.error??'Не удалось отправить ответ.');await load();toast.success('Ответ добавлен в историю обращения.')}catch(error){toast.error((error as Error).message)}finally{setBusy(false)}}
 if(!user?.operator)return <Empty title="Доступ только администратору" description="Управление Atlas доступно только назначенному администратору." href="/account" label="Личный кабинет"/>;
 if(!data)return <section className="surface" role="status"><p>{loadError||"Загружаем операционный центр…"}</p>{loadError&&<button className="btn secondary" onClick={()=>void load()}>Повторить</button>}</section>;
 return <>
  <PageHeading overline="ОПЕРАЦИОННЫЙ ЦЕНТР" title="Управление Atlas." description="Заказы, команда, тарифы, ограничения и контроль действий в одном защищённом разделе."><span className="status-badge">Только администратор</span></PageHeading>
  <nav className="admin-tabs" aria-label="Разделы админки">{(['overview','catalog','customers','support','finance','staff','rules','system','audit'] as const).map((id,index)=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{c.tabs[index]}</button>)}</nav>
  {tab==='overview'&&<div className="admin-dashboard">
   <section className="admin-metrics">
    <article><UsersRound/><span>Клиенты</span><strong>{metrics.customers}</strong><small>профилей в базе</small></article>
    <article><Package/><span>Заказы в работе</span><strong>{metrics.activeOrders}</strong><small>{metrics.orders} всего</small></article>
    <article><ClipboardList/><span>Нужна реакция</span><strong>{metrics.attention+metrics.openTickets}</strong><small>заказы и обращения</small></article>
    <article><History/><span>Действия</span><strong>{data.audit.length}</strong><small>последние записи</small></article>
   </section>
   <section className="admin-shortcuts surface"><div><h2>Рабочие разделы</h2><p>Переходите сразу к задаче, которую нужно обработать.</p></div><div className="admin-shortcut-grid"><Link href="/operations"><Package/><b>Очередь заказов</b><span>{metrics.attention} требуют внимания</span></Link><Link href="/analytics"><BarChart3/><b>Аналитика</b><span>заказы и комиссии</span></Link><button onClick={()=>setTab('staff')}><UsersRound/><b>Команда</b><span>{data.staff.length} сотрудников</span></button><button onClick={()=>setTab('rules')}><Settings2/><b>Ограничения</b><span>лимиты и запреты</span></button></div></section>
   <div className="notice"><ShieldCheck/><span>До подключения отдельной авторизации доступ к операциям имеет только основной email администратора. Записи команды пока не предоставляют право входа.</span></div>
  </div>}
  {tab==='catalog'&&<CatalogAdmin/>}
  {tab==='staff'&&<section className="surface admin-section"><div className="admin-section-head"><div><h2>Команда и роли</h2><p>Подготовьте сотрудников заранее. Активация их доступа произойдёт после подключения отдельной авторизации.</p></div></div><div className="staff-form"><div className="field"><label htmlFor="staff-name">Имя сотрудника</label><input id="staff-name" value={staffForm.displayName} onChange={event=>setStaffForm({...staffForm,displayName:event.target.value})}/></div><div className="field"><label htmlFor="staff-email">Email</label><input id="staff-email" type="email" value={staffForm.email} onChange={event=>setStaffForm({...staffForm,email:event.target.value})}/></div><div className="field"><label htmlFor="staff-role">Роль</label><select id="staff-role" value={staffForm.role} onChange={event=>setStaffForm({...staffForm,role:event.target.value as StaffRole})}>{Object.entries(roleLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div className="field"><label htmlFor="staff-status">Статус</label><select id="staff-status" value={staffForm.status} onChange={event=>setStaffForm({...staffForm,status:event.target.value as StaffStatus})}><option value="invited">Приглашён</option><option value="active">Активен</option><option value="disabled">Отключён</option></select></div><button className="btn primary" disabled={busy||!staffForm.email||staffForm.displayName.trim().length<2} onClick={()=>void saveStaff()}>{busy?'Сохраняем…':'Добавить сотрудника'}</button></div><div className="admin-table" role="table" aria-label="Сотрудники"><div className="admin-table-row head" role="row"><span>Сотрудник</span><span>Роль</span><span>Статус</span><span>Обновлён</span></div>{data.staff.map(member=><button className="admin-table-row" role="row" key={member.id} onClick={()=>setStaffForm({email:member.email,displayName:member.displayName,role:member.role,status:member.status})}><span><b>{member.displayName}</b><small>{member.email}</small></span><span>{roleLabels[member.role]}</span><span><i className={`staff-status ${member.status}`}>{statusLabels[member.status]}</i></span><time>{new Date(member.updatedAt).toLocaleDateString('ru-RU')}</time></button>)}</div></section>}
  {tab==='rules'&&<section className="surface admin-policy admin-section"><div className="admin-heading"><Settings2/><div><h2>Лимиты и ручная проверка</h2><p>Правила применяются на сервере ко всем новым действиям покупателей.</p></div></div><div className="pricing-grid"><div className="field"><label htmlFor="max-lines">Позиций в партии</label><input id="max-lines" type="number" min="1" max="20" value={data.policy.maxCartLines} onChange={event=>setData({...data,policy:{...data.policy,maxCartLines:Number(event.target.value)}})}/></div><div className="field"><label htmlFor="max-weight">Расчётный вес, кг</label><input id="max-weight" type="number" min="1" max="200" value={data.policy.maxCartWeightKg} onChange={event=>setData({...data,policy:{...data.policy,maxCartWeightKg:Number(event.target.value)}})}/></div><div className="field"><label htmlFor="max-usd">Стоимость товаров, USD</label><input id="max-usd" type="number" min="100" max="50000" value={data.policy.maxMerchandiseUsd} onChange={event=>setData({...data,policy:{...data.policy,maxMerchandiseUsd:Number(event.target.value)}})}/></div></div><div className="two-fields"><div className="field"><label htmlFor="blocked-categories">Запрещённые категории</label><input id="blocked-categories" value={data.policy.blockedCategories.join(', ')} onChange={event=>setData({...data,policy:{...data.policy,blockedCategories:event.target.value.split(',').map(value=>value.trim()).filter(Boolean)}})}/></div><div className="field"><label htmlFor="restricted-terms">Слова для ручной проверки</label><input id="restricted-terms" value={data.policy.restrictedTerms.join(', ')} onChange={event=>setData({...data,policy:{...data.policy,restrictedTerms:event.target.value.split(',').map(value=>value.trim()).filter(Boolean)}})}/></div></div><button className="btn primary" disabled={busy} onClick={()=>void saveRules()}>{busy?'Сохраняем…':'Сохранить правила'}</button></section>}
  {tab==='audit'&&<section className="surface admin-section"><div className="admin-section-head"><div><h2>Журнал действий</h2><p>Последние изменения в заказах, тарифах, ограничениях и команде.</p></div><span>{data.audit.length} записей</span></div>{data.audit.length?<div className="audit-list">{data.audit.map(event=><article key={event.id}><div><b>{event.action}</b><span>{event.entityType}{event.entityId?` · ${event.entityId}`:''}</span></div><div><span>{event.actorEmail}</span><time>{new Date(event.createdAt).toLocaleString('ru-RU')}</time></div></article>)}</div>:<div className="admin-empty"><History/><h3>Журнал пока пуст</h3><p>Первое изменение настройки или заказа появится здесь автоматически.</p></div>}</section>}
  {tab==='customers'&&<section className="surface admin-section"><div className="admin-section-head"><div><h2>Клиенты и доступ</h2><p>Активный профиль можно поставить на проверку или полностью заблокировать.</p></div><span>{data.accounts.length} клиентов</span></div><div className="admin-table" role="table" aria-label="Клиенты"><div className="admin-table-row head" role="row"><span>Клиент</span><span>Заказы</span><span>Обращения</span><span>Доступ</span></div>{data.accounts.map(account=><div className="admin-table-row" role="row" key={account.id}><span><b>{account.name}</b><small>{account.id.replace(/^email:/,'')}</small></span><span>{account.state.orders.length}</span><span>{account.state.supportTickets.filter(ticket=>ticket.status==='open').length}</span><select aria-label={`Доступ ${account.name}`} disabled={busy} value={data.customerStatuses[account.id]??'active'} onChange={event=>void customerStatus(account.id,event.target.value as 'active'|'review'|'blocked')}><option value="active">Активен</option><option value="review">На проверке</option><option value="blocked">Заблокирован</option></select></div>)}</div></section>}
  {tab==='support'&&<section className="surface admin-section"><div className="admin-section-head"><div><h2>Очередь поддержки</h2><p>Все обращения и сообщения привязаны к профилю клиента.</p></div><span>{metrics.openTickets} открыто</span></div><div className="audit-list">{data.accounts.flatMap(account=>account.state.supportTickets.map(ticket=>({account,ticket}))).sort((a,b)=>b.ticket.updatedAt-a.ticket.updatedAt).map(({account,ticket})=><article key={ticket.id}><div><b>{ticket.subject}</b><span>{account.name} · {ticket.replies.length} сообщений · {ticket.status==='open'?'ждёт ответа':'отвечено'}</span></div><button className="btn secondary" disabled={busy} onClick={()=>void reply(account,ticket.id)}>Ответить</button></article>)}</div></section>}
  {tab==='finance'&&<section className="surface admin-section"><div className="admin-section-head"><div><h2>Финансовый контроль</h2><p>Каждая комиссия хранится отдельной строкой; международная доставка и её маржа не смешиваются.</p></div></div><section className="admin-metrics"><article><WalletCards/><span>Оборот заказов</span><strong>{new Intl.NumberFormat('ru-RU').format(data.accounts.flatMap(a=>a.state.orders).reduce((sum,o)=>sum+o.quote.total,0))} сум</strong><small>по сохранённым расчётам</small></article><article><BarChart3/><span>Доход Atlas</span><strong>{new Intl.NumberFormat('ru-RU').format(data.accounts.flatMap(a=>a.state.orders).reduce((sum,o)=>sum+o.quote.service+(o.quote.buyout??0)+(o.quote.conversion??0)+(o.quote.deliveryMargin??0)+(o.quote.optionalServices??0),0))} сум</strong><small>сервис, выкуп, конвертация и услуги</small></article><article><ClipboardList/><span>Начисления</span><strong>{data.health.feeLines}</strong><small>отдельных строк</small></article></section></section>}
  {tab==='system'&&<section className="surface admin-section"><div className="admin-section-head"><div><h2>{c.system}</h2><p>Заказы сохраняют совместимость и одновременно раскладываются по операционным таблицам.</p></div><div className="admin-system-actions"><button className="btn primary" disabled={busy} onClick={()=>void rebuild()}>{busy?'…':c.sync}</button><a className="btn secondary" href="/api/backup">{c.backup}</a></div></div><section className="admin-metrics"><article><Database/><span>Клиенты</span><strong>{data.health.customers}</strong><small>в операционной базе</small></article><article><Package/><span>Заказы</span><strong>{data.health.orders}</strong><small>нормализованных записей</small></article><article><WalletCards/><span>Начисления</span><strong>{data.health.feeLines}</strong><small>отдельных строк</small></article><article><History/><span>События</span><strong>{data.health.events}</strong><small>история статусов</small></article></section><div className="monitor-panel"><h3>{c.errors}</h3>{data.errors.length?data.errors.slice(0,10).map(error=><p key={error.id}><b>{error.area}</b><span>{error.message}</span><time>{new Date(error.createdAt).toLocaleString()}</time></p>):<p className="micro">{c.clear}</p>}</div><div className="notice"><ShieldCheck/><span>Экспорт доступен только администратору, содержит контрольную сумму и фиксируется в журнале. Паспортные файлы не включаются.</span></div></section>}
 </>;
}
