"use client";
import {useState} from "react";
import {ListPlus,Loader2} from "lucide-react";
import {toast} from "sonner";
import {useMarket} from "@/lib/market/store";
import {safeImage,inferProductCategory,type Extracted} from "@/lib/importer/extract";
import {currencies,toUsd,paddedWeight} from "@/lib/market/world";
import {type Product} from "@/lib/market/domain";
import {Empty,PageHeading} from "./market-ui";

const weights:Record<string,number>={"Обувь":1.3,"Одежда":0.6,"Электроника":1,"Аксессуары":0.7,"Красота и уход":0.6,"Дом и быт":2,"Спорт":1,"Другое":1.5};
export function BatchImportView(){const {ready,pricing,act}=useMarket();const [urls,setUrls]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<string[]>([]);
 async function run(){if(busy||!ready)return;const links=[...new Set(urls.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];if(!links.length){toast.error('Вставьте хотя бы одну ссылку.');return}if(links.length>10){toast.error('За один раз можно проверить до 10 ссылок.');return}setBusy(true);setResult([]);const notes:string[]=[];for(const url of links){try{const response=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await response.json() as Extracted&{error?:string;fetchedAt?:number;expiresAt?:number};if(!response.ok)throw Error(data.error??'Не удалось получить данные.');const category=data.category??inferProductCategory(data.title??'',data.brand??'');const currency=currencies.includes(data.currency??'')?data.currency!:'USD';if(!data.title||data.price===undefined||!data.country)throw Error('Магазин не отдал название, цену или страну — добавьте этот товар через обычный импорт.');const variant=data.variants?.find(v=>v.available)?.label??'Стандартный';const sourceShipping=data.shipping??10;const shippingCurrency=currencies.includes(data.shippingCurrency??'')?data.shippingCurrency!:currency;const product:Product={id:data.sourceUrl+'#'+variant,name:data.title,brand:data.brand??new URL(data.sourceUrl).hostname,category,usd:toUsd(data.price,currency,pricing.rates),weight:paddedWeight(data.boxedWeight??weights[category]??1.5),image:data.image?safeImage(data.image,data.sourceUrl)??'':'',sourceUrl:data.sourceUrl,variants:[variant],country:data.country,sourceCurrency:currency,sourcePrice:data.price,sourceShipping,sourceShippingCurrency:shippingCurrency,sourceShippingUsd:toUsd(sourceShipping,shippingCurrency,pricing.rates),sourceShippingEstimated:data.shipping===undefined,shippingKnown:true,boxedWeight:data.boxedWeight??weights[category]??1.5,weightOrigin:data.boxedWeight?'со страницы магазина':'оценка по категории',importedAt:data.fetchedAt,sourceExpiresAt:data.expiresAt,declarationDescription:data.declarationDescription};const ok=await act({type:'cart-add',product,variant});notes.push(ok?`Добавлено: ${product.name}`:`Не добавлено: ${product.name}`)}catch(error){notes.push(`Проблема: ${url} — ${(error as Error).message}`)}}setResult(notes);setBusy(false);if(notes.some(note=>note.startsWith('Добавлено')))toast.success('Товары добавлены в корзину. Проверьте каждый перед оформлением.');}
 if(!ready)return <Empty title="Войдите, чтобы импортировать список" description="Партия и результаты проверки сохраняются в вашем профиле." href="/account" label="Открыть вход"/>;
 return <><PageHeading overline="ПАРТИЯ ИЗ НЕСКОЛЬКИХ ТОВАРОВ" title="Импортируйте список ссылок." description="До 10 ссылок, каждая с новой строки. Atlas добавит только товары с достаточными данными; перед оплатой всё можно проверить в корзине."/><section className="surface batch-import"><label className="field" htmlFor="batch-urls">Ссылки на товары</label><textarea id="batch-urls" rows={10} value={urls} onChange={e=>setUrls(e.target.value)} placeholder={'https://www.zara.com/...\nhttps://www.amazon.com/...'} /><button className="btn primary" disabled={busy||!urls.trim()} onClick={()=>void run()}>{busy?<Loader2 className="spin"/>:<ListPlus/>}{busy?'Импортируем…':'Импортировать в корзину'}</button>{result.length>0&&<ul className="batch-result">{result.map((line,index)=><li key={index}>{line}</li>)}</ul>}</section></>}
