"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Check,ChevronDown,ExternalLink,EyeOff,FolderPlus,ImageIcon,Link2,Loader2,MessageSquareWarning,RefreshCw,Send} from 'lucide-react';
import {toast} from 'sonner';
import {Modal} from './market-ui';
import {canonicalCatalogUrl,catalogCategories,catalogIssues,catalogRefreshInterval,cleanGeneratedCatalogDescription,dueCatalogEntries,type CatalogCollection,type CatalogDocument,type CatalogDraft} from '@/lib/market/catalog-editor';
import {catalogImportBatchSize,parseCatalogImportQueue,removeImportedCatalogLinks} from '@/lib/market/catalog-import-queue';
import {dedupeSafeImages,safeImage} from '@/lib/importer/extract';

type Result={document?:CatalogDocument;urls?:string[];importedId?:string;recheckResults?:string[];refreshResult?:{selected:number;checked:number;available:number;soldOut:number;unknown:number;failed:number;skipped:number};error?:string};
type ImportStatus='queued'|'importing'|'saved'|'failed';
type ImportProgress={url:string;status:ImportStatus;detail?:string};
class CatalogRequestError extends Error{constructor(message:string,readonly status?:number){super(message)}}
function hostLabel(url:string){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url.slice(0,72)}}
export function CatalogAdmin(){
 const [document,setDocument]=useState<CatalogDocument|null>(null),[urls,setUrls]=useState(''),[country,setCountry]=useState('США'),[collectionIds,setCollectionIds]=useState<string[]>([]),[busy,setBusy]=useState(''),[selected,setSelected]=useState<string[]>([]),[open,setOpen]=useState<string|null>(null),[importProgress,setImportProgress]=useState<ImportProgress[]>([]);
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[visibleCount,setVisibleCount]=useState(24),[refreshClock]=useState(()=>Date.now());
 const [newCollection,setNewCollection]=useState<{name:string;nameUz:string;nameEn:string}|null>(null);
 const load=useCallback(async()=>{const r=await fetch('/api/catalog?admin=1',{cache:'no-store'}),data=await r.json() as Result;if(!r.ok||!data.document)throw Error(data.error??'Не удалось загрузить витрину.');setDocument(data.document);return data.document},[]);
 // Loading is the external synchronization performed by this effect.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load().catch(error=>toast.error((error as Error).message))},[load]);
 const call=async(command:unknown,revision=document?.revision)=>{if(!document||revision===undefined)throw new Error('Каталог загружается.');const r=await fetch('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision,command})});let data:Result={};try{data=await r.json() as Result}catch{}if(!r.ok)throw new CatalogRequestError(data.error??'Не удалось сохранить каталог.',r.status);if(data.document)setDocument(data.document);return data};
 async function importAll(){
  const parsed=parseCatalogImportQueue(urls),batch=parsed.links.slice(0,catalogImportBatchSize);if(!batch.length||!document)return;
  setBusy('import');setImportProgress(batch.map(url=>({url,status:'queued'})));let saved=0,failed=0,revision=document.revision,firstImportedId:string|undefined,halted=false;
  const updateProgress=(index:number,progress:ImportProgress)=>setImportProgress(items=>items.map((item,i)=>i===index?progress:item));
  const finishItem=(url:string,id?:string)=>{saved++;setUrls(value=>removeImportedCatalogLinks(value,[url]));if(id&&!firstImportedId)firstImportedId=id};
  try{
   for(let index=0;index<batch.length;index++){
    const url=batch[index];updateProgress(index,{url,status:'importing'});let completed=false,reason='Не удалось добавить черновик.',stop=false;
    for(let attempt=0;attempt<2&&!completed;attempt++){
     const requestedAt=Date.now();
     try{
      const data=await call({kind:'import',url,collectionIds,country},revision);
      if(data.document)revision=data.document.revision;
      finishItem(url,data.importedId);updateProgress(index,{url,status:'saved',detail:'Черновик сохранён'});completed=true;
     }catch(error){
      const failure=error as CatalogRequestError;reason=failure.message;
      if(failure.status===429){reason='Достигнут лимит импорта. Повторите оставшиеся ссылки позже.';stop=true;break}
      const recoverable=failure.status===409||failure.status===undefined||failure.status>=500;
      if(!recoverable)break;
      try{
       const latest=await load();revision=latest.revision;
       let canonical='';try{canonical=canonicalCatalogUrl(url)}catch{}
       const committed=canonical?latest.entries.find(entry=>canonicalCatalogUrl(entry.draft.sourceUrl)===canonical&&entry.draft.checkedAt>=requestedAt-5000):undefined;
       if(committed){finishItem(url,committed.id);updateProgress(index,{url,status:'saved',detail:'Состояние восстановлено'});completed=true;break}
      }catch{reason='Не удалось обновить каталог для безопасного повтора.';stop=true;break}
      if(attempt===1&&failure.status===409)stop=true;
     }
    }
    if(!completed){failed++;updateProgress(index,{url,status:'failed',detail:reason})}
    if(stop){halted=true;break}
   }
   if(halted){setImportProgress(items=>items.map(item=>item.status==='queued'?{...item,detail:'Ожидает повтора'}:item))}
   if(firstImportedId){setOpen(firstImportedId);window.setTimeout(()=>window.document.getElementById(`catalog-${firstImportedId}`)?.scrollIntoView({behavior:'smooth',block:'center'}),80)}
   if(failed||halted)toast.warning(`Черновиков добавлено: ${saved}. Остальные ссылки оставлены в очереди для повтора.`);
   else toast.success(`Черновиков добавлено: ${saved}. Они сохранены в каталоге и готовы к проверке.`);
  }finally{setBusy('')}
 }
 async function discover(){const {links}=parseCatalogImportQueue(urls);if(links.length!==1)return;setBusy('discover');try{const data=await call({kind:'discover',url:links[0]});setUrls((data.urls??[]).join('\n'));setImportProgress([]);toast.success(`Найдено ссылок: ${data.urls?.length??0}`)}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function command(value:unknown,message:string){setBusy('save');try{await call(value);setSelected([]);toast.success(message)}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function recheck(ids:string[]){const batch=ids.slice(0,10);if(!batch.length)return;setBusy('recheck');try{const data=await call({kind:'recheck',ids:batch});setSelected([]);const failed=(data.recheckResults??[]).filter(line=>!line.endsWith(': проверено')).length;if(failed)toast.warning(`Проверено: ${batch.length-failed}, требуют внимания: ${failed}`);else toast.success(`Проверено товаров: ${batch.length}`)}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function refreshDue(){if(!document)return;setBusy('refresh-due');try{const data=await call({kind:'refresh-due'}),result=data.refreshResult;if(!result){toast.success('Проверка очереди завершена');return}if(result.soldOut)toast.warning(`Скрыто после подтверждения магазина: ${result.soldOut}`);else if(result.failed||result.unknown)toast.warning(`Проверено: ${result.checked}; требуют внимания: ${result.failed+result.unknown}`);else toast.success(result.checked?`Обновлено по источнику: ${result.checked}`:'Сейчас нет товаров для проверки')}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function addCollection(){if(!newCollection?.name.trim()||!document)return;const id='collection-'+crypto.randomUUID();setBusy('save');try{await call({kind:'collection',collection:{id,name:newCollection.name.trim(),nameUz:newCollection.nameUz.trim(),nameEn:newCollection.nameEn.trim(),description:'',visible:true,position:document.collections.length}});setCollectionIds(ids=>[...ids,id]);setNewCollection(null);toast.success('Подборка создана')}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function saveDraft(id:string,draft:CatalogDraft){await command({kind:'edit',id,draft},'Карточка сохранена')}
 const ready=useMemo(()=>document?.entries.filter(e=>!catalogIssues(e.draft).length&&!e.published).map(e=>e.id)??[],[document]);
 const attention=useMemo(()=>document?.entries.filter(e=>catalogIssues(e.draft).length).map(e=>e.id)??[],[document]);
 if(!document)return <section className="surface admin-section" role="status"><Loader2 className="spin"/> Загружаем витрину…</section>;
 const filteredEntries=[...document.entries].filter(entry=>[entry.draft.name,entry.draft.brand,entry.draft.sourceUrl].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).filter(entry=>filter==='all'||(filter==='published'&&!!entry.published)||(filter==='draft'&&!entry.published)||(filter==='attention'&&catalogIssues(entry.draft).length>0)||(filter==='no-image'&&!entry.draft.image)||(filter==='no-variants'&&!entry.draft.variants.some(v=>v.available))).sort((a,b)=>Number(Boolean(catalogIssues(b.draft).length))-Number(Boolean(catalogIssues(a.draft).length)));
 const importQueue=parseCatalogImportQueue(urls),importBatch=importQueue.links.slice(0,catalogImportBatchSize),settledImports=importProgress.filter(item=>item.status==='saved'||item.status==='failed').length,savedImports=importProgress.filter(item=>item.status==='saved').length;
  const reports=(document.availabilityReports??[]).filter(report=>!report.resolvedAt),unavailableReports=reports.filter(report=>report.answer==='unavailable');
 const due=dueCatalogEntries(document,refreshClock).length;
 return <section className="catalog-workspace">
  <section className="surface catalog-importer"><div><span className="eyebrow">БЫСТРОЕ ДОБАВЛЕНИЕ</span><h2>Ссылки магазинов → черновики каталога</h2><p>Вставьте страницы товаров, по одной ссылке на строку. Atlas соберёт название, цену, фотографии и доступную матрицу цветов и размеров. Импорт создаёт черновики — публикация остаётся за вами.</p></div>
   <textarea aria-label="Ссылки товаров или коллекции" disabled={busy==='import'} value={urls} onChange={e=>{setUrls(e.target.value);setImportProgress([])}} placeholder={'https://магазин.com/products/товар-1\nhttps://магазин.com/products/товар-2'}/>
   <div className="catalog-import-queue-summary" aria-live="polite"><span>{importQueue.links.length} уникальных ссылок</span><span>За один проход: до {catalogImportBatchSize}</span>{importQueue.duplicates>0&&<span>Повторы пропущены: {importQueue.duplicates}</span>}{importQueue.links.length>catalogImportBatchSize&&<span>После прохода останется: {importQueue.links.length-catalogImportBatchSize}</span>}</div>
   {importQueue.links.length>catalogImportBatchSize&&<p className="catalog-import-hint">Сначала обработаются первые {catalogImportBatchSize}. Остальные ссылки останутся в поле и не потеряются.</p>}
   {importProgress.length>0&&<div className="catalog-import-progress" aria-live="polite"><div className="catalog-import-progress-head"><strong>Импорт: {settledImports} из {importProgress.length}</strong><span>Добавлено черновиков: {savedImports}</span></div><progress max={importProgress.length} value={settledImports}/><ul>{importProgress.map(item=><li key={item.url} className={`import-${item.status}`}><span>{hostLabel(item.url)}</span><small>{item.detail??(item.status==='importing'?'Читаем магазин…':item.status==='queued'?'В очереди':'')}</small></li>)}</ul></div>}
   <div className="catalog-import-options"><label>Страна отправки<input value={country} maxLength={80} onChange={e=>setCountry(e.target.value)}/></label><fieldset><legend>Добавить в подборки</legend><div>{document.collections.map(c=><label key={c.id}><input type="checkbox" checked={collectionIds.includes(c.id)} onChange={e=>setCollectionIds(e.target.checked?[...collectionIds,c.id]:collectionIds.filter(id=>id!==c.id))}/>{c.name}</label>)}<button type="button" className="text-button" onClick={()=>setNewCollection({name:'',nameUz:'',nameEn:''})}><FolderPlus size={16}/>Новая подборка</button></div></fieldset></div>
   <div className="catalog-import-actions"><button className="btn primary" disabled={!!busy||!importBatch.length} onClick={()=>void importAll()}>{busy==='import'?<Loader2 className="spin"/>:<Link2/>}{busy==='import'?'Добавляем…':`Импортировать черновики (${importBatch.length})`}</button><button className="btn secondary" disabled={!!busy||importQueue.links.length!==1} onClick={()=>void discover()}><RefreshCw/>Найти товары на странице коллекции</button></div>
  </section>
  <section className="surface admin-section"><div className="admin-section-head"><div><h2>Подборки на главной</h2><p>Используйте их для одежды, косметики, распродаж, брендов или сезонных предложений.</p></div><button className="btn secondary" onClick={()=>setNewCollection({name:'',nameUz:'',nameEn:''})}><FolderPlus/>Создать</button></div>
   <div className="catalog-collections">{document.collections.length?[...document.collections].sort((a,b)=>a.position-b.position).map(c=><CollectionRow key={`${c.id}:${document.revision}`} value={c} disabled={!!busy} onSave={collection=>void command({kind:'collection',collection},'Подборка сохранена')}/>):<p className="micro">Создайте первую подборку и выберите её при импорте.</p>}</div>
  </section>
  {!!reports.length&&<section className="surface admin-section catalog-reports"><div className="admin-section-head"><div><h2><MessageSquareWarning/> Сообщения о наличии</h2><p>Новых ответов: {reports.length}. Сообщили об отсутствии: {unavailableReports.length}.</p></div></div><div>{reports.slice(0,20).map(report=>{const entry=document.entries.find(item=>item.id===report.productId);return <article key={report.id}><span className={report.answer==='unavailable'?'report-unavailable':'report-available'}>{report.answer==='unavailable'?'Нет в наличии':'Есть в наличии'}</span><div><b>{entry?.draft.name??'Товар каталога'}</b><small>{report.variant?`Вариант: ${report.variant} · `:''}{new Date(report.createdAt).toLocaleString('ru-RU')}</small></div><a className="text-button" href={report.sourceUrl} target="_blank" rel="noopener noreferrer">Магазин<ExternalLink size={14}/></a>{entry&&<button type="button" className="text-button" onClick={()=>{setOpen(entry.id);window.document.getElementById(`catalog-${entry.id}`)?.scrollIntoView({behavior:'smooth',block:'center'})}}>Карточка</button>}</article>})}</div></section>}
  <section className="surface admin-section"><div className="admin-section-head"><div><h2>Контроль товаров</h2><p>{attention.length?`Требуют внимания: ${attention.length}. Сначала проверьте цену и наличие.`:'Все карточки проверены.'}</p></div><div className="catalog-bulk-actions"><button className="btn secondary" disabled={!!busy||!due} onClick={()=>void refreshDue()}>{busy==='refresh-due'?<Loader2 className="spin"/>:<RefreshCw/>}Обновить очередь ({due})</button><button className="btn secondary" disabled={!!busy||!(selected.length||attention.length)} onClick={()=>void recheck(selected.length?selected:attention)}>{busy==='recheck'?<Loader2 className="spin"/>:<RefreshCw/>}Проверить {selected.length?`выбранные (${Math.min(selected.length,10)})`:`проблемные (${Math.min(attention.length,10)})`}</button><button className="btn primary" disabled={!!busy||!ready.length} onClick={()=>void command({kind:'publish',ids:ready},`Опубликовано: ${ready.length}`)}><Send/>Опубликовать готовые ({ready.length})</button>{selected.length>0&&<button className="btn secondary" disabled={!!busy} onClick={()=>void command({kind:'hide',ids:selected},'Товары скрыты')}><EyeOff/>Скрыть ({selected.length})</button>}</div></div>
   <p className="micro">Источник каждой опубликованной карточки ставится в очередь через {catalogRefreshInterval/3600000} часа. «Обновить очередь» проверяет до 5 разных магазинов и скрывает товар только если магазин явно подтвердил отсутствие всех вариантов.</p>
   <div className="catalog-review-controls"><input type="search" aria-label="Поиск товаров" placeholder="Товар, бренд или магазин" value={search} onChange={e=>{setSearch(e.target.value);setVisibleCount(24)}}/><select aria-label="Статус товаров" value={filter} onChange={e=>{setFilter(e.target.value);setVisibleCount(24)}}><option value="all">Все товары</option><option value="published">Опубликованы</option><option value="draft">Черновики</option><option value="attention">Требуют проверки</option><option value="no-image">Без фото</option><option value="no-variants">Без доступных вариантов</option></select></div>
   <div className="catalog-drafts">{filteredEntries.slice(0,visibleCount).map(entry=>{const issues=catalogIssues(entry.draft),published=!!entry.published,entryReports=reports.filter(report=>report.productId===entry.id),refresh=entry.refresh;return <article id={`catalog-${entry.id}`} key={entry.id} className="catalog-draft"><label className="catalog-select"><input type="checkbox" checked={selected.includes(entry.id)} onChange={e=>setSelected(e.target.checked?[...selected,entry.id]:selected.filter(id=>id!==entry.id))}/><span className={issues.length?'draft-review':published?'draft-live':'draft-ready'}>{entryReports.some(report=>report.answer==='unavailable')?'Сообщили: нет':entry.autoHiddenAt?'Скрыт: нет в наличии':issues.length?`${issues.length} проверить`:published?'Опубликован':'Черновик'}</span></label><button className="catalog-draft-summary" type="button" onClick={()=>setOpen(open===entry.id?null:entry.id)}>{entry.draft.image?<img src={entry.draft.image} alt=""/>:<span><ImageIcon/></span>}<div><b>{entry.draft.name||'Без названия'}</b><small>{new URL(entry.draft.sourceUrl).hostname} · {entry.draft.price??'—'} {entry.draft.currency}</small><em>{entryReports.length?`Сообщений о наличии: ${entryReports.length}`:refresh?.lastError??entry.draft.lastCheckError??(refresh?.lastSuccessAt?`Источник: ${new Date(refresh.lastSuccessAt).toLocaleString('ru-RU')}`:(issues.join(' · ')||`${entry.draft.variants.filter(v=>v.available).length} вариантов · ${entry.draft.images.length} фото`))}</em></div><ChevronDown className={open===entry.id?'open':''}/></button>{open===entry.id&&<DraftEditor key={`${entry.id}:${document.revision}`} draft={entry.draft} collections={document.collections} disabled={!!busy} onSave={draft=>void saveDraft(entry.id,draft)} onPublish={()=>void command({kind:'publish',ids:[entry.id]},'Товар опубликован')} onHide={()=>void command({kind:'hide',ids:[entry.id]},'Товар скрыт')}/>}</article>})}</div>
   {!filteredEntries.length&&<p role="status">По вашему запросу товаров нет. Измените поиск или фильтр.</p>}
   {filteredEntries.length>visibleCount&&<button className="btn secondary" onClick={()=>setVisibleCount(n=>n+24)}>Показать ещё</button>}
  </section>
  <Modal open={newCollection!==null} onClose={()=>setNewCollection(null)} title="Новая подборка" description="Название на русском обязательно; другие языки можно заполнить сейчас или позже.">
    <form className="collection-create-form" onSubmit={event=>{event.preventDefault();void addCollection()}}>
      <label>Название · RU<input autoFocus maxLength={100} required value={newCollection?.name??''} onChange={event=>setNewCollection(value=>value?{...value,name:event.target.value}:value)}/></label>
      <label>Название · UZ<input maxLength={100} value={newCollection?.nameUz??''} onChange={event=>setNewCollection(value=>value?{...value,nameUz:event.target.value}:value)}/></label>
      <label>Название · EN<input maxLength={100} value={newCollection?.nameEn??''} onChange={event=>setNewCollection(value=>value?{...value,nameEn:event.target.value}:value)}/></label>
      <button className="btn primary" type="submit" disabled={!!busy||!newCollection?.name.trim()}>{busy?'Сохраняем…':'Создать подборку'}</button>
    </form>
  </Modal>
 </section>
}
function CollectionRow({value,disabled,onSave}:{value:CatalogCollection;disabled:boolean;onSave:(v:CatalogCollection)=>void}){const [draft,setDraft]=useState(value);return <article><input aria-label="Название подборки" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input aria-label="Название на узбекском" placeholder="UZ" value={draft.nameUz} onChange={e=>setDraft({...draft,nameUz:e.target.value})}/><input aria-label="Название на английском" placeholder="EN" value={draft.nameEn} onChange={e=>setDraft({...draft,nameEn:e.target.value})}/><label><input type="checkbox" checked={draft.visible} onChange={e=>setDraft({...draft,visible:e.target.checked})}/>Показывать</label><button className="btn secondary" disabled={disabled||draft.name.trim().length<1} onClick={()=>onSave(draft)}><Check/>Сохранить</button></article>}
function DraftEditor({draft,collections,disabled,onSave,onPublish,onHide}:{draft:CatalogDraft;collections:CatalogCollection[];disabled:boolean;onSave:(v:CatalogDraft)=>void;onPublish:()=>void;onHide:()=>void}){
 const [value,setValue]=useState<CatalogDraft>(()=>({...draft,description:cleanGeneratedCatalogDescription(draft.description)})),issues=catalogIssues(value),gallery=dedupeSafeImages(value.images,value.sourceUrl);
 return <div className="catalog-editor">
  <div className="two-fields"><label>Название<input value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label><label>Бренд<input value={value.brand} onChange={e=>setValue({...value,brand:e.target.value})}/></label><label>Категория<select value={value.category} onChange={e=>setValue({...value,category:e.target.value as CatalogDraft['category']})}>{catalogCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Страна<input value={value.country} onChange={e=>setValue({...value,country:e.target.value})}/></label><label>Цена<input type="number" min="0" step=".01" value={value.price??''} onChange={e=>setValue({...value,price:e.target.value?Number(e.target.value):undefined})}/></label><label>Валюта<input maxLength={3} value={value.currency} onChange={e=>setValue({...value,currency:e.target.value.toUpperCase()})}/></label><label>Цена до скидки<input type="number" min="0" step=".01" value={value.referencePrice??''} onChange={e=>setValue({...value,referencePrice:e.target.value?Number(e.target.value):undefined})}/></label><label>Вес с коробкой, кг<input type="number" min=".01" max="49.5" step=".01" value={value.boxedWeight} onChange={e=>setValue({...value,boxedWeight:Number(e.target.value)})}/></label></div>
  <label>Главное фото<input type="url" value={value.image} onChange={e=>setValue({...value,image:e.target.value})}/></label>
  {!!gallery.length&&<div className="catalog-photo-gallery"><strong>Фото со страницы магазина · {gallery.length}</strong><div>{gallery.map((image,index)=><img key={`${image}:${index}`} src={image} alt={`Фото товара ${index+1}`} loading="lazy"/>)}</div></div>}
  <label>Описание<textarea value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label>
  <CatalogVariantMatrix variants={value.variants} currency={value.currency} sourceUrl={value.sourceUrl}/>
  <fieldset><legend>Подборки</legend><div>{collections.map(c=><label key={c.id}><input type="checkbox" checked={value.collectionIds.includes(c.id)} onChange={e=>setValue({...value,collectionIds:e.target.checked?[...value.collectionIds,c.id]:value.collectionIds.filter(id=>id!==c.id)})}/>{c.name}</label>)}</div></fieldset>
  {issues.length>0&&<p className="catalog-issues">Перед публикацией: {issues.join(', ')}</p>}
  <div className="catalog-editor-actions"><button className="btn secondary" disabled={disabled} onClick={()=>onSave(value)}><Check/>Сохранить</button><button className="btn primary" disabled={disabled||issues.length>0} onClick={onPublish}><Send/>Опубликовать</button><button className="text-button" disabled={disabled} onClick={onHide}><EyeOff/>Скрыть</button></div>
 </div>
}
function CatalogVariantMatrix({variants,currency,sourceUrl}:{variants:CatalogDraft['variants'];currency:string;sourceUrl:string}){
 const colors=new Set(variants.map(item=>item.color).filter(Boolean)),sizes=new Set(variants.map(item=>item.size).filter(Boolean));
 return <section className="catalog-variant-panel" aria-label="Варианты товара">
  <header><div><h3>Размеры, цвета и цены магазина</h3><p>{variants.length} вариантов{colors.size?` · ${colors.size} цветов`:''}{sizes.size?` · ${sizes.size} размеров`:''}</p></div><span>Данные источника</span></header>
  {!variants.length?<p className="catalog-variant-empty">Магазин не отдал варианты. Карточка остаётся редактируемым черновиком.</p>:<div className="catalog-variant-scroll"><table className="catalog-variant-table"><thead><tr><th>Фото</th><th>Вариант</th><th>Цвет</th><th>Размер</th><th>Цена</th><th>Наличие в данных магазина</th></tr></thead><tbody>{variants.map((item,index)=>{const image=safeImage(item.image,sourceUrl);return <tr key={item.id??`${item.label}:${index}`}><td>{image?<img src={image} alt="" loading="lazy"/>:<span className="catalog-variant-no-image">—</span>}</td><td><strong>{item.label||'Без названия'}</strong>{item.id&&<small>Артикул варианта: {item.id}</small>}</td><td>{item.color||'—'}</td><td>{item.size||'—'}{item.sizeLabel&&<small>{item.sizeLabel}</small>}</td><td>{item.price===undefined?'—':`${item.price.toLocaleString('ru-RU',{maximumFractionDigits:2})} ${currency}`}</td><td><span className={item.availabilityKnown===false?'variant-unknown':item.available?'variant-available':'variant-sold-out'}>{item.availabilityKnown===false?'Не указано':item.available?'Есть по данным страницы':'Нет по данным страницы'}</span></td></tr>})}</tbody></table></div>}
 </section>
}
