"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Check,ChevronDown,ExternalLink,EyeOff,FolderPlus,ImageIcon,Link2,Loader2,MessageSquareWarning,RefreshCw,Send} from 'lucide-react';
import {toast} from 'sonner';
import {catalogCategories,catalogIssues,catalogRefreshInterval,dueCatalogEntries,type CatalogCollection,type CatalogDocument,type CatalogDraft} from '@/lib/market/catalog-editor';

type Result={document?:CatalogDocument;urls?:string[];importedId?:string;recheckResults?:string[];refreshResult?:{selected:number;checked:number;available:number;soldOut:number;unknown:number;failed:number;skipped:number};error?:string};
const lines=(value:string)=>[...new Set(value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean))].slice(0,10);
export function CatalogAdmin(){
 const [document,setDocument]=useState<CatalogDocument|null>(null),[urls,setUrls]=useState(''),[country,setCountry]=useState('США'),[collectionIds,setCollectionIds]=useState<string[]>([]),[busy,setBusy]=useState(''),[selected,setSelected]=useState<string[]>([]),[open,setOpen]=useState<string|null>(null);
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[visibleCount,setVisibleCount]=useState(24),[refreshClock]=useState(()=>Date.now());
 const load=useCallback(async()=>{const r=await fetch('/api/catalog?admin=1',{cache:'no-store'}),data=await r.json() as Result;if(!r.ok||!data.document)throw Error(data.error??'Не удалось загрузить витрину.');setDocument(data.document)},[]);
 // Loading is the external synchronization performed by this effect.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load().catch(error=>toast.error((error as Error).message))},[load]);
 const call=async(command:unknown,revision=document?.revision)=>{if(!document||revision===undefined)throw Error('Каталог загружается.');const r=await fetch('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision,command})}),data=await r.json() as Result;if(!r.ok)throw Error(data.error??'Не удалось сохранить каталог.');if(data.document)setDocument(data.document);return data};
 async function importAll(){const queue=lines(urls);if(!queue.length||!document)return;setBusy('import');let ok=0,revision=document.revision;try{for(const url of queue){try{const data=await call({kind:'import',url,collectionIds,country},revision);if(data.document){revision=data.document.revision;setDocument(data.document)}ok++}catch(error){toast.error(`${new URL(url).hostname}: ${(error as Error).message}`)}}if(ok===queue.length)setUrls('');toast.success(`Готово карточек: ${ok} из ${queue.length}`)}finally{setBusy('')}}
 async function discover(){const [url]=lines(urls);if(!url)return;setBusy('discover');try{const data=await call({kind:'discover',url});setUrls((data.urls??[]).join('\n'));toast.success(`Найдено ссылок: ${data.urls?.length??0}`)}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function command(value:unknown,message:string){setBusy('save');try{await call(value);setSelected([]);toast.success(message)}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function recheck(ids:string[]){const batch=ids.slice(0,10);if(!batch.length)return;setBusy('recheck');try{const data=await call({kind:'recheck',ids:batch});setSelected([]);const failed=(data.recheckResults??[]).filter(line=>!line.endsWith(': проверено')).length;if(failed)toast.warning(`Проверено: ${batch.length-failed}, требуют внимания: ${failed}`);else toast.success(`Проверено товаров: ${batch.length}`)}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function refreshDue(){if(!document)return;setBusy('refresh-due');try{const data=await call({kind:'refresh-due'}),result=data.refreshResult;if(!result){toast.success('Проверка очереди завершена');return}if(result.soldOut)toast.warning(`Скрыто после подтверждения магазина: ${result.soldOut}`);else if(result.failed||result.unknown)toast.warning(`Проверено: ${result.checked}; требуют внимания: ${result.failed+result.unknown}`);else toast.success(result.checked?`Обновлено по источнику: ${result.checked}`:'Сейчас нет товаров для проверки')}catch(error){toast.error((error as Error).message)}finally{setBusy('')}}
 async function addCollection(){const name=window.prompt('Название подборки, например «Уход и косметика»');if(!name?.trim()||!document)return;const id='collection-'+crypto.randomUUID();await command({kind:'collection',collection:{id,name:name.trim(),nameUz:'',nameEn:'',description:'',visible:true,position:document.collections.length}},'Подборка создана');setCollectionIds([...collectionIds,id])}
 async function saveDraft(id:string,draft:CatalogDraft){await command({kind:'edit',id,draft},'Карточка сохранена')}
 const ready=useMemo(()=>document?.entries.filter(e=>!catalogIssues(e.draft).length&&!e.published).map(e=>e.id)??[],[document]);
 const attention=useMemo(()=>document?.entries.filter(e=>catalogIssues(e.draft).length).map(e=>e.id)??[],[document]);
 if(!document)return <section className="surface admin-section" role="status"><Loader2 className="spin"/> Загружаем витрину…</section>;
 const filteredEntries=[...document.entries].filter(entry=>[entry.draft.name,entry.draft.brand,entry.draft.sourceUrl].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).filter(entry=>filter==='all'||(filter==='published'&&!!entry.published)||(filter==='draft'&&!entry.published)||(filter==='attention'&&catalogIssues(entry.draft).length>0)||(filter==='no-image'&&!entry.draft.image)||(filter==='no-variants'&&!entry.draft.variants.some(v=>v.available))).sort((a,b)=>Number(Boolean(catalogIssues(b.draft).length))-Number(Boolean(catalogIssues(a.draft).length)));
  const reports=(document.availabilityReports??[]).filter(report=>!report.resolvedAt),unavailableReports=reports.filter(report=>report.answer==='unavailable');
 const due=dueCatalogEntries(document,refreshClock).length;
 return <section className="catalog-workspace">
  <section className="surface catalog-importer"><div><span className="eyebrow">БЫСТРОЕ ДОБАВЛЕНИЕ</span><h2>Вставьте ссылки — Atlas соберёт карточки</h2><p>Название, магазин, цена, фотографии, размеры и цвета подставятся автоматически. До 10 ссылок, каждая с новой строки.</p></div>
   <textarea aria-label="Ссылки товаров или коллекции" value={urls} onChange={e=>setUrls(e.target.value)} placeholder={'https://магазин.com/products/товар-1\nhttps://магазин.com/products/товар-2'}/>
   <div className="catalog-import-options"><label>Страна отправки<input value={country} maxLength={80} onChange={e=>setCountry(e.target.value)}/></label><fieldset><legend>Добавить в подборки</legend><div>{document.collections.map(c=><label key={c.id}><input type="checkbox" checked={collectionIds.includes(c.id)} onChange={e=>setCollectionIds(e.target.checked?[...collectionIds,c.id]:collectionIds.filter(id=>id!==c.id))}/>{c.name}</label>)}<button type="button" className="text-button" onClick={()=>void addCollection()}><FolderPlus size={16}/>Новая подборка</button></div></fieldset></div>
   <div className="catalog-import-actions"><button className="btn primary" disabled={!!busy||!lines(urls).length} onClick={()=>void importAll()}>{busy==='import'?<Loader2 className="spin"/>:<Link2/>}Создать карточки</button><button className="btn secondary" disabled={!!busy||lines(urls).length!==1} onClick={()=>void discover()}><RefreshCw/>Найти товары на странице коллекции</button></div>
  </section>
  <section className="surface admin-section"><div className="admin-section-head"><div><h2>Подборки на главной</h2><p>Используйте их для одежды, косметики, распродаж, брендов или сезонных предложений.</p></div><button className="btn secondary" onClick={()=>void addCollection()}><FolderPlus/>Создать</button></div>
   <div className="catalog-collections">{document.collections.length?[...document.collections].sort((a,b)=>a.position-b.position).map(c=><CollectionRow key={`${c.id}:${document.revision}`} value={c} disabled={!!busy} onSave={collection=>void command({kind:'collection',collection},'Подборка сохранена')}/>):<p className="micro">Создайте первую подборку и выберите её при импорте.</p>}</div>
  </section>
  {!!reports.length&&<section className="surface admin-section catalog-reports"><div className="admin-section-head"><div><h2><MessageSquareWarning/> Сообщения о наличии</h2><p>Новых ответов: {reports.length}. Сообщили об отсутствии: {unavailableReports.length}.</p></div></div><div>{reports.slice(0,20).map(report=>{const entry=document.entries.find(item=>item.id===report.productId);return <article key={report.id}><span className={report.answer==='unavailable'?'report-unavailable':'report-available'}>{report.answer==='unavailable'?'Нет в наличии':'Есть в наличии'}</span><div><b>{entry?.draft.name??'Товар каталога'}</b><small>{report.variant?`Вариант: ${report.variant} · `:''}{new Date(report.createdAt).toLocaleString('ru-RU')}</small></div><a className="text-button" href={report.sourceUrl} target="_blank" rel="noopener noreferrer">Магазин<ExternalLink size={14}/></a>{entry&&<button type="button" className="text-button" onClick={()=>{setOpen(entry.id);window.document.getElementById(`catalog-${entry.id}`)?.scrollIntoView({behavior:'smooth',block:'center'})}}>Карточка</button>}</article>})}</div></section>}
  <section className="surface admin-section"><div className="admin-section-head"><div><h2>Контроль товаров</h2><p>{attention.length?`Требуют внимания: ${attention.length}. Сначала проверьте цену и наличие.`:'Все карточки проверены.'}</p></div><div className="catalog-bulk-actions"><button className="btn secondary" disabled={!!busy||!due} onClick={()=>void refreshDue()}>{busy==='refresh-due'?<Loader2 className="spin"/>:<RefreshCw/>}Обновить очередь ({due})</button><button className="btn secondary" disabled={!!busy||!(selected.length||attention.length)} onClick={()=>void recheck(selected.length?selected:attention)}>{busy==='recheck'?<Loader2 className="spin"/>:<RefreshCw/>}Проверить {selected.length?`выбранные (${Math.min(selected.length,10)})`:`проблемные (${Math.min(attention.length,10)})`}</button><button className="btn primary" disabled={!!busy||!ready.length} onClick={()=>void command({kind:'publish',ids:ready},`Опубликовано: ${ready.length}`)}><Send/>Опубликовать готовые ({ready.length})</button>{selected.length>0&&<button className="btn secondary" disabled={!!busy} onClick={()=>void command({kind:'hide',ids:selected},'Товары скрыты')}><EyeOff/>Скрыть ({selected.length})</button>}</div></div>
   <p className="micro">Источник каждой опубликованной карточки ставится в очередь через {catalogRefreshInterval/3600000} часа. «Обновить очередь» проверяет до 5 разных магазинов и скрывает товар только если магазин явно подтвердил отсутствие всех вариантов.</p>
   <div className="catalog-review-controls"><input type="search" aria-label="Поиск товаров" placeholder="Товар, бренд или магазин" value={search} onChange={e=>{setSearch(e.target.value);setVisibleCount(24)}}/><select aria-label="Статус товаров" value={filter} onChange={e=>{setFilter(e.target.value);setVisibleCount(24)}}><option value="all">Все товары</option><option value="published">Опубликованы</option><option value="draft">Черновики</option><option value="attention">Требуют проверки</option><option value="no-image">Без фото</option><option value="no-variants">Без доступных вариантов</option></select></div>
   <div className="catalog-drafts">{filteredEntries.slice(0,visibleCount).map(entry=>{const issues=catalogIssues(entry.draft),published=!!entry.published,entryReports=reports.filter(report=>report.productId===entry.id),refresh=entry.refresh;return <article id={`catalog-${entry.id}`} key={entry.id} className="catalog-draft"><label className="catalog-select"><input type="checkbox" checked={selected.includes(entry.id)} onChange={e=>setSelected(e.target.checked?[...selected,entry.id]:selected.filter(id=>id!==entry.id))}/><span className={issues.length?'draft-review':published?'draft-live':'draft-ready'}>{entryReports.some(report=>report.answer==='unavailable')?'Сообщили: нет':entry.autoHiddenAt?'Скрыт: нет в наличии':issues.length?`${issues.length} проверить`:published?'Опубликован':'Черновик'}</span></label><button className="catalog-draft-summary" type="button" onClick={()=>setOpen(open===entry.id?null:entry.id)}>{entry.draft.image?<img src={entry.draft.image} alt=""/>:<span><ImageIcon/></span>}<div><b>{entry.draft.name||'Без названия'}</b><small>{new URL(entry.draft.sourceUrl).hostname} · {entry.draft.price??'—'} {entry.draft.currency}</small><em>{entryReports.length?`Сообщений о наличии: ${entryReports.length}`:refresh?.lastError??entry.draft.lastCheckError??(refresh?.lastSuccessAt?`Источник: ${new Date(refresh.lastSuccessAt).toLocaleString('ru-RU')}`:(issues.join(' · ')||`${entry.draft.variants.filter(v=>v.available).length} вариантов · ${entry.draft.images.length} фото`))}</em></div><ChevronDown className={open===entry.id?'open':''}/></button>{open===entry.id&&<DraftEditor key={`${entry.id}:${document.revision}`} draft={entry.draft} collections={document.collections} disabled={!!busy} onSave={draft=>void saveDraft(entry.id,draft)} onPublish={()=>void command({kind:'publish',ids:[entry.id]},'Товар опубликован')} onHide={()=>void command({kind:'hide',ids:[entry.id]},'Товар скрыт')}/>}</article>})}</div>
   {!filteredEntries.length&&<p role="status">По вашему запросу товаров нет. Измените поиск или фильтр.</p>}
   {filteredEntries.length>visibleCount&&<button className="btn secondary" onClick={()=>setVisibleCount(n=>n+24)}>Показать ещё</button>}
  </section>
 </section>
}
function CollectionRow({value,disabled,onSave}:{value:CatalogCollection;disabled:boolean;onSave:(v:CatalogCollection)=>void}){const [draft,setDraft]=useState(value);return <article><input aria-label="Название подборки" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input aria-label="Название на узбекском" placeholder="UZ" value={draft.nameUz} onChange={e=>setDraft({...draft,nameUz:e.target.value})}/><input aria-label="Название на английском" placeholder="EN" value={draft.nameEn} onChange={e=>setDraft({...draft,nameEn:e.target.value})}/><label><input type="checkbox" checked={draft.visible} onChange={e=>setDraft({...draft,visible:e.target.checked})}/>Показывать</label><button className="btn secondary" disabled={disabled||draft.name.trim().length<1} onClick={()=>onSave(draft)}><Check/>Сохранить</button></article>}
function DraftEditor({draft,collections,disabled,onSave,onPublish,onHide}:{draft:CatalogDraft;collections:CatalogCollection[];disabled:boolean;onSave:(v:CatalogDraft)=>void;onPublish:()=>void;onHide:()=>void}){const [value,setValue]=useState(draft);const issues=catalogIssues(value);return <div className="catalog-editor"><div className="two-fields"><label>Название<input value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label><label>Бренд<input value={value.brand} onChange={e=>setValue({...value,brand:e.target.value})}/></label><label>Категория<select value={value.category} onChange={e=>setValue({...value,category:e.target.value as CatalogDraft['category']})}>{catalogCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Страна<input value={value.country} onChange={e=>setValue({...value,country:e.target.value})}/></label><label>Цена<input type="number" min="0" step=".01" value={value.price??''} onChange={e=>setValue({...value,price:e.target.value?Number(e.target.value):undefined})}/></label><label>Валюта<input maxLength={3} value={value.currency} onChange={e=>setValue({...value,currency:e.target.value.toUpperCase()})}/></label><label>Цена до скидки<input type="number" min="0" step=".01" value={value.referencePrice??''} onChange={e=>setValue({...value,referencePrice:e.target.value?Number(e.target.value):undefined})}/></label><label>Вес с коробкой, кг<input type="number" min=".01" max="49.5" step=".01" value={value.boxedWeight} onChange={e=>setValue({...value,boxedWeight:Number(e.target.value)})}/></label></div><label>Главное фото<input type="url" value={value.image} onChange={e=>setValue({...value,image:e.target.value})}/></label><label>Описание<textarea value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label><fieldset><legend>Подборки</legend><div>{collections.map(c=><label key={c.id}><input type="checkbox" checked={value.collectionIds.includes(c.id)} onChange={e=>setValue({...value,collectionIds:e.target.checked?[...value.collectionIds,c.id]:value.collectionIds.filter(id=>id!==c.id)})}/>{c.name}</label>)}</div></fieldset>{issues.length>0&&<p className="catalog-issues">Перед публикацией: {issues.join(', ')}</p>}<div className="catalog-editor-actions"><button className="btn secondary" disabled={disabled} onClick={()=>onSave(value)}><Check/>Сохранить</button><button className="btn primary" disabled={disabled||issues.length>0} onClick={onPublish}><Send/>Опубликовать</button><button className="text-button" disabled={disabled} onClick={onHide}><EyeOff/>Скрыть</button></div></div>}
