"use client";

import { ArrowUpRight } from "lucide-react";
import { useMarket } from "@/lib/market/store";
import { customsReferences as customsSources } from "@/lib/market/customs";
import { CustomsCalculator } from "./customs-estimate";
import { PageHeading } from "./market-ui";

// Public customs guidance (/customs): Russian text with Uzbek and English versions.
export function CustomsView() {
  const { pricing, state } = useMarket();
  if(state.communication.language!=='ru')return <LocalizedCustoms locale={state.communication.language} fx={pricing.fx}/>;
  return <>
    <PageHeading overline="ДО ОФОРМЛЕНИЯ ЗАКАЗА" title="Таможня: что нужно учитывать." description="Памятка для личных некоммерческих покупок в Узбекистан. Проверена 11 сентября 2026 года." />
    <div className="customs-grid"><section className="surface"><h2>Курьерские отправления</h2><strong className="customs-limit">$200</strong><p>Лимит беспошлинного ввоза на имя физического лица за календарный месяц по нормам, введённым с 1 мая 2025 года. Учитывайте покупки у других продавцов и сервисов.</p></section><section className="surface"><h2>Почтовые отправления</h2><strong className="customs-limit">$100</strong><p>Для международных почтовых отправлений установлена отдельная норма. Нельзя автоматически применять к ним курьерский лимит.</p></section></div>
    <CustomsCalculator fx={pricing.fx} locale={state.communication.language}/><section className="surface customs-text"><details className="ux-disclosure"><summary>Если стоимость выше нормы</summary><p>Для личных некоммерческих товаров превышение установленных норм облагается единым таможенным платежом. Конкретный расчёт зависит от таможенной стоимости, количества, категории и способа ввоза. Возможны отдельные сборы.</p></details><details className="ux-disclosure"><summary>Какая ставка используется</summary><p>Для обычного личного курьерского ввоза: 30% превышения, минимум $3 за кг облагаемой части. С 1 января 2027 года пункт 8 УП-174 предусматривает 20%, минимум $2 за кг. НДС повторно не добавляется. Дата прибытия меняет ставку в калькуляторе.</p><details><summary>Почему не 3% или 5% из публикаций?</summary><p>ПП-136 устанавливает отдельный эксперимент для бондовых складов и зарегистрированных платформ: 3% плюс НДС для специального перечня либо единый платёж 5%. Это не общий режим зарубежных покупок; 5% не означает 5% плюс НДС, а курьерский лимит $200 к этой схеме не переносится.</p></details></details><details className="ux-disclosure"><summary>Что означает ваше согласие</summary><p>При оформлении вы подтверждаете, что ознакомлены с условиями и понимаете возможность дополнительных таможенных платежей. Это не разрешение на автоматическое списание произвольной суммы: доплата согласовывается отдельно.</p></details><details className="ux-disclosure"><summary>Что Atlas пока не знает</summary><p>Мы не получаем ваши покупки через другие сервисы и официальный остаток месячного лимита. Оценка таможни показана отдельно и не включена в сумму Atlas. Страна магазина сама по себе не определяет размер платежа; некоторые категории и коммерческие партии имеют другие требования.</p></details><details className="ux-disclosure"><summary>Официальные источники</summary><div className="source-list">{customsSources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.title}<ArrowUpRight size={16} /></a>)}</div><p className="micro">Перед реальными покупками проверьте действующую редакцию правил и расчёт перевозчика. Эта памятка не заменяет таможенное решение.</p></details></section>
  </>;
}

function LocalizedCustoms({locale,fx}:{locale:'uz'|'en';fx:number}){
  const c=locale==='uz'?{overline:'BUYURTMA RASMIYLASHTIRISHDAN OLDIN',title:'Bojxona: nimalarni bilish kerak.',intro:'O‘zbekistondagi shaxsiy notijorat xaridlar uchun qo‘llanma.',courier:'Kuryer jo‘natmalari',courierText:'Jismoniy shaxs nomiga bir oy uchun bojsiz olib kirish limiti. Boshqa xizmatlardagi xaridlarni ham hisobga oling.',postal:'Pochta jo‘natmalari',postalText:'Xalqaro pochta jo‘natmalari uchun alohida norma mavjud. Kuryer limitini avtomatik qo‘llab bo‘lmaydi.',overLimit:'Qiymat limitdan oshsa',overText:'Limitdan oshgan qism yagona bojxona to‘lovi bilan soliqqa tortiladi. Hisob qiymat, miqdor, kategoriya va olib kirish usuliga bog‘liq.',rate:'Qaysi stavka ishlatiladi',rateText:'Oddiy shaxsiy kuryer jo‘natmasi uchun: oshgan qismning 30 foizi, kamida har kg uchun $3. 2027-yildan 20 foiz va kamida $2 nazarda tutilgan.',consent:'Roziligingiz nimani anglatadi',consentText:'Shartlarni o‘qiganingizni va qo‘shimcha to‘lov ehtimolini tushunganingizni tasdiqlaysiz. Qo‘shimcha to‘lov alohida kelishiladi.',unknown:'Atlas nimani bilmaydi',unknownText:'Boshqa xizmatlardagi rasmiy oylik limit qoldig‘i bizga ko‘rinmaydi. Baholangan bojxona summasi Atlas narxiga kirmaydi.',sources:'Rasmiy manbalar',sourcesText:'Haqiqiy xariddan oldin amaldagi qoidalarni tekshiring.'}:{overline:'BEFORE CHECKOUT',title:'Customs: what to keep in mind.',intro:'A guide for personal, non-commercial purchases in Uzbekistan.',courier:'Courier shipments',courierText:'Duty-free allowance for an individual per calendar month. Include purchases made through other services.',postal:'Postal shipments',postalText:'International postal shipments have a separate allowance. The courier allowance cannot be applied automatically.',overLimit:'If the value exceeds the allowance',overText:'The excess is subject to a single customs payment. The calculation depends on value, quantity, category and import method.',rate:'Which rate applies',rateText:'For ordinary personal courier imports: 30% of the excess, at least $3 per taxable kilogram. From 2027, 20% and at least $2 per kilogram are planned.',consent:'What your consent means',consentText:'You confirm that you understand the terms and possible extra customs payments. Any top-up is agreed separately.',unknown:'What Atlas does not know yet',unknownText:'We cannot see the official monthly allowance used through other services. The customs estimate is separate from the Atlas amount.',sources:'Official sources',sourcesText:'Before a real purchase, check the current rules.'};
  return <><PageHeading overline={c.overline} title={c.title} description={c.intro}/><div className="customs-grid"><section className="surface"><h2>{c.courier}</h2><strong className="customs-limit">$200</strong><p>{c.courierText}</p></section><section className="surface"><h2>{c.postal}</h2><strong className="customs-limit">$100</strong><p>{c.postalText}</p></section></div><CustomsCalculator fx={fx} locale={locale}/><section className="surface customs-text"><details className="ux-disclosure"><summary>{c.overLimit}</summary><p>{c.overText}</p></details><details className="ux-disclosure"><summary>{c.rate}</summary><p>{c.rateText}</p></details><details className="ux-disclosure"><summary>{c.consent}</summary><p>{c.consentText}</p></details><details className="ux-disclosure"><summary>{c.unknown}</summary><p>{c.unknownText}</p></details><details className="ux-disclosure"><summary>{c.sources}</summary><div className="source-list">{customsSources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.title}<ArrowUpRight size={16}/></a>)}</div><p className="micro">{c.sourcesText}</p></details></section></>;
}
