'use client';
import { useId, useState } from 'react';
import Link from '@/components/site-link';
import { estimateCourierCustoms, customsCheckedOn } from '@/lib/market/customs';
import type { Locale } from '@/lib/market/i18n';

const labels = {
  ru: { title:'Таможня, ориентир', from:'от', unavailable:'Уточните данные', assumption:'При свободном лимите месяца $200', separate:'Отдельно от суммы Atlas', used:'Уже ввезено в месяц прибытия, USD', date:'Дата прибытия на таможню', extra:'Дополнительно в таможенную стоимость, USD', extraHint:'Например, расходы, которые перевозчик включает в таможенную стоимость.', base:'Стоимость товаров', excess:'Превышение лимита', rule:'Ставка', minimum:'минимум', perKg:'за кг облагаемой части', note:'Личный курьерский ввоз. Остаток лимита вводится по вашим данным, не из таможенной базы. Вес и стоимость уточняет таможня; отдельные сборы, ограничения и регистрация устройств не учтены. Диапазон отражает неопределённость облагаемого веса.', details:'Условия и источники', invalid:'Введите неотрицательные суммы и корректную дату не ранее 01.05.2025.', calculator:'Оценить таможенный платёж', value:'Стоимость товаров, USD', weight:'Вес отправления с упаковкой, кг' },
  uz: { title:'Taxminiy bojxona to‘lovi', from:'dan', unavailable:'Ma’lumotlarni tekshiring', assumption:'Oylik $200 limit to‘liq mavjud bo‘lsa', separate:'Atlas summasiga kiritilmagan', used:'Kelish oyida avval olib kirilgan, USD', date:'Bojxonaga kelish sanasi', extra:'Bojxona qiymatiga qo‘shimcha, USD', extraHint:'Masalan, tashuvchi bojxona qiymatiga kiritadigan xarajatlar.', base:'Mahsulotlar qiymati', excess:'Limitdan oshgan qism', rule:'Stavka', minimum:'eng kam', perKg:'soliq solinadigan qismning kg uchun', note:'Shaxsiy kuryer jo‘natmasi. Limit siz kiritgan ma’lumotlardan olinadi, bojxona bazasidan emas. Qiymat va vaznni bojxona aniqlaydi; alohida yig‘imlar, cheklovlar va qurilmalarni ro‘yxatga olish hisobga olinmagan. Oraliq soliq solinadigan vazn noaniqligini bildiradi.', details:'Shartlar va manbalar', invalid:'Manfiy bo‘lmagan summalar va 01.05.2025 dan keyingi to‘g‘ri sanani kiriting.', calculator:'Bojxona to‘lovini hisoblash', value:'Mahsulotlar qiymati, USD', weight:'Qadoq bilan jo‘natma vazni, kg' },
  en: { title:'Estimated customs', from:'from', unavailable:'Check the inputs', assumption:'Assuming the full $200 monthly allowance', separate:'Not included in the Atlas amount', used:'Already imported in the arrival month, USD', date:'Expected customs arrival date', extra:'Additional customs value, USD', extraHint:'For example, costs your carrier includes in customs value.', base:'Merchandise value', excess:'Value above allowance', rule:'Rate', minimum:'minimum', perKg:'per kg of dutiable goods', note:'Personal courier imports only. Allowance is based on your inputs, not customs records. Customs determines value and weight; additional fees, restrictions and device registration are excluded. A range reflects uncertain dutiable weight.', details:'Conditions and sources', invalid:'Enter non-negative amounts and a valid date on or after 2025-05-01.', calculator:'Estimate customs charges', value:'Merchandise value, USD', weight:'Gross shipment weight, kg' },
};
export function CustomsEstimate({ valueUsd, grossKg, fx, locale = 'ru' }: { valueUsd: number; grossKg?: number; fx: number; locale?: Locale }) {
  const id = useId(), copy = labels[locale];
  const [used, setUsed] = useState('0'), [extra, setExtra] = useState('0');
  const [date, setDate] = useState(() => new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString().slice(0, 10));
  const estimate = estimateCourierCustoms({ valueUsd: valueUsd + (extra.trim() ? Number(extra) : NaN), usedUsd: used.trim() ? Number(used) : NaN, grossKg, date });
  const format = (usd: number) => new Intl.NumberFormat(locale === 'ru' ? 'ru-RU' : locale === 'uz' ? 'uz-UZ' : 'en-US', { maximumFractionDigits:0 }).format(Math.round(usd * fx)) + (locale === 'ru' ? ' сум' : locale === 'uz' ? ' so‘m' : ' UZS');
  const result = !estimate ? copy.unavailable : estimate.upperUsd === undefined ? copy.from + ' ' + format(estimate.lowerUsd) : estimate.upperUsd > estimate.lowerUsd ? format(estimate.lowerUsd) + ' – ' + format(estimate.upperUsd) : '≈ ' + format(estimate.lowerUsd);
  return <div className="customs-estimate-wrap"><details className="customs-estimate"><summary><span>{copy.title}</span><strong>{result}</strong></summary>
    <div className="customs-estimate-body"><p className="micro">{Number(used) === 0 ? copy.assumption + '. ' : ''}{copy.separate}.</p>
      <div className="field"><label htmlFor={id+'-used'}>{copy.used}</label><input id={id+'-used'} type="number" min="0" step="0.01" value={used} onChange={e=>setUsed(e.target.value)}/></div>
      <div className="field"><label htmlFor={id+'-date'}>{copy.date}</label><input id={id+'-date'} type="date" min="2025-05-01" value={date} onChange={e=>setDate(e.target.value)}/></div>
      <div className="field"><label htmlFor={id+'-extra'}>{copy.extra}</label><input id={id+'-extra'} type="number" min="0" step="0.01" value={extra} onChange={e=>setExtra(e.target.value)}/><small>{copy.extraHint}</small></div>
      {estimate ? <dl className="cost-lines"><div><dt>{copy.base}</dt><dd>${valueUsd.toFixed(2)}</dd></div><div><dt>{copy.excess}</dt><dd>${estimate.excessUsd.toFixed(2)}</dd></div><div><dt>{copy.rule}</dt><dd>{estimate.rate*100}% · {copy.minimum} ${estimate.minimumPerKg} {copy.perKg}</dd></div></dl> : <p role="alert">{copy.invalid}</p>}
      <p className="micro">{copy.note}</p><Link className="text-link" href="/customs">{copy.details} ↗</Link><small className="muted">{customsCheckedOn}</small>
    </div></details><span className="customs-estimate-caption">{Number(used) === 0 ? copy.assumption : copy.separate}</span>
  </div>;
}
export function CustomsCalculator({fx,locale='ru'}:{fx:number;locale?:Locale}) {
  const [value,setValue]=useState('300'),[weight,setWeight]=useState('1');const id=useId(),copy=labels[locale];
  return <section className="surface"><h2>{copy.calculator}</h2><div className="two-fields"><div className="field"><label htmlFor={id+'-value'}>{copy.value}</label><input id={id+'-value'} type="number" min="0" step="0.01" value={value} onChange={e=>setValue(e.target.value)}/></div><div className="field"><label htmlFor={id+'-weight'}>{copy.weight}</label><input id={id+'-weight'} type="number" min="0.01" step="0.01" value={weight} onChange={e=>setWeight(e.target.value)}/></div></div><CustomsEstimate valueUsd={value.trim()?Number(value):NaN} grossKg={weight.trim()?Number(weight):undefined} fx={fx} locale={locale}/></section>;
}
