'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Package,X,ChevronRight,ArrowUpRight} from 'lucide-react';
import Link from '@/components/site-link';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {money,type Product,type Quote} from '@/lib/market/domain';
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="select-control"><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export function ProductImage({product,className='',decorative=false}:{product:Product;className?:string;decorative?:boolean}){
 const [failedImage,setFailedImage]=useState('');
 if(!product.image||product.image===failedImage)return <div className={'no-photo '+className}><Package size={35}/><span>Товар по ссылке</span></div>;
 // Dynamic store images are displayed without proxying or optimization.
 // eslint-disable-next-line @next/next/no-img-element
 return <img className={'product-img '+className} src={product.image} onError={()=>setFailedImage(product.image)} alt={decorative?'':product.name} loading="lazy" referrerPolicy="no-referrer"/>;
}
export function PageHeading({overline,title,description,children}:{overline:string;title:string;description:string;children?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{overline}</div><h1>{title}</h1><p>{description}</p></div>{children}</div>}
export function Empty({title,description,href,label,children}:{title:string;description:string;href?:string;label?:string;children?:ReactNode}){return <div className="empty-state"><span className="empty-icon"><Package size={30}/></span><h2>{title}</h2><p>{description}</p>{href&&<Link href={href} className="btn primary">{label??'В каталог'}<ArrowUpRight size={18}/></Link>}{children}</div>}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description:string;children:ReactNode}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="atlas-modal" showCloseButton={false}><DialogClose asChild><button className="icon-btn modal-close" aria-label="Закрыть"><X size={20}/></button></DialogClose><DialogTitle className="modal-title">{title}</DialogTitle><DialogDescription>{description}</DialogDescription>{children}</DialogContent></Dialog>}
export function CostLines({q,shippingUnknown=false,locale='ru'}:{q:Pick<Quote,'merchandise'|'service'|'shipping'|'reserve'|'sourceShipping'|'buyout'|'conversion'|'deliveryMargin'|'optionalServices'>;shippingUnknown?:boolean;locale?:'ru'|'uz'|'en'}){const c={ru:{labels:['Товар','Доставка магазина','Сервис Atlas','Выкуп','Конвертация','Международная доставка','Маржа доставки','Дополнительные услуги','Возвратный резерв'],unknown:'Уточняется',free:'Бесплатно'},uz:{labels:['Tovar','Do‘kon yetkazishi','Atlas xizmati','Xarid komissiyasi','Konvertatsiya','Xalqaro yetkazish','Yetkazish marjasi','Qo‘shimcha xizmatlar','Qaytariladigan zaxira'],unknown:'Aniqlanmoqda',free:'Bepul'},en:{labels:['Item','Store delivery','Atlas service','Purchase fee','Conversion','International delivery','Delivery margin','Additional services','Refundable reserve'],unknown:'To be confirmed',free:'Free'}}[locale],rows=[[c.labels[0],q.merchandise],[c.labels[1],q.sourceShipping??0],[c.labels[2],q.service],[c.labels[3],q.buyout??0],[c.labels[4],q.conversion??0],[c.labels[5],q.shipping],[c.labels[6],q.deliveryMargin??0],[c.labels[7],q.optionalServices??0],[c.labels[8],q.reserve]];return <dl className="cost-lines">{rows.filter(([label,value])=>Number(value)>0||label===c.labels[0]||label===c.labels[1]).map(([l,n])=><div key={String(l)}><dt>{l}</dt><dd>{shippingUnknown&&l===c.labels[1]?c.unknown:l===c.labels[1]&&Number(n)===0?c.free:money(Number(n))}</dd></div>)}</dl>}
export function Expiry({expiresAt}:{expiresAt:number}){const [now,setNow]=useState(0);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);if(!now)return <span className="expiry">Проверяем срок расчёта…</span>;const seconds=Math.max(0,Math.floor((expiresAt-now)/1000));return <span className={seconds?'expiry':'expiry expired'}>{seconds?'Расчёт действует '+Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0'):'Расчёт истёк'}</span>}
export function SectionLink({href,children}:{href:string;children:ReactNode}){return <Link className="text-link" href={href}>{children}<ChevronRight size={17}/></Link>}
