'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Package,X,ChevronRight,ArrowUpRight} from 'lucide-react';
import Link from 'next/link';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {money,type Product,type Quote} from '@/lib/market/domain';
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="select-control"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export function ProductImage({product,className='',decorative=false}:{product:Product;className?:string;decorative?:boolean}){const [failed,setFailed]=useState(false);useEffect(()=>{setFailed(false)},[product.image]);return product.image&&!failed?<img className={'product-img '+className} src={product.image} onError={()=>setFailed(true)} alt={decorative?'':product.name} loading="lazy" referrerPolicy="no-referrer"/>:<div className={'no-photo '+className}><Package size={35}/><span>Товар по ссылке</span></div>}
export function PageHeading({overline,title,description,children}:{overline:string;title:string;description:string;children?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{overline}</div><h1>{title}</h1><p>{description}</p></div>{children}</div>}
export function Empty({title,description,href,label,children}:{title:string;description:string;href?:string;label?:string;children?:ReactNode}){return <div className="empty-state"><span className="empty-icon"><Package size={30}/></span><h2>{title}</h2><p>{description}</p>{href&&<Link href={href} className="btn primary">{label??'В каталог'}<ArrowUpRight size={18}/></Link>}{children}</div>}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description:string;children:ReactNode}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="atlas-modal" showCloseButton={false}><DialogClose asChild><button className="icon-btn modal-close" aria-label="Закрыть"><X size={20}/></button></DialogClose><DialogTitle className="modal-title">{title}</DialogTitle><DialogDescription>{description}</DialogDescription>{children}</DialogContent></Dialog>}
export function CostLines({q,shippingUnknown=false}:{q:Pick<Quote,'merchandise'|'service'|'shipping'|'reserve'|'sourceShipping'>;shippingUnknown?:boolean}){return <dl className="cost-lines">{[['Товар',q.merchandise],['Доставка магазина',q.sourceShipping??0],['Выкуп и сервис',q.service],['Доставка, предварительно',q.shipping],['Возвратный резерв',q.reserve]].map(([l,n])=><div key={l}><dt>{l}</dt><dd>{shippingUnknown&&l==='Доставка магазина'?'Уточняется':money(Number(n))}</dd></div>)}</dl>}
export function Expiry({expiresAt}:{expiresAt:number}){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);const seconds=Math.max(0,Math.floor((expiresAt-now)/1000));return <span className={seconds?'expiry':'expiry expired'}>{seconds?'Расчёт действует '+Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0'):'Расчёт истёк'}</span>}
export function SectionLink({href,children}:{href:string;children:ReactNode}){return <Link className="text-link" href={href}>{children}<ChevronRight size={17}/></Link>}
