'use client';
import {useState} from 'react';
import Link from '@/components/site-link';
import {ArrowUpRight,ArrowRight,Package,Wallet,Link2,Search,MapPin,ShieldCheck,ShoppingBag,Heart,Plus,LayoutGrid,X,Globe2,Settings2,Bell,BarChart3} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster,toast} from 'sonner';
import {products,price,money,balanceOf,validateSource,type Product} from '@/lib/market/domain';
import {useMarket} from '@/lib/market/store';
import {Choice,ProductImage,PageHeading,Empty,CostLines} from './market-ui';
import {GlobalLinkOrder} from './global-link-order';
import {AccountView,CustomsView} from './account-views';
import {countryName} from '@/lib/market/world';
import {CartView} from './shopping';
import {OrdersView,BalanceView,NotificationsView} from './order-workspace';
import {AnalyticsView,LegalView} from './prelaunch-views';
const titles:Record<string,string>={catalog:'Каталог',favorites:'Избранное',link:'Заказ по ссылке',cart:'Корзина',orders:'Мои заказы',balance:'Баланс',operations:'Кабинет оператора',notifications:'Уведомления',account:'Личный кабинет',customs:'Таможенные условия',analytics:'Аналитика',legal:'Правила Atlas'};
const navigate=(href:string)=>window.location.assign(href);
export default function Marketplace({view}:{view:string}) {
  const {state,pricing,ready,error,act,user,refresh}=useMarket();
  const [selected,setSelected]=useState<Product|null>(null),[variant,setVariant]=useState(''),[adding,setAdding]=useState(false);
  const count=state.cart.reduce((s,i)=>s+i.quantity,0),balance=balanceOf(state),unread=state.notifications.filter(item=>!item.read).length;
  function select(p:Product){setSelected(p);setVariant(p.variants[0])}
  async function favorite(p:Product){await act({type:'favorite',id:p.id})}
  async function add(){if(!selected||adding)return;setAdding(true);const ok=await act({type:'cart-add',product:selected,variant});setAdding(false);if(ok){setSelected(null);toast.success('Товар добавлен в корзину',{action:{label:'Открыть',onClick:()=>navigate('/cart')}})}}
  return <><Toaster position="top-right" richColors/><div className="utility-bar"><span><Globe2 size={14}/> Весь мир <ArrowRight size={12}/> Узбекистан</span><span>Предрелиз · внешние операции в тестовом режиме</span><span className="desktop-only"><MapPin size={14}/> Ташкент</span></div>
  <header className="site-header"><Link className="wordmark" href="/" aria-label="Atlas — главная">atlas<ArrowUpRight/></Link><nav className="desktop-nav" aria-label="Основное меню">{[['/','catalog','Каталог'],['/order-by-link','link','Заказ по ссылке'],['/orders','orders','Мои заказы']].map(([href,key,label])=><Link key={key} className={key===view?'active':''} href={href}>{label}{key==='link'&&<ArrowUpRight size={14}/>}</Link>)}</nav><div className="header-actions"><Link className="text-link" href="/account">{user?'Кабинет':'Войти'}</Link><Link href="/balance" className="wallet-link"><Wallet size={19}/><span>{money(balance)}</span></Link><Link aria-label={'Уведомления, непрочитанных: '+unread} href="/notifications" className={'icon-btn notice-link '+(view==='notifications'?'active':'')}><Bell size={20}/>{unread>0&&<b>{Math.min(unread,99)}</b>}</Link><Link aria-label="Избранное" href="/favorites" className={'icon-btn desktop-only '+(view==='favorites'?'active':'')}><Heart size={20}/></Link><Link href="/cart" className="cart-link" aria-label={'Корзина, товаров: '+count}><ShoppingBag size={19}/><span className="desktop-only">Корзина</span><b>{count}</b></Link></div></header>
  <main className="site-main" id="main"><div className="breadcrumb"><Link href="/">Главная</Link><span>/</span><span>{titles[view]}</span></div>{error&&<div className="notice error account-error" role="alert"><span>{error}</span><div><button type="button" className="text-button" onClick={()=>void refresh()}>Повторить</button>{!user&&<Link className="text-link" href="/account">Открыть вход<ArrowRight size={15}/></Link>}</div></div>}
  {(view==='catalog'||view==='favorites')&&<Catalog favorites={view==='favorites'} select={select} toggleFavorite={favorite}/>}
  {view==='link'&&<GlobalLinkOrder select={select}/>}{view==='cart'&&<CartView/>}{(view==='orders'||view==='operations')&&<OrdersView operations={view==='operations'}/>}{view==='balance'&&<BalanceView/>}{view==='notifications'&&<NotificationsView/>}{view==='account'&&<AccountView/>}{view==='customs'&&<CustomsView/>}{view==='analytics'&&<AnalyticsView/>}{view==='legal'&&<LegalView/>}
  <footer className="site-footer"><div><Link className="wordmark" href="/">atlas<ArrowUpRight/></Link><p>Покупки из мира — к вам.</p></div><div><Link href="/order-by-link">Заказ по ссылке</Link><Link href="/orders">Мои заказы</Link><Link href="/account">Личный кабинет</Link><Link href="/legal">Правила Atlas</Link><Link href="/customs">Таможенные условия</Link>{user?.operator&&<><Link href="/operations"><Settings2 size={14}/> Кабинет оператора</Link><Link href="/analytics"><BarChart3 size={14}/> Аналитика</Link></>}</div><small>Предрелизная версия.<br/>Реальных списаний и отправок нет.</small></footer></main>
  <nav className="mobile-nav" aria-label="Мобильное меню">{[['/','catalog',LayoutGrid,'Каталог'],['/favorites','favorites',Heart,'Избранное'],['/order-by-link','link',Link2,'Ссылка'],['/orders','orders',Package,'Заказы'],['/cart','cart',ShoppingBag,'Корзина']].map(([href,key,Icon,label])=>{const I=Icon as typeof LayoutGrid;return <Link href={href as string} key={key as string} className={key===view?'active':''}><I size={21}/><span>{label as string}</span>{key==='cart'&&count>0&&<b>{count}</b>}</Link>})}</nav>
  <Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><SheetContent showCloseButton={false} className="product-sheet"><SheetClose asChild><button className="icon-btn sheet-close" aria-label="Закрыть карточку"><X size={20}/></button></SheetClose>{selected&&<><div className={'detail-image detail-'+selected.id}><ProductImage product={selected}/><span className="floating-label">{selected.sourceUrl?countryName(selected):'Пример товара'}</span></div><div className="sheet-body"><div className="eyebrow">{selected.brand.includes(countryName(selected))?selected.brand:selected.brand+' · '+countryName(selected)}</div><SheetTitle className="product-title">{selected.name}</SheetTitle><SheetDescription>{selected.sourceUrl?'Данные магазина требуют проверки: выберите нужный вариант и подтвердите стоимость.':'Фото иллюстративное. Цена, варианты и наличие демонстрационные.'}</SheetDescription><Tabs defaultValue="about" className="detail-tabs"><TabsList variant="line"><TabsTrigger value="about">О товаре</TabsTrigger><TabsTrigger value="price">Расчёт стоимости</TabsTrigger></TabsList><TabsContent value="about"><p>{selected.description??'Товар по вашей ссылке. Данные введены вручную и требуют проверки перед реальным выкупом.'}</p>{selected.sourceUrl&&<a className="text-link" href={selected.sourceUrl} target="_blank" rel="noopener noreferrer">Открыть источник<ArrowUpRight size={16}/></a>}<div className="product-facts"><span>Цена в магазине <b>{selected.sourcePrice??selected.usd} {selected.sourceCurrency??'USD'}</b></span><span>Расчётный вес <b>{selected.weight} кг</b>{selected.boxedWeight!==undefined&&<small>С коробкой {selected.boxedWeight} + 0,3 + 0,2 кг</small>}</span></div></TabsContent><TabsContent value="price"><CostLines q={price(selected.usd,selected.weight,1,selected.sourceShippingUsd??0,pricing)}/><small className="muted">Курс расчёта: {money(pricing.fx)} / USD · {pricing.version}</small></TabsContent></Tabs><div className="field"><label>Вариант товара</label><Choice label="Вариант товара" value={variant} onChange={setVariant} options={selected.variants}/></div><div className="notice"><ShieldCheck size={19}/><span>Остаток доставки вернётся после взвешивания. Доплату выше резерва согласуем отдельно.</span></div><div className="sheet-total"><span>С доставкой и резервом<strong>{money(price(selected.usd,selected.weight,1,selected.sourceShippingUsd??0,pricing).total)}</strong></span><button className="btn primary" disabled={!ready||adding} onClick={add}><ShoppingBag size={18}/>{adding?'Добавляем…':'В корзину'}</button></div><p className="micro">Таможенные расходы и сроки пока не рассчитаны.</p></div></>}</SheetContent></Sheet></>;
}
function Catalog({favorites,select,toggleFavorite}:{favorites:boolean;select:(p:Product)=>void;toggleFavorite:(p:Product)=>void}){
  const {state,pricing,ready}=useMarket();const [search,setSearch]=useState(''),[category,setCategory]=useState('Все товары'),[sort,setSort]=useState('Рекомендуем'),[url,setUrl]=useState(''),[filterCountry,setFilterCountry]=useState('Все страны');
  const list=products.filter(p=>(filterCountry==='Все страны'||countryName(p)===filterCountry)&&(!favorites||state.favorites.includes(p.id))&&(category==='Все товары'||p.category===category)&&`${p.name} ${p.brand}`.toLowerCase().includes(search.toLowerCase().trim())).sort((a,b)=>sort==='Сначала дешевле'?price(a.usd,a.weight,1,0,pricing).total-price(b.usd,b.weight,1,0,pricing).total:sort==='Сначала дороже'?price(b.usd,b.weight,1,0,pricing).total-price(a.usd,a.weight,1,0,pricing).total:0);
  return <><PageHeading overline={favorites?'СОХРАНЕНО ДЛЯ ВАС':'ПОКУПКИ БЕЗ ГРАНИЦ'} title={favorites?'Ваши будущие находки.':'Весь мир. В вашей корзине.'} description={favorites?'Сохранённые товары, к которым хочется вернуться.':'Выбирайте товары со всего мира. Считайте доставку в сумах.'}>{!favorites&&<div className="route-stamp"><span>WORLD</span><ArrowRight size={21}/><span>UZ</span><small>Один заказ · весь путь</small></div>}</PageHeading>
  {!favorites&&<section className="import-strip"><div><span className="strip-icon"><Link2 size={24}/></span><div><h2>Уже нашли свой товар?</h2><p>Начните с ссылки на страницу магазина.</p></div></div><form onSubmit={e=>{e.preventDefault();try{navigate('/order-by-link?url='+encodeURIComponent(validateSource(url)))}catch(e){toast.error((e as Error).message)}}}><input type="url" required aria-label="Ссылка на товар" placeholder="Вставьте ссылку на товар" value={url} onChange={e=>setUrl(e.target.value)}/><button className="btn light">Рассчитать <ArrowUpRight size={19}/></button></form></section>}
  <div className="catalog-toolbar"><div><h2>{favorites?'Избранное':'Подборка для первого заказа'}</h2><p>{favorites?'Сохраняйте понравившееся сердечком.':'Примеры для знакомства с сервисом. Любой свой товар добавьте по ссылке.'}</p></div><Choice label="Сортировка товаров" value={sort} onChange={setSort} options={['Рекомендуем','Сначала дешевле','Сначала дороже']}/></div>
  <div className="catalog-filters"><div className="category-list">{['Все товары','Обувь','Электроника','Аксессуары'].map(c=><button key={c} aria-pressed={c===category} className={c===category?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="search-field"><Search size={18}/><input aria-label="Поиск товаров" placeholder="Поиск в подборке" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button className="icon-btn" aria-label="Очистить поиск" onClick={()=>setSearch('')}><X size={16}/></button>}</div></div>
  <div className="country-filter"><Choice label="Страна каталога" value={filterCountry} onChange={setFilterCountry} options={['Все страны',...Array.from(new Set(products.map(countryName)))]}/></div><div className="results-count" aria-live="polite">{list.length} из {favorites?state.favorites.length:products.length} товаров</div>
  <section className="catalog-grid">{list.map(p=><article className="product-card" key={p.id}><div className={'card-photo card-'+p.id}><button className="photo-button" onClick={()=>select(p)} aria-label={'Подробнее: '+p.name}><ProductImage product={p}/></button><span className="floating-label">{p.category}</span><button aria-pressed={state.favorites.includes(p.id)} aria-label={(state.favorites.includes(p.id)?'Убрать из избранного: ':'В избранное: ')+p.name} disabled={!ready} className={'favorite-btn '+(state.favorites.includes(p.id)?'is-favorite':'')} onClick={()=>toggleFavorite(p)}><Heart size={19}/></button></div><div className="card-content"><div className="card-meta"><span>{countryName(p)} · {p.category}</span><span>Демо</span></div><button className="product-name" onClick={()=>select(p)}>{p.name}</button><div className="card-price"><div><strong>{money(price(p.usd,p.weight,1,0,pricing).total)}</strong><p>С доставкой и резервом</p></div><button className="card-add" onClick={()=>select(p)} aria-label={'Выбрать вариант '+p.name}><Plus size={21}/></button></div></div></article>)}</section>
  {!list.length&&<Empty title={favorites&&!state.favorites.length?'Здесь будут ваши находки':'Ничего не найдено'} description={favorites&&!state.favorites.length?'Нажмите на сердечко у товара в каталоге.':'Измените запрос или выберите другую категорию.'} href={favorites&&!state.favorites.length?'/':undefined}>{(!favorites||!!state.favorites.length)&&<button className="btn secondary" onClick={()=>{setSearch('');setCategory('Все товары');setFilterCountry('Все страны')}}>Сбросить фильтры</button>}</Empty>}
  {!favorites&&<section className="trust-strip"><div><ShieldCheck/><h3>Стоимость перед вами</h3><p>Товар, сервис, доставка и резерв — отдельными строками.</p></div><div><Package/><h3>Каждый этап на виду</h3><p>Выкуп, склад, отправка и получение — в вашем заказе.</p></div><div><Wallet/><h3>Остаток возвращается</h3><p>После взвешивания пересчитываем доставку и возвращаем разницу.</p></div></section>}</>;
}
