import { isUzbek, type Locale } from "./i18n.ts";
import { uzText, withCyrillic } from "./uz-cyrl.ts";

/** Plural of "item" (товар) for a count. */
function itemsWord(count: number, locale: Locale) {
  if (isUzbek(locale)) return uzText(locale, "ta tovar");
  if (locale === "en") return count === 1 ? "item" : "items";
  const tens = count % 100, ones = count % 10;
  if (tens >= 11 && tens <= 14) return "товаров";
  if (ones === 1) return "товар";
  if (ones >= 2 && ones <= 4) return "товара";
  return "товаров";
}

/**
 * Cart checkboxes and the checkout review (owner, 7.10.2026): the customer ticks what to check out now, the rest
 * stays in the cart; the review lists the order as a numbered table grouped by store and model.
 */
export const cartSelectCopy = /*@__PURE__*/withCyrillic({
  ru: {
    selectAll: "Выбрать все",
    selectStore: (store: string) => `Выбрать все товары ${store}`,
    selectGroup: (name: string) => `Выбрать все варианты: ${name}`,
    selectLine: (name: string) => `Оформить сейчас: ${name}`,
    checkoutN: (count: number) => `Оформить ${count} ${itemsWord(count, "ru")}`,
    selectedOf: (selected: number, all: number) => `Выбрано ${selected} из ${all}`,
    noneSelected: "Выберите товары для оформления",
    later: "Останется в корзине",
    laterCount: (count: number) => count % 10 === 1 && count % 100 !== 11 ? `${count} ${itemsWord(count, "ru")} останется в корзине — его можно оформить позже.` : `${count} ${itemsWord(count, "ru")} останутся в корзине — их можно оформить позже.`,
    leaveForLater: "Оставить на потом",
    saving: "Сохраняем…",
    parcelServices: "Услуги для посылки",
    parcelServicesHint: "Выбираются один раз на посылку магазина, а не для каждого размера.",
    unitPackage: "на посылку",
    unitItem: (count: number) => `на ${count} ${itemsWord(count, "ru")}`,
    unitPhoto: (count: number) => `${count} фото`,
    review: {
      columns: { item: "Товар", variant: "Вариант", quantity: "Кол-во", price: "Цена", sum: "Сумма" },
      parcel: (store: string, country: string) => `${store} · ${country}`,
      checks: "Перед подтверждением",
      variants: "Варианты и количество",
      variantsValue: (lines: number, pieces: number) => `${lines} поз. · ${pieces} шт.`,
      recipient: "Получатель и адрес",
      speed: "Скорость доставки",
      services: "Комментарии и услуги",
      servicesNone: "Без услуг и комментариев",
      servicesValue: (services: number, notes: number) => [services ? `услуг: ${services}` : "", notes ? `комментариев: ${notes}` : ""].filter(Boolean).join(" · "),
      customs: "Таможня",
      customsHelp: "Atlas оплачивает пошлину за вас",
      customsSelf: "Пошлину при необходимости оплачиваете сами",
      total: "Итог и резервы",
      held: "Отдельно удерживается",
      change: "Изменить",
      lineChanged: "Цена изменилась — проверьте новую сумму",
      lineIssue: "Магазин изменил данные — загрузите товар заново",
      services_: "Услуги",
      note: "Комментарий",
    },
  },
  uz: {
    selectAll: "Hammasini tanlash",
    selectStore: (store: string) => `${store} tovarlarini tanlash`,
    selectGroup: (name: string) => `Barcha variantlar: ${name}`,
    selectLine: (name: string) => `Hozir rasmiylashtirish: ${name}`,
    checkoutN: (count: number) => `${count} ${itemsWord(count, "uz")}ni rasmiylashtirish`,
    selectedOf: (selected: number, all: number) => `${all} tadan ${selected} tasi tanlandi`,
    noneSelected: "Rasmiylashtirish uchun tovarlarni tanlang",
    later: "Savatda qoladi",
    laterCount: (count: number) => `${count} ${itemsWord(count, "uz")} savatda qoladi — ${count === 1 ? "uni" : "ularni"} keyinroq rasmiylashtirish mumkin.`,
    leaveForLater: "Keyinga qoldirish",
    saving: "Saqlanmoqda…",
    parcelServices: "Posilka uchun xizmatlar",
    parcelServicesHint: "Do‘kon posilkasi uchun bir marta tanlanadi, har bir o‘lcham uchun emas.",
    unitPackage: "posilkaga",
    unitItem: (count: number) => `${count} ${itemsWord(count, "uz")}ga`,
    unitPhoto: (count: number) => `${count} ta foto`,
    review: {
      columns: { item: "Tovar", variant: "Variant", quantity: "Soni", price: "Narx", sum: "Summa" },
      parcel: (store: string, country: string) => `${store} · ${country}`,
      checks: "Tasdiqlashdan oldin",
      variants: "Variantlar va soni",
      variantsValue: (lines: number, pieces: number) => `${lines} pozitsiya · ${pieces} dona`,
      recipient: "Qabul qiluvchi va manzil",
      speed: "Yetkazish tezligi",
      services: "Izohlar va xizmatlar",
      servicesNone: "Xizmat va izohlarsiz",
      servicesValue: (services: number, notes: number) => [services ? `xizmatlar: ${services}` : "", notes ? `izohlar: ${notes}` : ""].filter(Boolean).join(" · "),
      customs: "Bojxona",
      customsHelp: "Bojni Atlas siz uchun to‘laydi",
      customsSelf: "Kerak bo‘lsa, bojni o‘zingiz to‘laysiz",
      total: "Jami va rezervlar",
      held: "Alohida ushlab turiladi",
      change: "O‘zgartirish",
      lineChanged: "Narx o‘zgardi — yangi summani tekshiring",
      lineIssue: "Do‘kon ma’lumotlarni o‘zgartirdi — tovarni qayta yuklang",
      services_: "Xizmatlar",
      note: "Izoh",
    },
  },
  en: {
    selectAll: "Select all",
    selectStore: (store: string) => `Select all items from ${store}`,
    selectGroup: (name: string) => `Select all options: ${name}`,
    selectLine: (name: string) => `Check out now: ${name}`,
    checkoutN: (count: number) => `Check out ${count} ${itemsWord(count, "en")}`,
    selectedOf: (selected: number, all: number) => `${selected} of ${all} selected`,
    noneSelected: "Select the items to check out",
    later: "Stays in the cart",
    laterCount: (count: number) => `${count} ${itemsWord(count, "en")} will stay in the cart — you can check ${count === 1 ? "it" : "them"} out later.`,
    leaveForLater: "Leave for later",
    saving: "Saving…",
    parcelServices: "Parcel services",
    parcelServicesHint: "Chosen once per store parcel, not for every size.",
    unitPackage: "per parcel",
    unitItem: (count: number) => `for ${count} ${itemsWord(count, "en")}`,
    unitPhoto: (count: number) => `${count} photos`,
    review: {
      columns: { item: "Item", variant: "Option", quantity: "Qty", price: "Price", sum: "Amount" },
      parcel: (store: string, country: string) => `${store} · ${country}`,
      checks: "Before you confirm",
      variants: "Options and quantity",
      variantsValue: (lines: number, pieces: number) => `${lines} lines · ${pieces} pcs`,
      recipient: "Recipient and address",
      speed: "Delivery speed",
      services: "Notes and services",
      servicesNone: "No services or notes",
      servicesValue: (services: number, notes: number) => [services ? `services: ${services}` : "", notes ? `notes: ${notes}` : ""].filter(Boolean).join(" · "),
      customs: "Customs",
      customsHelp: "Atlas pays the duty for you",
      customsSelf: "You pay any duty yourself",
      total: "Total and holds",
      held: "Held separately",
      change: "Change",
      lineChanged: "The price changed — check the new amount",
      lineIssue: "The store changed this item — load it again",
      services_: "Services",
      note: "Note",
    },
  },
});
export type CartSelectCopy = (typeof cartSelectCopy)["ru"];
