import type { Locale } from './i18n';

const ru = {
  title: 'Каталог зарубежных товаров.', intro: 'Обычные товары и лучшие скидки — в одном месте, с расчётом доставки в Узбекистан.',
  overline: 'КАТАЛОГ ATLAS', savedTitle: 'Избранные товары.', savedIntro: 'Сравните цены и вернитесь к покупке, когда будете готовы.',
  observed: 'Цена на', checkOptions: 'Atlas перепроверит цену и выбранный вариант', priceNote: 'Цены зафиксированы на указанную дату и могут измениться. Atlas сверит цену и валюту выбранного варианта при добавлении. Atlas не является официальным представителем указанных брендов.', estimateHint: 'Вес оценочный. Итог рассчитан по настроенным тарифам Atlas, не является офертой и уточняется до выкупа.',
  all: 'Все категории', footwear: 'Обувь', clothing: 'Одежда', electronics: 'Электроника', accessories: 'Аксессуары',
  search: 'Поиск по каталогу', searchPlaceholder: 'Товар, магазин, категория или страна', clear: 'Очистить поиск',
  country: 'Страна', allCountries: 'Все страны', us: 'США', de: 'Германия', es: 'Испания',
  budget: 'Бюджет с доставкой', anyBudget: 'Любой бюджет', budget1: 'До 1 млн сум', budget15: 'До 1,5 млн сум', budget2: 'До 2 млн сум',
  sort: 'Сортировка', discountSort: 'Больше скидка на товар', lowSort: 'Дешевле с доставкой', highSort: 'Дороже с доставкой',
  reset: 'Сбросить фильтры', results: 'Найдено', saved: 'Избранное', catalog: 'Каталог', topDeal: 'Топ-цена',
  discountLabel: 'в магазине', productPrice: 'Цена магазина, USD', referenceLabel: 'Базовая цена, указанная магазином', saving: 'Разница в цене товара',
  delivered: 'Предварительно с доставкой', excluded: 'Таможенные платежи не включены', breakdown: 'Из чего складывается цена',
  merchandise: 'Товар', service: 'Выкуп и сервис', merchantShipping: 'Доставка магазина', international: 'Международная доставка', reserve: 'Возвратный резерв',
  unknownShipping: 'На доставку магазина заложен резерв $10. Фактическая сумма уточняется отдельно.',
  buy: 'Добавить в корзину', variants: 'Вариантов', save: 'Сохранить', remove: 'Убрать из избранного', savingState: 'Сохраняем', signin: 'Войдите, чтобы сохранять товары',
  compareHint: 'Скидка относится только к цене товара в USD. Итог ниже включает сервис, доставку и резерв.',
  empty: 'Таких товаров пока нет', emptyHint: 'Увеличьте бюджет или уберите один из фильтров.', emptySaved: 'Сохраните первый товар', emptySavedHint: 'Нажмите на сердечко у товара — он появится здесь.',
  linkTitle: 'Уже нашли товар в другом магазине?', linkHint: 'Вставьте свою ссылку — рассчитайте покупку через Atlas.', linkLabel: 'Ссылка на товар', calculate: 'Рассчитать', signInToCalculate: 'Войти и рассчитать', signInToCalculateHint: 'Расчёт и выбранный товар сохранятся в вашем кабинете.', batch: 'Добавить несколько ссылок',
  stepsTitle: 'Всего три шага', step1: 'Выберите товар', step1hint: 'В каталоге или по ссылке из магазина.', step2: 'Укажите адрес', step2hint: 'Выберите получателя или добавьте нового.', step3: 'Подтвердите заказ', step3hint: 'Проверьте итог и подтвердите оформление.', step4: 'Следите за статусом', step4hint: 'Все обновления появятся в кабинете.', stepsNote: 'Платёжный провайдер и доставка пока не подключены: списания и отправки не выполняются.',
  sourceMissing: 'Источник магазина ещё не подключён', sourceOpen: 'Страница магазина',
  shoeName: 'Кроссовки на каждый день', audioName: 'Беспроводные наушники', bagName: 'Городской рюкзак',
};
type Copy = { [K in keyof typeof ru]: string };
const uz: Copy = {
  title: 'Xorijiy mahsulotlar katalogi.', intro: 'Oddiy mahsulotlar va eng yaxshi chegirmalar — O‘zbekistonga yetkazish hisobi bilan bir joyda.',
  overline: 'ATLAS KATALOGI', savedTitle: 'Saralangan mahsulotlar.', savedIntro: 'Narxlarni solishtiring va tayyor bo‘lganingizda xaridga qayting.',
  observed: 'Narx sanasi', checkOptions: 'Atlas narx va tanlangan variantni qayta tekshiradi', priceNote: 'Narxlar ko‘rsatilgan sanada qayd etilgan va o‘zgarishi mumkin. Savatga qo‘shishda Atlas tanlangan variant narxi va valyutasini tekshiradi. Atlas ushbu brendlarning rasmiy vakili emas.', estimateHint: 'Vazn taxminiy. Jami Atlas tariflari asosida hisoblangan, oferta emas va xariddan oldin aniqlashtiriladi.',
  all: 'Barcha toifalar', footwear: 'Poyabzal', clothing: 'Kiyim', electronics: 'Elektronika', accessories: 'Aksessuarlar',
  search: 'Katalogdan qidirish', searchPlaceholder: 'Mahsulot, do‘kon, toifa yoki mamlakat', clear: 'Qidiruvni tozalash',
  country: 'Mamlakat', allCountries: 'Barcha mamlakatlar', us: 'AQSH', de: 'Germaniya', es: 'Ispaniya',
  budget: 'Yetkazish bilan budjet', anyBudget: 'Istalgan budjet', budget1: '1 mln so‘mgacha', budget15: '1,5 mln so‘mgacha', budget2: '2 mln so‘mgacha',
  sort: 'Saralash', discountSort: 'Kattaroq mahsulot chegirmasi', lowSort: 'Yetkazish bilan arzonroq', highSort: 'Yetkazish bilan qimmatroq',
  reset: 'Filtrlarni tozalash', results: 'Topildi', saved: 'Saralangan', catalog: 'Katalog', topDeal: 'Top narx',
  discountLabel: 'do‘konda', productPrice: 'Do‘kon narxi, USD', referenceLabel: 'Do‘kon ko‘rsatgan asosiy narx', saving: 'Mahsulot narxidagi farq',
  delivered: 'Yetkazish bilan taxminiy jami', excluded: 'Bojxona to‘lovlari kiritilmagan', breakdown: 'Narx tarkibi',
  merchandise: 'Mahsulot', service: 'Sotib olish va xizmat', merchantShipping: 'Do‘kondan yetkazish', international: 'Xalqaro yetkazish', reserve: 'Qaytariladigan zaxira',
  unknownShipping: 'Do‘kondan yetkazish uchun $10 zaxira kiritilgan. Haqiqiy summa alohida aniqlashtiriladi.',
  buy: 'Savatga qo‘shish', variants: 'Variantlar', save: 'Saqlash', remove: 'Saralanganlardan olib tashlash', savingState: 'Saqlanmoqda', signin: 'Mahsulotlarni saqlash uchun kiring',
  compareHint: 'Chegirma faqat mahsulotning USD narxiga tegishli. Quyidagi jami xizmat, yetkazish va zaxirani o‘z ichiga oladi.',
  empty: 'Bunday mahsulotlar hozircha yo‘q', emptyHint: 'Budjetni oshiring yoki filtrlardan birini olib tashlang.', emptySaved: 'Birinchi mahsulotni saqlang', emptySavedHint: 'Mahsulot yonidagi yurakchani bosing — u shu yerda paydo bo‘ladi.',
  linkTitle: 'Boshqa do‘konda mahsulot topdingizmi?', linkHint: 'Havolani joylang va Atlas orqali xaridni hisoblang.', linkLabel: 'Mahsulot havolasi', calculate: 'Hisoblash', signInToCalculate: 'Kirish va hisoblash', signInToCalculateHint: 'Hisob va tanlangan mahsulot kabinetingizda saqlanadi.', batch: 'Bir nechta havola qo‘shish',
  stepsTitle: 'Atigi uch qadam', step1: 'Tovarni tanlang', step1hint: 'Katalogdan yoki do‘kon havolasi orqali.', step2: 'Manzilni kiriting', step2hint: 'Qabul qiluvchini tanlang yoki yangisini qo‘shing.', step3: 'Buyurtmani tasdiqlang', step3hint: 'Jami hisobni ko‘rib, rasmiylashtirishni tasdiqlang.', step4: 'Holatni kuzating', step4hint: 'Barcha yangilanishlar kabinetda ko‘rinadi.', stepsNote: 'To‘lov provayderi va yetkazish hali ulanmagan: pul yechilmaydi va jo‘natmalar yuborilmaydi.',
  sourceMissing: 'Do‘kon manbasi hali ulanmagan', sourceOpen: 'Do‘kon sahifasi',
  shoeName: 'Kundalik krossovkalar', audioName: 'Simsiz quloqchinlar', bagName: 'Shahar ryukzagi',
};
const en: Copy = {
  title: 'International product catalog.', intro: 'Everyday products and the best discounts in one place, with delivery estimates to Uzbekistan.',
  overline: 'ATLAS CATALOG', savedTitle: 'Saved products.', savedIntro: 'Compare prices and come back when you’re ready to buy.',
  observed: 'Price recorded', checkOptions: 'Atlas rechecks price and selected option', priceNote: 'Prices were recorded on the stated date and may change. Atlas checks the selected option’s price and currency when it is added. Atlas is not an official representative of these brands.', estimateHint: 'Weight is estimated. Totals use configured Atlas rates, are not a binding offer and must be confirmed before purchase.',
  all: 'All categories', footwear: 'Footwear', clothing: 'Clothing', electronics: 'Electronics', accessories: 'Accessories',
  search: 'Search catalog', searchPlaceholder: 'Product, store, category or country', clear: 'Clear search',
  country: 'Country', allCountries: 'All countries', us: 'USA', de: 'Germany', es: 'Spain',
  budget: 'Budget including delivery', anyBudget: 'Any budget', budget1: 'Under 1m UZS', budget15: 'Under 1.5m UZS', budget2: 'Under 2m UZS',
  sort: 'Sort', discountSort: 'Largest product discount', lowSort: 'Lowest delivered cost', highSort: 'Highest delivered cost',
  reset: 'Reset filters', results: 'Found', saved: 'Saved', catalog: 'Catalog', topDeal: 'Top price',
  discountLabel: 'at the store', productPrice: 'Store price, USD', referenceLabel: 'Base price shown by the store', saving: 'Product price difference',
  delivered: 'Estimated total with delivery', excluded: 'Customs charges not included', breakdown: 'Price breakdown',
  merchandise: 'Product', service: 'Purchasing and service', merchantShipping: 'Store delivery', international: 'International delivery', reserve: 'Refundable reserve',
  unknownShipping: 'A $10 reserve covers unconfirmed store delivery. The actual amount is checked separately.',
  buy: 'Add to cart', variants: 'Options', save: 'Save', remove: 'Remove from saved', savingState: 'Saving', signin: 'Sign in to save products',
  compareHint: 'The discount applies only to the product price in USD. The total below includes service, delivery and reserve.',
  empty: 'No matching products yet', emptyHint: 'Increase your budget or remove a filter.', emptySaved: 'Save your first product', emptySavedHint: 'Tap the heart on a product and it will appear here.',
  linkTitle: 'Found something in another store?', linkHint: 'Paste your link to calculate a purchase through Atlas.', linkLabel: 'Product link', calculate: 'Calculate', signInToCalculate: 'Sign in to calculate', signInToCalculateHint: 'Your calculation and selected item will be saved in your account.', batch: 'Add multiple links',
  stepsTitle: 'Just three steps', step1: 'Choose a product', step1hint: 'Pick from the catalog or paste a store link.', step2: 'Enter your address', step2hint: 'Choose a recipient or add a new one.', step3: 'Confirm your order', step3hint: 'Review the total and confirm checkout.', step4: 'Follow the status', step4hint: 'Updates will appear in your account.', stepsNote: 'A payment provider and delivery integration are not connected yet; no charges or shipments are made.',
  sourceMissing: 'Store source not connected yet', sourceOpen: 'Store page',
  shoeName: 'Everyday sneakers', audioName: 'Wireless headphones', bagName: 'City backpack',
};
export const dealCopy = (locale: Locale): Copy => ({
  ...({ ru, uz, en })[locale],
  stepsNote: {
    ru: 'Платёжный провайдер и доставка пока не подключены: списания и отправки не выполняются.',
    uz: 'To‘lov provayderi va yetkazish hali ulanmagan: pul yechilmaydi va jo‘natmalar yuborilmaydi.',
    en: 'A payment provider and delivery integration are not connected yet; no charges or shipments are made.',
  }[locale],
});
