import type { Locale } from './i18n';

const ru = {
  title: 'Находки, которые стоят внимания.', intro: 'Выбирайте по выгоде. Сравнивайте с учётом доставки в Узбекистан.',
  overline: 'ATLAS FINDS', savedTitle: 'Ваши сохранённые находки.', savedIntro: 'Сравните цены и вернитесь к покупке, когда будете готовы.',
  demo: 'Демонстрационная подборка', demoHint: 'Товары, скидки и варианты — примеры. Актуальные предложения магазинов ещё не подключены.',
  all: 'Все категории', footwear: 'Обувь', electronics: 'Электроника', accessories: 'Аксессуары',
  search: 'Поиск находок', searchPlaceholder: 'Товар, категория или страна', clear: 'Очистить поиск',
  country: 'Страна', allCountries: 'Все страны', us: 'США', de: 'Германия', es: 'Испания',
  budget: 'Бюджет с доставкой', anyBudget: 'Любой бюджет', budget1: 'До 1 млн сум', budget15: 'До 1,5 млн сум', budget2: 'До 2 млн сум',
  sort: 'Сортировка', discountSort: 'Больше скидка на товар', lowSort: 'Дешевле с доставкой', highSort: 'Дороже с доставкой',
  reset: 'Сбросить фильтры', results: 'Найдено', saved: 'Избранное', catalog: 'Все находки',
  demoBadge: 'Пример скидки', demoItem: 'Демо-товар', productPrice: 'Товар, USD', before: 'Пример до скидки', saving: 'Разница в цене товара',
  delivered: 'Предварительно с доставкой', excluded: 'Таможенные платежи не включены', breakdown: 'Из чего складывается цена',
  merchandise: 'Товар', service: 'Выкуп и сервис', merchantShipping: 'Доставка магазина', international: 'Международная доставка', reserve: 'Возвратный резерв',
  zeroShipping: '0 сум в этом примере', unknownShipping: 'Неизвестная доставка требует отдельного резерва. Здесь показан учебный расчёт.',
  buy: 'Выбрать вариант', variants: 'Вариантов', save: 'Сохранить', remove: 'Убрать из избранного', savingState: 'Сохраняем', signin: 'Войдите, чтобы сохранять находки',
  compareHint: 'Скидка относится только к цене товара в USD. Итог ниже включает сервис, доставку и резерв.',
  empty: 'Таких находок пока нет', emptyHint: 'Увеличьте бюджет или уберите один из фильтров.', emptySaved: 'Сохраните первую находку', emptySavedHint: 'Нажмите на сердечко у товара — он появится здесь.',
  linkTitle: 'Уже нашли товар в другом магазине?', linkHint: 'Вставьте свою ссылку — рассчитайте покупку через Atlas.', linkLabel: 'Ссылка на товар', calculate: 'Рассчитать', batch: 'Добавить несколько ссылок',
  stepsTitle: 'От находки до вашего заказа', step1: 'Выберите товар', step1hint: 'Посмотрите варианты и предварительный итог.', step2: 'Проверьте расчёт', step2hint: 'Все расходы видны отдельными строками.', step3: 'Подтвердите', step3hint: 'Укажите получателя и проверьте данные.', step4: 'Следите за заказом', step4hint: 'Изменения и согласования — в кабинете.',
  sourceMissing: 'Источник магазина ещё не подключён', sourceOpen: 'Страница магазина',
  shoeName: 'Кроссовки на каждый день', audioName: 'Беспроводные наушники', bagName: 'Городской рюкзак',
};
type Copy = { [K in keyof typeof ru]: string };
const uz: Copy = {
  title: 'E’tiborga loyiq topilmalar.', intro: 'Foydali takliflarni O‘zbekistonga yetkazish xarajati bilan solishtiring.',
  overline: 'ATLAS FINDS', savedTitle: 'Saqlangan topilmalaringiz.', savedIntro: 'Narxlarni solishtiring va tayyor bo‘lganingizda xaridga qayting.',
  demo: 'Namuna to‘plami', demoHint: 'Mahsulotlar, chegirmalar va variantlar — namunalar. Do‘konlarning joriy takliflari hali ulanmagan.',
  all: 'Barcha toifalar', footwear: 'Poyabzal', electronics: 'Elektronika', accessories: 'Aksessuarlar',
  search: 'Topilmalarni qidirish', searchPlaceholder: 'Mahsulot, toifa yoki mamlakat', clear: 'Qidiruvni tozalash',
  country: 'Mamlakat', allCountries: 'Barcha mamlakatlar', us: 'AQSH', de: 'Germaniya', es: 'Ispaniya',
  budget: 'Yetkazish bilan budjet', anyBudget: 'Istalgan budjet', budget1: '1 mln so‘mgacha', budget15: '1,5 mln so‘mgacha', budget2: '2 mln so‘mgacha',
  sort: 'Saralash', discountSort: 'Kattaroq mahsulot chegirmasi', lowSort: 'Yetkazish bilan arzonroq', highSort: 'Yetkazish bilan qimmatroq',
  reset: 'Filtrlarni tozalash', results: 'Topildi', saved: 'Saralangan', catalog: 'Barcha topilmalar',
  demoBadge: 'Chegirma namunasi', demoItem: 'Namuna mahsulot', productPrice: 'Mahsulot, USD', before: 'Chegirmagacha namuna narx', saving: 'Mahsulot narxidagi farq',
  delivered: 'Yetkazish bilan taxminiy jami', excluded: 'Bojxona to‘lovlari kiritilmagan', breakdown: 'Narx tarkibi',
  merchandise: 'Mahsulot', service: 'Sotib olish va xizmat', merchantShipping: 'Do‘kondan yetkazish', international: 'Xalqaro yetkazish', reserve: 'Qaytariladigan zaxira',
  zeroShipping: 'Ushbu misolda 0 so‘m', unknownShipping: 'Noma’lum yetkazish narxi alohida zaxirani talab qiladi. Bu yerda namuna hisob ko‘rsatilgan.',
  buy: 'Variantni tanlash', variants: 'Variantlar', save: 'Saqlash', remove: 'Saralanganlardan olib tashlash', savingState: 'Saqlanmoqda', signin: 'Topilmalarni saqlash uchun kiring',
  compareHint: 'Chegirma faqat mahsulotning USD narxiga tegishli. Quyidagi jami xizmat, yetkazish va zaxirani o‘z ichiga oladi.',
  empty: 'Bunday topilmalar hozircha yo‘q', emptyHint: 'Budjetni oshiring yoki filtrlardan birini olib tashlang.', emptySaved: 'Birinchi topilmani saqlang', emptySavedHint: 'Mahsulot yonidagi yurakchani bosing — u shu yerda paydo bo‘ladi.',
  linkTitle: 'Boshqa do‘konda mahsulot topdingizmi?', linkHint: 'Havolani joylang va Atlas orqali xaridni hisoblang.', linkLabel: 'Mahsulot havolasi', calculate: 'Hisoblash', batch: 'Bir nechta havola qo‘shish',
  stepsTitle: 'Topilmadan buyurtmagacha', step1: 'Mahsulotni tanlang', step1hint: 'Variantlar va taxminiy jamini ko‘ring.', step2: 'Hisobni tekshiring', step2hint: 'Har bir xarajat alohida ko‘rsatiladi.', step3: 'Tasdiqlang', step3hint: 'Qabul qiluvchini kiriting va ma’lumotlarni tekshiring.', step4: 'Buyurtmani kuzating', step4hint: 'O‘zgarishlar va kelishuvlar kabinetda.',
  sourceMissing: 'Do‘kon manbasi hali ulanmagan', sourceOpen: 'Do‘kon sahifasi',
  shoeName: 'Kundalik krossovkalar', audioName: 'Simsiz quloqchinlar', bagName: 'Shahar ryukzagi',
};
const en: Copy = {
  title: 'Finds worth a closer look.', intro: 'Discover offers. Compare costs including delivery to Uzbekistan.',
  overline: 'ATLAS FINDS', savedTitle: 'Your saved finds.', savedIntro: 'Compare prices and come back when you’re ready to buy.',
  demo: 'Demo collection', demoHint: 'Products, discounts and options are examples. Live store offers are not connected yet.',
  all: 'All categories', footwear: 'Footwear', electronics: 'Electronics', accessories: 'Accessories',
  search: 'Search finds', searchPlaceholder: 'Product, category or country', clear: 'Clear search',
  country: 'Country', allCountries: 'All countries', us: 'USA', de: 'Germany', es: 'Spain',
  budget: 'Budget including delivery', anyBudget: 'Any budget', budget1: 'Under 1m UZS', budget15: 'Under 1.5m UZS', budget2: 'Under 2m UZS',
  sort: 'Sort', discountSort: 'Largest product discount', lowSort: 'Lowest delivered cost', highSort: 'Highest delivered cost',
  reset: 'Reset filters', results: 'Found', saved: 'Saved finds', catalog: 'All finds',
  demoBadge: 'Example discount', demoItem: 'Demo product', productPrice: 'Product, USD', before: 'Example previous price', saving: 'Product price difference',
  delivered: 'Estimated total with delivery', excluded: 'Customs charges not included', breakdown: 'Price breakdown',
  merchandise: 'Product', service: 'Purchasing and service', merchantShipping: 'Store delivery', international: 'International delivery', reserve: 'Refundable reserve',
  zeroShipping: '0 UZS in this example', unknownShipping: 'Unknown store delivery requires a separate reserve. This is an illustrative calculation.',
  buy: 'Choose options', variants: 'Options', save: 'Save', remove: 'Remove from saved', savingState: 'Saving', signin: 'Sign in to save finds',
  compareHint: 'The discount applies only to the product price in USD. The total below includes service, delivery and reserve.',
  empty: 'No matching finds yet', emptyHint: 'Increase your budget or remove a filter.', emptySaved: 'Save your first find', emptySavedHint: 'Tap the heart on a product and it will appear here.',
  linkTitle: 'Found something in another store?', linkHint: 'Paste your link to calculate a purchase through Atlas.', linkLabel: 'Product link', calculate: 'Calculate', batch: 'Add multiple links',
  stepsTitle: 'From a find to your order', step1: 'Choose a product', step1hint: 'Check the options and estimated total.', step2: 'Review the calculation', step2hint: 'Every cost is shown separately.', step3: 'Confirm', step3hint: 'Add the recipient and check the details.', step4: 'Follow your order', step4hint: 'Updates and approvals stay in your account.',
  sourceMissing: 'Store source not connected yet', sourceOpen: 'Store page',
  shoeName: 'Everyday sneakers', audioName: 'Wireless headphones', bagName: 'City backpack',
};
export const dealCopy = (locale: Locale): Copy => ({ ru, uz, en })[locale];
