import type { Locale } from './i18n';

const ru = {
  title: 'Каталог зарубежных товаров.', intro: 'Обычные товары и лучшие скидки — в одном месте, с расчётом доставки в Узбекистан.',
  overline: 'КАТАЛОГ ATLAS', savedTitle: 'Избранные товары.', savedIntro: 'Сравните цены и вернитесь к покупке, когда будете готовы.',
  observed: 'Цена на', checkOptions: 'Размер и наличие — в магазине', priceNote: 'Цены зафиксированы на указанную дату и могут измениться. Перед оформлением проверьте выбранный вариант в магазине. Atlas не является официальным представителем указанных брендов.', estimateHint: 'Вес оценочный. Итог рассчитан по настроенным тарифам Atlas, не является офертой и уточняется до выкупа.',
  all: 'Все категории', footwear: 'Обувь', clothing: 'Одежда', electronics: 'Электроника', accessories: 'Аксессуары',
  search: 'Поиск по каталогу', searchPlaceholder: 'Товар, магазин, категория или страна', clear: 'Очистить поиск',
  country: 'Страна', allCountries: 'Все страны', us: 'США', de: 'Германия', es: 'Испания',
  budget: 'Бюджет с доставкой', anyBudget: 'Любой бюджет', budget1: 'До 1 млн сум', budget15: 'До 1,5 млн сум', budget2: 'До 2 млн сум',
  sort: 'Сортировка', discountSort: 'Больше скидка на товар', lowSort: 'Дешевле с доставкой', highSort: 'Дороже с доставкой',
  reset: 'Сбросить фильтры', results: 'Найдено', saved: 'Избранное', catalog: 'Каталог', topDeal: 'Топ-цена',
  discountLabel: 'в магазине', productPrice: 'Цена магазина, USD', referenceLabel: 'Базовая цена, указанная магазином', saving: 'Разница в цене товара',
  delivered: 'Предварительно с доставкой', excluded: 'Таможенные платежи не включены', breakdown: 'Из чего складывается цена',
  merchandise: 'Товар', service: 'Выкуп и сервис', merchantShipping: 'Доставка магазина', international: 'Международная доставка', reserve: 'Возвратный резерв',
  unknownShipping: 'На доставку магазина заложен резерв $10. Фактическая сумма уточняется отдельно.',
  buy: 'В корзину', variants: 'Вариантов', save: 'Сохранить', remove: 'Убрать из избранного', savingState: 'Сохраняем', signin: 'Войдите, чтобы сохранять товары',
  compareHint: 'Скидка относится только к цене товара в USD. Итог ниже включает сервис, доставку и резерв.',
  empty: 'Таких товаров пока нет', emptyHint: 'Увеличьте бюджет или уберите один из фильтров.', emptySaved: 'Сохраните первый товар', emptySavedHint: 'Нажмите на сердечко у товара — он появится здесь.',
  linkTitle: 'Уже нашли товар в другом магазине?', linkHint: 'Вставьте свою ссылку — рассчитайте покупку через Atlas.', linkLabel: 'Ссылка на товар', calculate: 'Рассчитать', batch: 'Добавить несколько ссылок',
  stepsTitle: 'От товара до вашего заказа', step1: 'Выберите товар', step1hint: 'Посмотрите варианты и предварительный итог.', step2: 'Проверьте расчёт', step2hint: 'Все расходы видны отдельными строками.', step3: 'Подтвердите', step3hint: 'Укажите получателя и проверьте данные.', step4: 'Следите за заказом', step4hint: 'Изменения и согласования — в кабинете.',
  sourceMissing: 'Источник магазина ещё не подключён', sourceOpen: 'Страница магазина',
  shoeName: 'Кроссовки на каждый день', audioName: 'Беспроводные наушники', bagName: 'Городской рюкзак',
};
type Copy = { [K in keyof typeof ru]: string };
const uz: Copy = {
  title: 'Xorijiy mahsulotlar katalogi.', intro: 'Oddiy mahsulotlar va eng yaxshi chegirmalar — O‘zbekistonga yetkazish hisobi bilan bir joyda.',
  overline: 'ATLAS KATALOGI', savedTitle: 'Saralangan mahsulotlar.', savedIntro: 'Narxlarni solishtiring va tayyor bo‘lganingizda xaridga qayting.',
  observed: 'Narx sanasi', checkOptions: 'O‘lcham va mavjudlik — do‘konda', priceNote: 'Narxlar ko‘rsatilgan sanada qayd etilgan va o‘zgarishi mumkin. Buyurtmadan oldin variantni do‘konda tekshiring. Atlas ushbu brendlarning rasmiy vakili emas.', estimateHint: 'Vazn taxminiy. Jami Atlas tariflari asosida hisoblangan, oferta emas va xariddan oldin aniqlashtiriladi.',
  all: 'Barcha toifalar', footwear: 'Poyabzal', clothing: 'Kiyim', electronics: 'Elektronika', accessories: 'Aksessuarlar',
  search: 'Katalogdan qidirish', searchPlaceholder: 'Mahsulot, do‘kon, toifa yoki mamlakat', clear: 'Qidiruvni tozalash',
  country: 'Mamlakat', allCountries: 'Barcha mamlakatlar', us: 'AQSH', de: 'Germaniya', es: 'Ispaniya',
  budget: 'Yetkazish bilan budjet', anyBudget: 'Istalgan budjet', budget1: '1 mln so‘mgacha', budget15: '1,5 mln so‘mgacha', budget2: '2 mln so‘mgacha',
  sort: 'Saralash', discountSort: 'Kattaroq mahsulot chegirmasi', lowSort: 'Yetkazish bilan arzonroq', highSort: 'Yetkazish bilan qimmatroq',
  reset: 'Filtrlarni tozalash', results: 'Topildi', saved: 'Saralangan', catalog: 'Katalog', topDeal: 'Top narx',
  discountLabel: 'do‘konda', productPrice: 'Do‘kon narxi, USD', referenceLabel: 'Do‘kon ko‘rsatgan asosiy narx', saving: 'Mahsulot narxidagi farq',
  delivered: 'Yetkazish bilan taxminiy jami', excluded: 'Bojxona to‘lovlari kiritilmagan', breakdown: 'Narx tarkibi',
  merchandise: 'Mahsulot', service: 'Sotib olish va xizmat', merchantShipping: 'Do‘kondan yetkazish', international: 'Xalqaro yetkazish', reserve: 'Qaytariladigan zaxira',
  unknownShipping: 'Do‘kondan yetkazish uchun $10 zaxira kiritilgan. Haqiqiy summa alohida aniqlashtiriladi.',
  buy: 'Savatga', variants: 'Variantlar', save: 'Saqlash', remove: 'Saralanganlardan olib tashlash', savingState: 'Saqlanmoqda', signin: 'Mahsulotlarni saqlash uchun kiring',
  compareHint: 'Chegirma faqat mahsulotning USD narxiga tegishli. Quyidagi jami xizmat, yetkazish va zaxirani o‘z ichiga oladi.',
  empty: 'Bunday mahsulotlar hozircha yo‘q', emptyHint: 'Budjetni oshiring yoki filtrlardan birini olib tashlang.', emptySaved: 'Birinchi mahsulotni saqlang', emptySavedHint: 'Mahsulot yonidagi yurakchani bosing — u shu yerda paydo bo‘ladi.',
  linkTitle: 'Boshqa do‘konda mahsulot topdingizmi?', linkHint: 'Havolani joylang va Atlas orqali xaridni hisoblang.', linkLabel: 'Mahsulot havolasi', calculate: 'Hisoblash', batch: 'Bir nechta havola qo‘shish',
  stepsTitle: 'Mahsulotdan buyurtmagacha', step1: 'Mahsulotni tanlang', step1hint: 'Variantlar va taxminiy jamini ko‘ring.', step2: 'Hisobni tekshiring', step2hint: 'Har bir xarajat alohida ko‘rsatiladi.', step3: 'Tasdiqlang', step3hint: 'Qabul qiluvchini kiriting va ma’lumotlarni tekshiring.', step4: 'Buyurtmani kuzating', step4hint: 'O‘zgarishlar va kelishuvlar kabinetda.',
  sourceMissing: 'Do‘kon manbasi hali ulanmagan', sourceOpen: 'Do‘kon sahifasi',
  shoeName: 'Kundalik krossovkalar', audioName: 'Simsiz quloqchinlar', bagName: 'Shahar ryukzagi',
};
const en: Copy = {
  title: 'International product catalog.', intro: 'Everyday products and the best discounts in one place, with delivery estimates to Uzbekistan.',
  overline: 'ATLAS CATALOG', savedTitle: 'Saved products.', savedIntro: 'Compare prices and come back when you’re ready to buy.',
  observed: 'Price recorded', checkOptions: 'Check options at the store', priceNote: 'Prices were recorded on the stated date and may change. Check your selected option at the store before ordering. Atlas is not an official representative of these brands.', estimateHint: 'Weight is estimated. Totals use configured Atlas rates, are not a binding offer and must be confirmed before purchase.',
  all: 'All categories', footwear: 'Footwear', clothing: 'Clothing', electronics: 'Electronics', accessories: 'Accessories',
  search: 'Search catalog', searchPlaceholder: 'Product, store, category or country', clear: 'Clear search',
  country: 'Country', allCountries: 'All countries', us: 'USA', de: 'Germany', es: 'Spain',
  budget: 'Budget including delivery', anyBudget: 'Any budget', budget1: 'Under 1m UZS', budget15: 'Under 1.5m UZS', budget2: 'Under 2m UZS',
  sort: 'Sort', discountSort: 'Largest product discount', lowSort: 'Lowest delivered cost', highSort: 'Highest delivered cost',
  reset: 'Reset filters', results: 'Found', saved: 'Saved', catalog: 'Catalog', topDeal: 'Top price',
  discountLabel: 'at the store', productPrice: 'Store price, USD', referenceLabel: 'Base price shown by the store', saving: 'Product price difference',
  delivered: 'Estimated total with delivery', excluded: 'Customs charges not included', breakdown: 'Price breakdown',
  merchandise: 'Product', service: 'Purchasing and service', merchantShipping: 'Store delivery', international: 'International delivery', reserve: 'Refundable reserve',
  unknownShipping: 'A $10 reserve covers unconfirmed store delivery. The actual amount is checked separately.',
  buy: 'Add to cart', variants: 'Options', save: 'Save', remove: 'Remove from saved', savingState: 'Saving', signin: 'Sign in to save products',
  compareHint: 'The discount applies only to the product price in USD. The total below includes service, delivery and reserve.',
  empty: 'No matching products yet', emptyHint: 'Increase your budget or remove a filter.', emptySaved: 'Save your first product', emptySavedHint: 'Tap the heart on a product and it will appear here.',
  linkTitle: 'Found something in another store?', linkHint: 'Paste your link to calculate a purchase through Atlas.', linkLabel: 'Product link', calculate: 'Calculate', batch: 'Add multiple links',
  stepsTitle: 'From product to order', step1: 'Choose a product', step1hint: 'Check the options and estimated total.', step2: 'Review the calculation', step2hint: 'Every cost is shown separately.', step3: 'Confirm', step3hint: 'Add the recipient and check the details.', step4: 'Follow your order', step4hint: 'Updates and approvals stay in your account.',
  sourceMissing: 'Store source not connected yet', sourceOpen: 'Store page',
  shoeName: 'Everyday sneakers', audioName: 'Wireless headphones', bagName: 'City backpack',
};
export const dealCopy = (locale: Locale): Copy => ({ ru, uz, en })[locale];
