import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {blank,parseState,pricingSchema,tariff,type Pricing,type State} from './domain';
import {defaultPolicy,policySchema,type Policy} from './policy';
export function database(){if(!env.DB)throw Error('Серверное хранилище пока недоступно.');return env.DB}
export async function identity(){const user=await getChatGPTUser();if(!user)throw new HttpError(401,'Войдите, чтобы продолжить.');return user}
export function operator(email:string){return !!env.ATLAS_OPERATOR_EMAIL&&email.toLowerCase()===env.ATLAS_OPERATOR_EMAIL.toLowerCase()}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)throw new HttpError(403,'Недопустимый источник запроса.')}
export const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function account(user:{userId:string;platformUserId?:string|null;displayName:string}){const now=Date.now(),db=database();if(user.platformUserId&&user.platformUserId!==user.userId)await db.prepare('INSERT OR IGNORE INTO market_accounts (user_id,name,state,revision,created_at,updated_at) SELECT ?,name,state,revision,created_at,updated_at FROM market_accounts WHERE user_id=?').bind(user.userId,user.platformUserId).run();await db.prepare('INSERT OR IGNORE INTO market_accounts (user_id,name,state,revision,created_at,updated_at) VALUES (?,?,?,0,?,?)').bind(user.userId,user.displayName,JSON.stringify(blank()),now,now).run();const row=await db.prepare('SELECT name,state,revision,created_at FROM market_accounts WHERE user_id=?').bind(user.userId).first<{name:string;state:string;revision:number;created_at:number}>();if(!row)throw Error('Account unavailable');return {...row,state:parseState(row.state)}}
export async function persist(id:string,state:State,revision:number){if(JSON.stringify(state).length>1000000)throw new HttpError(413,'Достигнут лимит данных тестового профиля.');const result=await database().prepare('UPDATE market_accounts SET state=?, revision=revision+1, updated_at=? WHERE user_id=? AND revision=?').bind(JSON.stringify(state),Date.now(),id,revision).run();if(!result.meta.changes)throw new HttpError(409,'Заказ изменился в другой вкладке. Данные обновлены — повторите действие.');}
export async function pricing():Promise<Pricing>{const row=await database().prepare("SELECT value FROM market_settings WHERE key='pricing'").first<{value:string}>();if(!row)return tariff;try{const parsed=pricingSchema.safeParse(JSON.parse(row.value));return parsed.success?parsed.data:tariff}catch{return tariff}}
export async function savePricing(next:Pricing,userId:string){await database().prepare("INSERT INTO market_settings (key,value,updated_at,updated_by) VALUES ('pricing',?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by").bind(JSON.stringify(next),next.updatedAt,userId).run()}
export async function policy():Promise<Policy>{const row=await database().prepare("SELECT value FROM market_settings WHERE key='policy'").first<{value:string}>();if(!row)return defaultPolicy;try{const parsed=policySchema.safeParse(JSON.parse(row.value));return parsed.success?parsed.data:defaultPolicy}catch{return defaultPolicy}}
export async function savePolicy(next:Policy,userId:string){await database().prepare("INSERT INTO market_settings (key,value,updated_at,updated_by) VALUES ('policy',?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by").bind(JSON.stringify(next),next.updatedAt,userId).run()}
export async function operatorAccounts(){const rows=await database().prepare('SELECT user_id,name,state,revision,updated_at FROM market_accounts ORDER BY updated_at DESC LIMIT 200').all<{user_id:string;name:string;state:string;revision:number;updated_at:number}>();return rows.results.map(row=>({id:row.user_id,name:row.name,state:parseState(row.state),revision:row.revision,updatedAt:row.updated_at}))}
export async function storedAccount(id:string){const row=await database().prepare('SELECT user_id,name,state,revision,updated_at FROM market_accounts WHERE user_id=?').bind(id).first<{user_id:string;name:string;state:string;revision:number;updated_at:number}>();if(!row)throw new HttpError(404,'Профиль покупателя не найден.');return {id:row.user_id,name:row.name,state:parseState(row.state),revision:row.revision,updatedAt:row.updated_at}}
export function failure(error:unknown){if(error instanceof HttpError)return json({error:error.message},error.status);return json({error:'Не удалось выполнить запрос. Попробуйте ещё раз.'},503)}

export async function requestJson(request:Request,maxBytes=1100000):Promise<unknown>{
 const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'Пустой запрос.');
 let text='',size=0;const decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new HttpError(413,'Слишком большой запрос.')}text+=decoder.decode(value,{stream:true})}text+=decoder.decode();try{return JSON.parse(text)}catch{throw new HttpError(400,'Некорректный JSON.')}
}
