import type { Locale } from './i18n.ts';
import type { DeliveryRegion } from './site-content.ts';
import type { StoreCountry, StoreRegion } from './store-brands.ts';
import {withCyrillic} from './uz-cyrl.ts';

function ruPlural(count: number, [one, few, many]: [string, string, string]) {
  const tens = count % 100, units = count % 10;
  if (tens >= 11 && tens <= 14) return many;
  return units === 1 ? one : units >= 2 && units <= 4 ? few : many;
}

const ru = {
  title: (count: number) => `${count} ${ruPlural(count, ['магазин', 'магазина', 'магазинов'])} мира в одном месте`,
  intro: 'Вставьте ссылку — покажем итог в сумах.',
  howtoTitle: 'Как скопировать ссылку на товар',
  howto: [['iPhone', 'В Safari откройте товар, нажмите «Поделиться» → «Скопировать».'], ['Android', 'В Chrome: меню ⋮ → «Поделиться» → «Копировать ссылку».'], ['Компьютер', 'Скопируйте адрес из строки браузера: Ctrl+C (⌘C).']] as [string, string][],
  pasteLabel: 'Ссылка на товар', pastePlaceholder: 'Ссылка на товар', calculate: 'Рассчитать', paste: 'Вставить из буфера',
  regionsTitle: 'Откуда везём',
  daysShort: (from: number, to: number) => `${from}–${to} раб. дн`,
  termsNote: 'Сроки ориентировочные; тариф и курс — на день расчёта.',
  pendingTerms: 'срок уточняется',
  moreCountries: (count: number) => `ещё ${count} ${ruPlural(count, ['страна', 'страны', 'стран'])}`,
  showcase: 'Витрины с товарами',
  products: (count: number) => `${count} ${ruPlural(count, ['товар', 'товара', 'товаров'])}`,
  fromTotal: '≈ от', withDelivery: ' с доставкой',
  lastPrices: 'по последним ценам магазина',
  showStore: 'Смотреть',
  youOrdered: 'Вы заказывали здесь', inCartMark: 'Посылка в корзине',
  popular: 'Популярные', directory: 'Все магазины', search: 'Найти магазин или бренд', clear: 'Очистить',
  all: 'Все', regionLabel: 'Где покупать', regions: { us: 'США', eu: 'Европа', asia: 'Азия', other: 'Другие страны' } as Record<StoreRegion, string>,
  /** Shorter country names for the narrow hero cards; others use storeCountryNames. */
  countryShort: { uk: 'Британия' } as Partial<Record<StoreCountry, string>>,
  count: (count: number) => `${count} ${ruPlural(count, ['магазин', 'магазина', 'магазинов'])}`,
  noResults: 'Такого магазина нет в списке. Проверьте название или домен — или вставьте ссылку на товар: если магазин поддерживается, расчёт откроется сразу.',
  open: (domain: string) => `Открыть ${domain}`, storefronts: 'Витрины по странам',
  howTitle: 'Как заказать', close: 'Закрыть', newTab: 'откроется в новой вкладке',
  dialogPaste: (domain: string) => `Вставьте ссылку с ${domain}`,
  termsTitle: (from: string) => `Условия доставки ${from}`,
  fromCountry: { us: 'из США', uk: 'из Великобритании', cn: 'из Китая', de: 'из Германии', it: 'из Италии', es: 'из Испании' } as Record<DeliveryRegion, string>,
  termsGeneric: 'Условия доставки',
  termsPending: 'Срок и тариф уточняются при расчёте — они зависят от страны магазина.',
  termsLabels: { weight: 'Вес', storeShipping: 'Доставка магазина', customs: 'Таможня' },
  minParcel: 'минимум 1 кг на посылку + 0,3 кг упаковки',
  storeShippingRule: (freeFrom: string, hold: string) => `Если магазин не указал доставку до склада: при товарах из магазина дороже ${freeFrom} резерв не удерживается, иначе — возвратный резерв, обычно ${hold}; точная сумма — на странице расчёта`,
  dutyLimit: (limit: string) => `лимит без пошлины ${limit} в месяц на получателя (оценка)`,
  catalogShelf: (count: number) => `В каталоге Atlas · ${count} ${ruPlural(count, ['товар', 'товара', 'товаров'])}`,
  allProducts: (count: number) => `Все ${count}`,
  currencyUnsupported: (currency: string) => `расчёт в ${currency} пока недоступен`,
  note: 'Atlas принимает ссылки на товары с доменов из этого списка. Цену и вариант каждого товара Atlas сверяет с магазином отдельно. Логотипы принадлежат их владельцам; Atlas не является официальным представителем магазинов.',
  mine: 'Вы уже заказывали', showAll: (count: number) => `Показать все ${count}`, showLess: 'Свернуть',
  similar: 'Похожие магазины',
  missingTitle: 'Нет нужного магазина?', missingText: 'Вставьте ссылку на товар: если магазин поддерживается, сразу покажем расчёт. Если нет — подскажем, что делать.', missingAction: 'Вставить ссылку',
};
type Copy = typeof ru;

const uz: Copy = {
  title: (count: number) => `Dunyoning ${count} ta do‘koni bir joyda`,
  intro: 'Havolani qo‘ying — narxni so‘mda ko‘rsatamiz.',
  howtoTitle: 'Tovar havolasini qanday nusxalash',
  howto: [['iPhone', 'Safari’da tovarni oching, «Ulashish» → «Nusxalash» ni bosing.'], ['Android', 'Chrome’da: menyu ⋮ → «Ulashish» → «Havolani nusxalash».'], ['Kompyuter', 'Brauzer manzil satridan nusxalang: Ctrl+C (⌘C).']],
  pasteLabel: 'Tovar havolasi', pastePlaceholder: 'Tovar havolasi', calculate: 'Hisoblash', paste: 'Buferdan qo‘yish',
  regionsTitle: 'Qayerdan olib kelamiz',
  daysShort: (from: number, to: number) => `${from}–${to} ish kuni`,
  termsNote: 'Muddatlar taxminiy; tarif va kurs — hisob kuniga ko‘ra.',
  pendingTerms: 'muddat aniqlanadi',
  moreCountries: (count: number) => `yana ${count} ta mamlakat`,
  showcase: 'Tovarli vitrinalar',
  products: (count: number) => `${count} ta tovar`,
  fromTotal: '≈ yetkazish bilan', withDelivery: 'dan',
  lastPrices: 'do‘konning oxirgi narxlari bo‘yicha',
  showStore: 'Ko‘rish',
  youOrdered: 'Siz bu yerdan buyurtma bergansiz', inCartMark: 'Savatda jo‘natma bor',
  popular: 'Mashhur', directory: 'Barcha do‘konlar', search: 'Do‘kon yoki brendni toping', clear: 'Tozalash',
  all: 'Barchasi', regionLabel: 'Qayerdan xarid qilish', regions: { us: 'AQSh', eu: 'Yevropa', asia: 'Osiyo', other: 'Boshqa mamlakatlar' },
  countryShort: { uk: 'Britaniya' },
  count: (count: number) => `${count} ta do‘kon`,
  noResults: 'Bunday do‘kon ro‘yxatda yo‘q. Nom yoki domenni tekshiring — yoki tovar havolasini qo‘ying: do‘kon qo‘llab-quvvatlansa, hisob darhol ochiladi.',
  open: (domain: string) => `${domain} saytini ochish`, storefronts: 'Mamlakatlar bo‘yicha vitrinalar',
  howTitle: 'Qanday buyurtma berish', close: 'Yopish', newTab: 'yangi oynada ochiladi',
  dialogPaste: (domain: string) => `${domain} dan havola qo‘ying`,
  termsTitle: (from: string) => `${from} yetkazish shartlari`,
  fromCountry: { us: 'AQShdan', uk: 'Buyuk Britaniyadan', cn: 'Xitoydan', de: 'Germaniyadan', it: 'Italiyadan', es: 'Ispaniyadan' },
  termsGeneric: 'Yetkazish shartlari',
  termsPending: 'Muddat va tarif hisoblashda aniqlanadi — ular do‘kon mamlakatiga bog‘liq.',
  termsLabels: { weight: 'Og‘irlik', storeShipping: 'Do‘kon yetkazishi', customs: 'Bojxona' },
  minParcel: 'jo‘natmaga kamida 1 kg + 0,3 kg qadoq',
  storeShippingRule: (freeFrom: string, hold: string) => `Do‘kon omborgacha yetkazishni ko‘rsatmagan bo‘lsa: do‘kondagi tovarlar ${freeFrom} dan qimmat bo‘lsa zaxira ushlanmaydi, aks holda — qaytariladigan zaxira, odatda ${hold}; aniq summa — hisob sahifasida`,
  dutyLimit: (limit: string) => `oyiga har bir oluvchiga ${limit} gacha bojsiz limit (taxmin)`,
  catalogShelf: (count: number) => `Atlas katalogida · ${count} ta tovar`,
  allProducts: (count: number) => `Barchasi: ${count}`,
  currencyUnsupported: (currency: string) => `${currency} da hisoblash hozircha mavjud emas`,
  note: 'Atlas shu ro‘yxatdagi domenlardan tovar havolalarini qabul qiladi. Har bir tovarning narxi va variantini Atlas do‘kon bilan alohida solishtiradi. Logotiplar egalariga tegishli; Atlas do‘konlarning rasmiy vakili emas.',
  mine: 'Siz buyurtma bergan do‘konlar', showAll: (count: number) => `Barchasini ko‘rsatish: ${count}`, showLess: 'Yig‘ish',
  similar: 'O‘xshash do‘konlar',
  missingTitle: 'Kerakli do‘kon yo‘qmi?', missingText: 'Tovar havolasini qo‘ying: do‘kon qo‘llab-quvvatlansa, darhol hisobni ko‘rsatamiz. Bo‘lmasa — nima qilishni aytamiz.', missingAction: 'Havolani qo‘yish',
};

const en: Copy = {
  title: (count: number) => `${count} stores from around the world in one place`,
  intro: 'Paste a link — see the total in soum.',
  howtoTitle: 'How to copy a product link',
  howto: [['iPhone', 'In Safari open the product, tap Share → Copy.'], ['Android', 'In Chrome: menu ⋮ → Share → Copy link.'], ['Computer', 'Copy the address from the browser bar: Ctrl+C (⌘C).']],
  pasteLabel: 'Product link', pastePlaceholder: 'Product link', calculate: 'Calculate', paste: 'Paste from clipboard',
  regionsTitle: 'Where we ship from',
  daysShort: (from: number, to: number) => `${from}–${to} bus. days`,
  termsNote: 'Timing is approximate; the rate and exchange rate are those of the day of the estimate.',
  pendingTerms: 'timing to be confirmed',
  moreCountries: (count: number) => `${count} more ${count === 1 ? 'country' : 'countries'}`,
  showcase: 'Storefronts with products',
  products: (count: number) => `${count} ${count === 1 ? 'product' : 'products'}`,
  fromTotal: '≈ from', withDelivery: ' with delivery',
  lastPrices: 'at the store’s last prices',
  showStore: 'View',
  youOrdered: 'You ordered here', inCartMark: 'Parcel in your cart',
  popular: 'Popular', directory: 'All stores', search: 'Find a store or brand', clear: 'Clear',
  all: 'All', regionLabel: 'Where to shop', regions: { us: 'USA', eu: 'Europe', asia: 'Asia', other: 'Other countries' },
  countryShort: { uk: 'UK' },
  count: (count: number) => `${count} ${count === 1 ? 'store' : 'stores'}`,
  noResults: 'This store isn’t on the list. Check the name or domain — or paste a product link: if the store is supported, the estimate opens right away.',
  open: (domain: string) => `Open ${domain}`, storefronts: 'Storefronts by country',
  howTitle: 'How to order', close: 'Close', newTab: 'opens in a new tab',
  dialogPaste: (domain: string) => `Paste a link from ${domain}`,
  termsTitle: (from: string) => `Delivery terms ${from}`,
  fromCountry: { us: 'from the USA', uk: 'from the UK', cn: 'from China', de: 'from Germany', it: 'from Italy', es: 'from Spain' },
  termsGeneric: 'Delivery terms',
  termsPending: 'Timing and rate are confirmed in the estimate — they depend on the store’s country.',
  termsLabels: { weight: 'Weight', storeShipping: 'Store delivery', customs: 'Customs' },
  minParcel: 'minimum 1 kg per parcel + 0.3 kg packaging',
  storeShippingRule: (freeFrom: string, hold: string) => `If the store does not state delivery to the warehouse: no reserve when items from the store cost over ${freeFrom}, otherwise a refundable reserve, usually ${hold}; the exact amount is on the estimate page`,
  dutyLimit: (limit: string) => `duty-free limit ${limit} per month per recipient (estimate)`,
  catalogShelf: (count: number) => `In the Atlas catalog · ${count} ${count === 1 ? 'product' : 'products'}`,
  allProducts: (count: number) => `All ${count}`,
  currencyUnsupported: (currency: string) => `estimates in ${currency} are not available yet`,
  note: 'Atlas accepts product links from the domains on this list. Atlas checks each product’s price and option with the store separately. Logos belong to their owners; Atlas is not an official representative of these stores.',
  mine: 'Stores you ordered from', showAll: (count: number) => `Show all ${count}`, showLess: 'Show less',
  similar: 'Similar stores',
  missingTitle: 'Store not listed?', missingText: 'Paste a product link: if the store is supported, the estimate opens right away. If not, we tell you what to do.', missingAction: 'Paste a link',
};

export const storesCopy: Record<Locale, Copy> = /*@__PURE__*/withCyrillic({ ru, uz, en });
