// Isolated design fixtures. No imports from production state and no network writes.
const copy = {
  catalog:['Каталог','Katalog','Catalog'], product:['Товар','Mahsulot','Product'], cart:['Корзина','Savat','Bag'], account:['Кабинет','Kabinet','Account'],
  favorites:['Избранное','Saralangan','Saved'], link:['Заказ по ссылке','Havola orqali buyurtma','Order by link'], support:['Поддержка','Yordam','Support'],
  hero:['Хорошие вещи.\nБлиже, чем кажется.','Yaxshi narsalar.\nSiz o‘ylagandan yaqinroq.','Good things.\nCloser than you think.'],
  intro:['Выбирайте в зарубежных магазинах. Atlas поможет с выкупом и доставкой в Узбекистан.','Xorijiy do‘konlardan tanlang. Atlas xarid va O‘zbekistonga yetkazishda yordam beradi.','Shop overseas stores. Atlas helps arrange your purchase and delivery to Uzbekistan.'],
  browse:['Смотреть каталог','Katalogni ko‘rish','Explore the catalog'], season:['Вещи для каждого дня','Har kun uchun buyumlar','Everyday essentials'],
  selection:['Выбрано для вас','Siz uchun tanlangan','Selected for you'], all:['Все товары','Barcha mahsulotlar','All items'], shoes:['Обувь','Poyabzal','Footwear'], tech:['Техника','Texnika','Technology'], accessories:['Аксессуары','Aksessuarlar','Accessories'],
  search:['Найти вещь или бренд','Mahsulot yoki brendni topish','Find an item or brand'], sourcePrice:['В магазине','Do‘konda','Store price'], estimate:['Ориентир с доставкой','Yetkazish bilan taxminan','Estimated with delivery'],
  choose:['Выбрать','Tanlash','Choose'], saved:['Сохранено','Saqlandi','Saved'], save:['Сохранить','Saqlash','Save'], clear:['Сбросить','Tozalash','Reset'],
  customLink:['Уже нашли свою вещь?','Kerakli narsani topdingizmi?','Found something elsewhere?'], paste:['Вставьте ссылку из магазина','Do‘kon havolasini kiriting','Paste a store product link'],
  sampleLink:['В прототипе откроется пример товара. Ссылка не отправляется на сервер.','Prototipda namuna ochiladi. Havola serverga yuborilmaydi.','This prototype opens a sample item. The link is not sent to a server.'],
  reviewNote:['Визуальный прототип · цены и заказы приведены для примера','Vizual prototip · narxlar va buyurtmalar namuna sifatida','Visual prototype · sample prices and orders'],
  purchase:['Выкуп','Xarid','Purchase'], delivery:['Доставка','Yetkazish','Delivery'], country:['США → Узбекистан','AQSh → O‘zbekiston','US → Uzbekistan'],
  name0:['Кеды из канваса','Kanvas kedalar','Canvas low-top sneakers'], name1:['Накладные наушники','Quloqchinlar','Over-ear headphones'], name2:['Городской рюкзак','Shahar ryukzagi','Everyday backpack'],
  description:['Лёгкая пара на каждый день. Выберите размер перед добавлением в корзину.','Har kun uchun yengil juftlik. Savatga qo‘shishdan oldin o‘lchamni tanlang.','An easy everyday pair. Choose your size before adding to your bag.'],
  color:['Цвет','Rang','Color'], navy:['Тёмно-синий','To‘q ko‘k','Navy'], size:['Размер','O‘lcham','Size'], sizeHint:['Размеры в примере не подтверждают наличие в магазине.','Namunadagi o‘lchamlar do‘kondagi mavjudlikni tasdiqlamaydi.','Sample sizes do not represent verified store stock.'],
  add:['Добавить в корзину','Savatga qo‘shish','Add to bag'], selectSize:['Выберите размер','O‘lchamni tanlang','Choose a size'], breakdown:['Из чего складывается сумма','Summa qanday hisoblanadi','Cost breakdown'],
  itemCost:['Стоимость товара','Mahsulot narxi','Item price'], storeShipping:['До зарубежного склада · резерв','Xorijiy omborgacha · zaxira','To overseas warehouse · reserve'], service:['Услуги Atlas','Atlas xizmatlari','Atlas services'], freight:['Международная доставка','Xalqaro yetkazish','International delivery'], reserve:['Резерв доставки','Yetkazish zaxirasi','Delivery reserve'],
  estimateNote:['Предварительная сумма. Изменения согласуем перед выкупом.','Dastlabki summa. O‘zgarishlar xariddan oldin kelishiladi.','Preliminary estimate. Changes need your approval before purchase.'],
  customs:['Таможенные условия','Bojxona shartlari','Customs conditions'], customsText:['Итоговые платежи зависят от товара и ввоза получателя. Расчёт нужно проверить перед оформлением.','Yakuniy to‘lovlar mahsulot va qabul qiluvchining importiga bog‘liq. Buyurtmadan oldin hisobni tekshiring.','Final charges depend on the item and recipient’s imports. Review the estimate before checkout.'],
  back:['Назад к покупкам','Xaridlarga qaytish','Back to shopping'], review:['Проверьте заказ','Buyurtmani tekshiring','Review your order'], recipient:['Получатель','Qabul qiluvchi','Recipient'], address:['Адрес доставки','Yetkazish manzili','Delivery address'], edit:['Изменить','O‘zgartirish','Edit'],
  recipientSample:['Получатель из примера','Namunadagi qabul qiluvchi','Sample recipient'], addressSample:['Ташкент · адрес из примера','Toshkent · namunadagi manzil','Tashkent · sample address'],
  consent:['Принимаю условия сервиса и таможенные условия','Xizmat va bojxona shartlarini qabul qilaman','I accept the service and customs conditions'],
  next:['Перейти к проверке','Tekshirishga o‘tish','Continue to review'], confirm:['Подтвердить в прототипе','Prototipda tasdiqlash','Confirm in prototype'], complete:['Пример заказа подтверждён. Деньги не списаны, заявка не отправлена.','Namuna tasdiqlandi. Pul yechilmadi, buyurtma yuborilmadi.','Sample confirmed. No charge or order was sent.'],
  units:['1 товар','1 mahsulot','1 item'], overview:['Ваш Atlas','Sizning Atlas','Your Atlas'], welcome:['Всё важное — под рукой.','Muhim narsalar bir joyda.','Everything in its place.'],
  active:['В работе','Jarayonda','In progress'], orders:['Заказы','Buyurtmalar','Orders'], documents:['Документы','Hujjatlar','Documents'], recipients:['Получатели и адреса','Qabul qiluvchilar va manzillar','Recipients & addresses'], messages:['Сообщения','Xabarlar','Messages'],
  nextAction:['Следующий шаг','Keyingi qadam','Next step'], orderTitle:['Заказ на зарубежном складе','Buyurtma xorijiy omborda','Your order is at the overseas warehouse'], orderHint:['Ожидаем взвешивание. Пока ничего делать не нужно.','Tortishni kutyapmiz. Hozircha hech narsa qilish shart emas.','Waiting for weighing. Nothing you need to do right now.'], openOrder:['Открыть заказ','Buyurtmani ochish','View order'],
  latest:['Последние заказы','Oxirgi buyurtmalar','Recent orders'], allOrders:['Все заказы','Barcha buyurtmalar','All orders'], warehouse:['На складе','Omborda','At warehouse'], inTransit:['В пути','Yo‘lda','In transit'], delivered:['Доставлен','Yetkazildi','Delivered'],
  addressesText:['Сохранён один получатель. Данные используются только при оформлении.','Bitta qabul qiluvchi saqlangan. Ma’lumotlar rasmiylashtirishda ishlatiladi.','One saved recipient. Details are used at checkout.'],
  docsText:['Паспорт, счета и складские фото доступны только владельцу заказа.','Pasport, hisoblar va ombor rasmlari faqat buyurtma egasiga ko‘rinadi.','Passport, invoices and warehouse photos are available to the order owner.'],
  supportText:['История обращений остаётся рядом с заказом.','Murojaatlar tarixi buyurtma yonida saqlanadi.','Your conversation stays with the order.'],
  timeline:['Выкуплен → склад → отправка → получение','Xarid → ombor → jo‘natish → qabul qilish','Purchased → warehouse → dispatch → received'],
  empty:['Здесь пока ничего нет','Hozircha hech narsa yo‘q','Nothing here yet'], emptyText:['Попробуйте другой запрос или вернитесь к каталогу.','Boshqa so‘rovni sinab ko‘ring yoki katalogga qayting.','Try another search or return to the catalog.'], error:['Не удалось загрузить данные','Ma’lumotlarni yuklab bo‘lmadi','Couldn’t load your data'], errorText:['Ваши выбранные параметры сохранены в этом просмотре. Попробуйте ещё раз.','Tanlovlaringiz ushbu ko‘rishda saqlangan. Qayta urinib ko‘ring.','Your selections are kept in this preview. Please try again.'], retry:['Повторить','Qayta urinish','Try again'], loading:['Загружаем','Yuklanmoqda','Loading'],
  help:['Нужна помощь с заказом?','Buyurtma bo‘yicha yordam kerakmi?','Need help with an order?'], ownLink:['По своей ссылке','O‘z havolangiz bilan','Use your own link'],
};
const query = new URLSearchParams(location.search);
const values = { theme:['commerce','editorial','refined'], screen:['catalog','product','cart','account'], lang:['ru','uz','en'], state:['ready','empty','error','loading'] };
const model = { theme:'commerce',screen:'catalog',lang:'ru',state:'ready',category:'all',search:'',product:0,size:'',saved:new Set(),cartProduct:0,cartSize:'40',review:false,consent:false,accordion:'',linkValue:'' };
for (const key of Object.keys(values)) if (values[key].includes(query.get(key))) model[key] = query.get(key);
const products = [ {image:'sneaker',category:'shoes',usd:54}, {image:'headphones',category:'tech',usd:89}, {image:'backpack',category:'accessories',usd:64} ];
const t = key => copy[key]?.[['ru','uz','en'].indexOf(model.lang)] ?? key;
const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money = amount => new Intl.NumberFormat({ru:'ru-RU',uz:'uz-UZ',en:'en-US'}[model.lang],{maximumFractionDigits:0}).format(amount) + ' UZS';
const total = product => product.usd * 12800 * 1.12 + 236000;
const paths = { arrow:'M5 12h14m-6-6 6 6-6 6', bag:'M5 7h14l1 14H4L5 7Zm4 0V5a3 3 0 0 1 6 0v2', user:'M20 21a8 8 0 0 0-16 0m12-14a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z', search:'m21 21-5-5m2-6a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z', heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z', box:'m3 7 9-5 9 5v10l-9 5-9-5V7Zm0 0 9 5 9-5M12 12v10M7.5 4.5l9 5', plus:'M12 5v14M5 12h14', check:'m5 12 4 4L19 6', doc:'M14 2H4v20h16V8l-6-6Zm0 0v6h6M8 13h8M8 17h6', pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z', chat:'M21 11a9 9 0 0 1-9 9H3l1.7-4A9 9 0 1 1 21 11Z' };
const icon = name => `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.arrow}"/></svg>`;
function navigate(screen) { model.screen = screen; model.state='ready'; render(); window.scrollTo(0,0); if (parent !== window) parent.postMessage({type:'atlas-screen',screen},location.origin); }
function button(label, action, extra='') { return `<button class="button" data-action="${action}" ${extra}>${label}${icon('arrow')}</button>`; }
function picture(index, className='') { return `<img class="${className}" src="assets/${products[index].image}.jpg" alt="${esc(t('name'+index))}" width="1000" height="1000">`; }
function header() { return `<div class="sample-note">${t('reviewNote')}</div><header class="site-header"><button class="wordmark" data-nav="catalog" aria-label="Atlas — ${t('catalog')}">atlas<span>®</span></button><nav class="main-nav" aria-label="${t('catalog')}"><button data-nav="catalog" ${model.screen==='catalog'?'aria-current="page"':''}>${t('catalog')}</button><button data-nav="product">${t('link')}</button></nav><div class="header-actions"><span class="destination">UZ / ${model.lang.toUpperCase()}</span><button class="icon-button" data-nav="account" aria-label="${t('account')}">${icon('user')}</button><button class="icon-button bag" data-nav="cart" aria-label="${t('cart')}">${icon('bag')}<span>1</span></button></div></header>`; }
function cards() { const visible = products.map((product,index)=>({...product,index})).filter(product => (model.category==='all'||product.category===model.category) && (t('name'+product.index)+' '+t(product.category)).toLocaleLowerCase().includes(model.search.toLocaleLowerCase()));
  if(!visible.length) return `<div class="empty-inline"><h2>${t('empty')}</h2><p>${t('emptyText')}</p><button class="text-button" data-action="reset">${t('clear')}</button></div>`;
  return visible.map(product=>`<article class="product-card"><div class="product-image"><button class="photo-button" data-product="${product.index}" aria-label="${t('choose')} ${esc(t('name'+product.index))}">${picture(product.index)}</button><button class="save-button" data-save="${product.index}" aria-pressed="${model.saved.has(product.index)}" aria-label="${t('save')} ${esc(t('name'+product.index))}">${icon('heart')}</button><span class="product-category">${t(product.category)}</span></div><div class="product-content"><div class="product-kicker">${t('sourcePrice')} <span>$${product.usd}</span></div><button class="product-name" data-product="${product.index}">${t('name'+product.index)}</button><div class="card-footer"><div><small>${t('estimate')}</small><strong>${money(total(product))}</strong></div><button class="round-button" data-product="${product.index}" aria-label="${t('choose')} ${esc(t('name'+product.index))}">${icon('arrow')}</button></div></div></article>`).join('');
}
function catalog() { return `<section class="hero"><div class="hero-copy"><span class="eyebrow">WORLDWIDE FINDS / ATLAS</span><h1>${t('hero').split('\n').map(line=>`<span>${line}</span>`).join('')}</h1><p>${t('intro')}</p><div class="hero-actions">${button(t('browse'),'browse')}<button class="text-button" data-nav="product">${t('ownLink')}</button></div></div><div class="hero-image">${picture(0)}<span class="image-caption">${t('season')} <span>01 / 03</span></span></div></section><section class="catalog-section" id="catalog"><div class="section-title"><div><span class="eyebrow">THE SELECTION</span><h2>${t('selection')}</h2></div><label class="search-field">${icon('search')}<input id="search" type="search" value="${esc(model.search)}" placeholder="${t('search')}" aria-label="${t('search')}"></label></div><div class="category-tabs" role="group" aria-label="${t('catalog')}">${['all','shoes','tech','accessories'].map(key=>`<button data-category="${key}" aria-pressed="${model.category===key}">${t(key)}</button>`).join('')}</div><div class="product-grid" id="product-grid">${cards()}</div></section><section class="link-strip"><div><span class="eyebrow">YOUR FIND, OUR HELP</span><h2>${t('customLink')}</h2></div><form id="link-form"><label class="sr-only" for="product-url">${t('paste')}</label><input id="product-url" type="url" placeholder="https://…" value="${esc(model.linkValue)}" required><button class="button" type="submit" aria-label="${t('link')}">${icon('arrow')}</button></form><small>${t('sampleLink')}</small></section>`; }
function costDetails(index) { const product=products[index]; return `<details class="disclosure"><summary>${t('breakdown')}<span>+</span></summary><dl class="cost-lines">${[['itemCost',product.usd*12800],['storeShipping',128000],['service',product.usd*12800*.12],['freight',90000],['reserve',18000]].map(([key,amount])=>`<div><dt>${t(key)}</dt><dd>${money(amount)}</dd></div>`).join('')}</dl><p class="fine">${t('estimateNote')}</p></details>`; }
function product() { const index=model.product; const needsSize=index===0; return `<div class="breadcrumbs"><button data-nav="catalog">${t('catalog')}</button><span>/</span><span>${t(products[index].category)}</span></div><section class="product-layout"><div class="product-gallery">${picture(index)}<div class="gallery-caption"><span>${t('country')}</span><span>01 / 01</span></div></div><div class="product-info"><span class="eyebrow">${t(products[index].category)}</span><h1>${t('name'+index)}</h1><div class="source-price">$${products[index].usd}<span>USD · ${t('sourcePrice')}</span></div>${needsSize?`<p class="description">${t('description')}</p><div class="option-label"><span>${t('color')}</span><strong>${t('navy')}</strong><span class="color-swatch" aria-hidden="true"></span></div><div class="size-label"><span>${t('size')}</span><span>EU</span></div><div class="size-options" role="group" aria-label="${t('size')}">${['38','39','40','41','42'].map(size=>`<button data-size="${size}" aria-pressed="${model.size===size}">${size}</button>`).join('')}</div><small class="fine">${t('sizeHint')}</small>`:''}<div class="product-total"><span>${t('estimate')}</span><strong>${money(total(products[index]))}</strong></div><button class="button full" data-action="add" ${needsSize&&!model.size?'disabled':''}>${needsSize&&!model.size?t('selectSize'):t('add')}${icon('bag')}</button><p class="fine">${t('estimateNote')}</p>${costDetails(index)}<details class="disclosure"><summary>${t('customs')}<span>+</span></summary><p>${t('customsText')}</p></details></div></section>`; }
function cart() { const index=model.cartProduct; return `<div class="breadcrumbs"><button data-nav="catalog">${t('back')}</button><span>/</span><span>${t('cart')}</span></div><div class="page-heading"><span class="eyebrow">YOUR NEXT GOOD FIND</span><h1>${model.review?t('review'):t('cart')}</h1></div><div class="checkout-layout"><div><ol class="steps"><li class="${!model.review?'current':''}"><b>1</b>${t('recipient')}</li><li class="${model.review?'current':''}"><b>2</b>${t('review')}</li></ol><article class="cart-row">${picture(index)}<div><span class="eyebrow">${t(products[index].category)}</span><h2>${t('name'+index)}</h2><p>${index===0?'EU '+model.cartSize+' · ':''}${t('units')}</p><button class="text-button" data-nav="product">${t('edit')}</button></div><strong>$${products[index].usd}</strong></article><section class="recipient-panel"><div class="section-title"><h2>${t('recipient')}</h2>${icon('pin')}</div><label for="recipient-name">${t('recipient')}</label><input id="recipient-name" autocomplete="off" value="${esc(t('recipientSample'))}" ${model.review?'readonly':''}><label for="recipient-address">${t('address')}</label><input id="recipient-address" autocomplete="off" value="${esc(t('addressSample'))}" ${model.review?'readonly':''}></section></div><aside class="checkout-summary"><span class="eyebrow">ATLAS / ORDER SUMMARY</span><h2>${t('review')}</h2><div class="product-total"><span>${t('estimate')}</span><strong>${money(total(products[index]))}</strong></div>${costDetails(index)}<details class="disclosure"><summary>${t('customs')}<span>+</span></summary><p>${t('customsText')}</p></details><label class="consent"><input id="consent" type="checkbox" ${model.consent?'checked':''}><span>${t('consent')}</span></label><button class="button full" data-action="checkout" ${!model.consent?'disabled':''}>${model.review?t('confirm'):t('next')}${icon('arrow')}</button><p class="fine">${t('reviewNote')}</p></aside></div>`; }
function account() { return `<div class="account-heading"><div><span class="eyebrow">PERSONAL SPACE / ATLAS</span><h1>${t('overview')}</h1><p>${t('welcome')}</p></div><div class="avatar">A</div></div><div class="account-layout"><aside class="account-menu"><button class="selected">${icon('user')}${t('account')}</button><button data-action="order">${icon('box')}${t('orders')}<span>2</span></button><button data-section="addresses">${icon('pin')}${t('recipients')}</button><button data-section="documents">${icon('doc')}${t('documents')}</button><button data-section="support">${icon('chat')}${t('support')}</button></aside><div><section class="next-action"><div><span class="eyebrow">${t('nextAction')}</span><h2>${t('orderTitle')}</h2><p>${t('orderHint')}</p></div>${button(t('openOrder'),'order')}</section><section class="orders-section"><div class="section-title"><h2>${t('latest')}</h2><span class="fine">02</span></div><button class="order-row" data-action="order">${picture(0)}<span><strong>${t('name0')}</strong><small>AT–1042 · EU 40</small></span><span class="status-tag">${t('warehouse')}</span><span class="order-arrow">${icon('arrow')}</span></button><button class="order-row" data-action="order">${picture(2)}<span><strong>${t('name2')}</strong><small>AT–1041</small></span><span class="status-tag muted">${t('inTransit')}</span><span class="order-arrow">${icon('arrow')}</span></button><div id="order-detail" class="inline-detail" hidden><b>AT–1042</b><p>${t('timeline')}</p><p>${t('orderHint')}</p><small>${t('reviewNote')}</small></div></section><div class="account-details">${[['addresses','recipients','addressesText','pin'],['documents','documents','docsText','doc'],['support','support','supportText','chat']].map(([key,label,textKey,image])=>`<section class="account-disclosure"><h2><button data-section="${key}" aria-expanded="${model.accordion===key}" aria-controls="panel-${key}">${icon(image)}<span>${t(label)}</span>${icon('plus')}</button></h2><div id="panel-${key}" ${model.accordion!==key?'hidden':''}><p>${t(textKey)}</p>${key==='addresses'?`<p><strong>${t('recipientSample')}</strong><br>${t('addressSample')}</p>`:''}</div></section>`).join('')}</div></div></div>`; }
function stateContent() { if(model.state==='loading') return `<section class="state-panel" aria-busy="true"><span class="eyebrow">ATLAS</span><h1>${t('loading')}…</h1><div class="skeletons" aria-hidden="true"><i></i><i></i><i></i></div></section>`; const error=model.state==='error'; return `<section class="state-panel">${icon(error?'chat':'bag')}<h1>${t(error?'error':'empty')}</h1><p>${t(error?'errorText':'emptyText')}</p>${button(t(error?'retry':'catalog'),error?'retry':'reset')}</section>`; }
function render() { document.documentElement.lang=model.lang; document.body.dataset.theme=model.theme; document.querySelector('#app').innerHTML=header()+`<main id="content">${model.state!=='ready'?stateContent():({catalog,product,cart,account}[model.screen])()}</main><footer class="site-footer"><span class="footer-mark">atlas</span><span>${t('country')}</span><button data-nav="account">${t('support')} ${icon('arrow')}</button></footer><nav class="mobile-nav" aria-label="Atlas">${[['catalog','search'],['product','plus'],['cart','bag'],['account','user']].map(([screen,name])=>`<button data-nav="${screen}" ${model.screen===screen?'aria-current="page"':''}>${icon(name)}<span>${t(screen==='product'?'link':screen)}</span></button>`).join('')}</nav>`; }
document.addEventListener('click', event => {
  const button=event.target.closest('button'); if(!button||button.disabled) return;
  if(button.dataset.nav) { navigate(button.dataset.nav); return; }
  if(button.dataset.product!==undefined) { model.product=Number(button.dataset.product); navigate('product'); return; }
  if(button.dataset.save!==undefined) { const id=Number(button.dataset.save); if(model.saved.has(id)) model.saved.delete(id); else model.saved.add(id); button.setAttribute('aria-pressed',String(model.saved.has(id))); return; }
  if(button.dataset.category) { model.category=button.dataset.category; document.querySelectorAll('[data-category]').forEach(item=>item.setAttribute('aria-pressed',String(item.dataset.category===model.category))); document.querySelector('#product-grid').innerHTML=cards(); return; }
  if(button.dataset.size) { model.size=button.dataset.size; render(); document.querySelector(`[data-size="${model.size}"]`).focus(); return; }
  if(button.dataset.section) { model.accordion=model.accordion===button.dataset.section?'':button.dataset.section; render(); document.querySelector(`.account-disclosure [data-section="${button.dataset.section}"]`)?.focus(); return; }
  const action=button.dataset.action;
  if(action==='browse') document.querySelector('#catalog').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
  if(action==='reset') { model.search=''; model.category='all'; navigate('catalog'); }
  if(action==='retry') { model.state='ready'; render(); }
  if(action==='add') { model.cartProduct=model.product; model.cartSize=model.size; model.review=false; navigate('cart'); }
  if(action==='checkout') { if(!model.review) { model.review=true; render(); } else { const status=document.querySelector('#announcement'); status.textContent=t('complete'); status.classList.add('visible'); clearTimeout(window.announcementTimer); window.announcementTimer=setTimeout(()=>status.classList.remove('visible'),6500); } }
  if(action==='order') { const details=document.querySelector('#order-detail'); details.hidden=!details.hidden; if(!details.hidden) details.scrollIntoView({block:'nearest'}); }
});
document.addEventListener('input', event => { if(event.target.id==='search') { model.search=event.target.value; document.querySelector('#product-grid').innerHTML=cards(); } if(event.target.id==='product-url') model.linkValue=event.target.value; });
document.addEventListener('change', event => { if(event.target.id==='consent') { model.consent=event.target.checked; document.querySelector('[data-action="checkout"]').disabled=!model.consent; } });
document.addEventListener('submit', event => { event.preventDefault(); if(event.target.id==='link-form') navigate('product'); });
window.addEventListener('message', event => { if(event.origin!==location.origin||event.source!==parent||event.data?.type!=='atlas-design') return; for(const key of Object.keys(values)) if(values[key].includes(event.data[key])) model[key]=event.data[key]; render(); });
render();
