// Vector store marks: public/store-marks/<key>.svg, cropped to the drawing, and their proportions in
// lib/market/store-marks.ts. Source: Simple Icons (https://simpleicons.org, CC0) — monochrome brand marks,
// drawn by the page in the text colour, so they stay crisp at any size and read in both themes.
//   node --experimental-strip-types scripts/store-marks.mjs <folder with simple-icons <key>.svg files>
// The files are fetched by hand (cdn.jsdelivr.net/npm/simple-icons/icons/<slug>.svg) and saved under the
// Atlas store key; visitors' browsers never call a third party.
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";
import { storeBrands } from "../lib/market/store-brands.ts";

const source = process.argv[2];
if (!source) throw Error("Usage: node --experimental-strip-types scripts/store-marks.mjs <folder>");
const out = join("public", "store-marks");
const keys = new Set(storeBrands.map((brand) => brand.key));
// 24-unit icons rendered at 100 px a unit: the crop is exact to 0.01 of a unit.
const scale = 100;
await mkdir(out, { recursive: true });

const marks = {};
for (const file of (await readdir(source)).filter((name) => name.endsWith(".svg")).sort()) {
  const key = file.slice(0, -4);
  if (!keys.has(key)) throw Error(`${key}: not an Atlas store key`);
  const svg = await readFile(join(source, file), "utf8");
  const path = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((match) => match[1]);
  if (!path.length || !/viewBox="0 0 24 24"/.test(svg)) throw Error(`${key}: not a Simple Icons file`);
  const raster = await sharp(Buffer.from(svg.replace("<svg", `<svg width="${24 * scale}" height="${24 * scale}"`))).flatten({ background: "#fff" }).trim({ threshold: 10 }).toBuffer({ resolveWithObject: true });
  const { width, height, trimOffsetLeft = 0, trimOffsetTop = 0 } = raster.info;
  const box = [-trimOffsetLeft / scale, -trimOffsetTop / scale, width / scale, height / scale].map((value) => Math.round(value * 100) / 100);
  await writeFile(join(out, file), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box.join(" ")}">${path.map((d) => `<path d="${d}"/>`).join("")}</svg>\n`);
  marks[key] = Math.round((box[2] / box[3]) * 100) / 100;
}
await writeFile(join("lib", "market", "store-marks.ts"), `// Generated by scripts/store-marks.mjs: vector marks in public/store-marks/<key>.svg and their width ÷ height.
export const storeMarkRatios: Readonly<Record<string, number>> = ${JSON.stringify(marks)};
`);
console.log(`${Object.keys(marks).length} marks`);
