// Downloads one icon per store brand into public/store-logos/<key>.webp (96x96) and lists the
// brands that have one in lib/market/store-logos.ts. Run once after adding stores:
//   node --experimental-strip-types scripts/store-logos.mjs [--force]
// Icons are fetched here, at build time, so visitors' browsers never call a third party.
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";
import { storeBrands } from "../lib/market/store-brands.ts";

const out = join("public", "store-logos");
const force = process.argv.includes("--force");
// Icons checked by eye and rejected (an empty or unrecognisable square); these brands show a monogram.
const rejected = new Set(["goat"]);
await mkdir(out, { recursive: true });
const existing = new Set((await readdir(out)).filter((name) => name.endsWith(".webp")).map((name) => name.slice(0, -5)));

async function image(url) {
  try {
    const response = await fetch(url, { redirect: "follow", signal: AbortSignal.timeout(10000), headers: { "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15", Accept: "image/png,image/*;q=0.8" } });
    if (!response.ok || !/^image\//.test(response.headers.get("content-type") ?? "")) return null;
    const buffer = Buffer.from(await response.arrayBuffer());
    const meta = await sharp(buffer).metadata();
    await sharp(buffer).resize(8, 8).toBuffer(); // some servers send formats this decoder cannot read
    return meta.width && meta.height ? { buffer, size: Math.min(meta.width, meta.height) } : null;
  } catch {
    return null;
  }
}

// Google's favicon service returns the largest icon it knows (a 16 px globe when it knows none);
// a site's own apple-touch-icon is the fallback.
async function logo(root) {
  let small = null;
  for (const domain of [root, "www." + root]) {
    const google = await image(`https://www.google.com/s2/favicons?domain=${domain}&sz=128`);
    if (google && google.size >= 64) return google;
    if (google && google.size >= 32) small ??= google;
  }
  for (const host of [root, "www." + root]) {
    const touch = await image(`https://${host}/apple-touch-icon.png`);
    if (touch && touch.size >= 64) return touch;
  }
  return small;
}

const found = new Set(force ? [] : [...existing].filter((key) => !rejected.has(key) && storeBrands.some((brand) => brand.key === key)));
const queue = storeBrands.filter((brand) => !rejected.has(brand.key) && (force || !existing.has(brand.key)));
const missing = [];
await Promise.all(Array.from({ length: 8 }, async () => {
  for (let brand = queue.shift(); brand; brand = queue.shift()) {
    let result = null;
    for (const { root } of brand.storefronts) if ((result = await logo(root))) break;
    if (!result) { missing.push(brand.key); continue; }
    try {
      await sharp(result.buffer).resize(96, 96, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } }).webp({ quality: 90 }).toFile(join(out, brand.key + ".webp"));
      found.add(brand.key);
    } catch { missing.push(brand.key); }
  }
}));
const keys = [...found].sort();
await writeFile(join("lib", "market", "store-logos.ts"), `// Generated by scripts/store-logos.mjs: brands with a logo in public/store-logos/<key>.webp.\nexport const storeLogoKeys: readonly string[] = ${JSON.stringify(keys)};\n`);
console.log(`Logos: ${keys.length} of ${storeBrands.length}. Missing: ${missing.sort().join(", ") || "none"}.`);
